### ISSUE TITLE
Porting WritePCAPHandler to Netty

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#10385]
SwiftNIO ships a very interesting handler that allows to dump bytes as PCAP files while these travel the pipeline. This is super useful for debugging. We should port it to Netty:

https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOExtras/WritePCAPHandler.swift

**Comment by hyperxpro** [comment]
Will the handler dump packets received on Netty directly or dumping will happen after packets are decoded?

Example: If I want to dump TLS packets using the handler, will it be possible? I don't wanna dump content decrypted from those TLS packets.

**Comment by johnou** [comment]
@hyperxpro depends where you put the handler in the pipeline :)

**Comment by hyperxpro** [comment]
@johnou Makes sense!

**Comment by devesh-shetty** [comment]
👋 
Could I tackle this?

**Comment by normanmaurer** [comment]
@devesh-shetty sure thing ... Let me know if you have any specific question. Basically it is just about porting the SwiftNIO code to Java :)

**Comment by hyperxpro** [comment]
Will we be writing our own Pcap Writer or some third party library?

**Comment by devesh-shetty** [comment]
Thanks @normanmaurer - will ask questions if I'm puzzled about something.

**Comment by normanmaurer** [comment]
@hyperxpro I think we can write our own... Looking at the SwiftNIO code it seems like this shouldn't be too much work for our use-case.

**Comment by hyperxpro** [comment]
@normanmaurer I got some free time so thought I should give it a shot. I took a look at the SwiftNIO code and it writes TCP Flags too (FIN, ACK, SYN, etc). I'm wondering how we'll be able to do that with Java? I mean, we can't look at TCP Packet Flags without some Pcap library, AFAIK. Can you help me here?

**Comment by Lukasa** [comment]
The SwiftNIO one makes them up. 😉

**Comment by normanmaurer** [comment]
@hyperxpro as @Lukasa said... these are just "dummy values".

**Comment by hyperxpro** [comment]
Alright. PR incoming next week! :D

**Comment by hyperxpro** [comment]
PTAL #10498

**Comment by geoand** [comment]
I have a question about `PcapWriteHandler`: I am looking to integrate it into Vert.x, but I due to how the processing pipeline is beig built up, `PcapWriteHandler#channelActive` does not get called which then obviously makes the whole thing fall down.
My question is whether or not it's safe for `PcapWriteHandler` to also implement `handlerAdded` in the same way that `channelActive` is implemented.

Thanks

**Comment by hyperxpro** [comment]
I think it should work. Did you face any issues when using `handlerAdded`?

**Comment by geoand** [comment]
Some of the time the file was corrupted and wireshark could not open it.

Of course I don't know if that was because of the change I had made to add the `handlerAdded` method, or if it was something else.

That's why I wanted to get your opinion on whether you see any fundamental reason why it would work not if I add `handlerAdded`.

**Comment by geoand** [comment]
Using `handlerAdded` seems to work just fine.

However I have another question: Say one wants to capture information from both a server pipeline and a client pipeline and write it to the same pcap file, should that work?
Asking because I got something like:

```
pcap: File has 1698373744-byte packet, bigger than maximum of 262144
```

**Comment by hyperxpro** [comment]
> I assume that this is happening because of the mixing of segment numbers, right?

Yes, that's correct. Pcap instance should not be shared with other pipelines.

**Comment by geoand** [comment]
Gotcha, thanks.

I'll into lifting that restriction if possible

**Comment by RoganDawes** [comment]
Also looking at this handler. wanting to have more than one stream per pcap file. My current solution (given the package private aspects of the current code) looks like this:

```
import java.io.IOException;
import java.io.OutputStream;
import java.util.concurrent.atomic.AtomicInteger;

import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandler.Sharable;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelPipeline;

@Sharable
public class MyPcapWriteHandler extends ChannelInitializer<Channel> {

    private static final byte[] PCAP_GLOBAL_HEADER = new byte[] { -95, -78, -61, -44, 0, 2, 0, 4, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, -1, -1, 0, 0, 0, 1 };

    private AtomicInteger useCount = new AtomicInteger(0);

    private final OutputStream out;

    private ChannelFutureListener bindListener = new ChannelFutureListener() {
        @Override
        public void operationComplete(ChannelFuture future) throws Exception {
            if (future.isSuccess()) {
                useCount.incrementAndGet();
                future.channel().closeFuture().addListener(closeListener);
            } else {
                out.close();
            }
        }
    };

    private ChannelFutureListener closeListener = new ChannelFutureListener() {
        @Override
        public void operationComplete(ChannelFuture future) throws Exception {
            int users = useCount.decrementAndGet();
            if (users == 0)
                out.close();
        }
    };

    public PcapWriteHandler(OutputStream out) throws IOException {
        this.out = out;
        out.write(PCAP_GLOBAL_HEADER);
    }

    public ChannelFutureListener bindListener() {
        return bindListener;
    }

    public ChannelFutureListener closeListener() {
        return closeListener;
    }

    @Override
    protected void initChannel(Channel ch) throws Exception {
        OutputStream sos = new SynchronizedOutputStream(out);
        ChannelPipeline p = ch.pipeline();
        String me = p.context(this).name();
        p.addAfter(me, null, new io.netty.handler.pcap.PcapWriteHandler(sos, false, false));
        ch.closeFuture().addListener(closeListener);
        useCount.incrementAndGet();
    }
}
```
One (important?) addition is a `SynchronizedOutputStream` wrapper that decorates all methods with a `synchronized` keyword, and the `close()` method stubbed out, so that each `PcapWriteHandler` can write and close their stream, without colliding with other instances. The usage then looks like:
```
ChannelFuture bindFuture = b.bind(address);
bindFuture.addListener(pcapWriteHandler.bindListener());
```
That is when the handler is being used with a ServerSocket, and the pcap should be closed when the server socket is closed (or fails to bind). And then obviously, the actual MyPcapWriteHandler needs to be added to the pipeline at a suitable position. Thoughts on this approach?
I did run into the abovementioned "pcap: File has 1698373744-byte packet, bigger than maximum of 262144" on one occasion, though (actual number varied, I think). Wondering what the underlying cause of that was, will have to dig more.
