### ISSUE TITLE
Http2: server rejects request with valid :protocol pseudo header

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#10436]
### Expected behavior

Server accepts request  with `:protocol` pseudo header (defined in [RFC8441](https://tools.ietf.org/html/rfc8441#section-4)) , if its initial settings contain SETTINGS_ENABLE_CONNECT_PROTOCOL SETTINGS=1.

### Actual behavior
Request is rejected
```
io.netty.handler.codec.http2.Http2Exception$StreamException: Invalid HTTP/2 pseudo-header ':protocol' encountered.
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
	at io.netty.handler.codec.http2.HpackDecoder.validate(HpackDecoder.java:393)
```
Suboptimal workaround is configuring server's `Http2ConnectionHandler` with `http2Builder.validateHeaders(false)`

### Minimal yet complete reproducer code (or URL to code)
https://github.com/jauntsdn/netty-websocket-http2/tree/feature/http2-protocol-header-reject

start `./channel_server.sh`  
start `./channel_client.sh`

### Netty version
4.1.51.Final

**Comment by normanmaurer** [comment]
@ejona86 @bryce-anderson @carl-mastrangelo @slandelle  can you have a look ?

**Comment by carl-mastrangelo** [comment]
This might be reasonable to support with the Http2ConnectionHandler, but not from the Multiplex handler.    Netty /is/ compliant with [RFC 7540](https://tools.ietf.org/html/rfc7540#section-8.1.2.1)  which states:

> Endpoints MUST treat a request or response that contains undefined or invalid pseudo-header fields as malformed

**Comment by ejona86** [comment]
It looks like the problem is that Netty does not support RFC 8441 for bootstrapping websockets. This [code in the sample](https://github.com/jauntsdn/netty-websocket-http2/blob/c7f9799608f9cb29fef93a2f6b5252cb8a2b6192/netty-websocket-http2/src/main/java/com/jauntsdn/netty/handler/codec/http2/websocketx/Http2WebSocketServerHandler.java#L64-L66) is invalid:

```java
    http2Builder
        .initialSettings()
        .put(Http2WebSocketProtocol.SETTINGS_ENABLE_CONNECT_PROTOCOL, (Long) 1L);
```

When you send SETTINGS_ENABLE_CONNECT_PROTOCOL, that means your system understands `:protocol`, which is not true in this case. And Netty should not blindly accept `:protocol` just in case someone set SETTINGS_ENABLE_CONNECT_PROTOCOL.

I think part of the problem here though is that this verification is being done in the hpack decoder. That doesn't seem appropriate, as the pseudo headers are part of HTTP/2, not HPACK.

**Comment by mostroverkhov** [comment]
> This code in the sample is invalid

It is valid as soon as channel pipeline contains rfc8441 websocket-over-http2 handlers. Repository linked in the issue implements rfc8441, and having parameter SETTINGS_ENABLE_CONNECT_PROTOCOL SETTINGS=1 is required by that spec for server to advertise websocket-over-http2 support.

> When you send SETTINGS_ENABLE_CONNECT_PROTOCOL, that means your system understands :protocol, which is not true in this case.

In this particular case system *does* understand `:protocol` because It is an [implementation](https://github.com/jauntsdn/netty-websocket-http2) of rfc8441.

netty's own http2 handlers deprive external code from supporting websocket-over-http2 - by requiring `validateHeaders = false` on the server for this use case. Requiring `validateHeaders = false` in practice means said external code cant be used on servers exposed to untrusted clients. 

If having `server advertising ENABLE_CONNECT_PROTOCOL, but no appropriate handler` is not considered a bug on library user side / needs to be handled by netty itself, then one solution may be as follows:

* server opts-in for websocket-over-http2 with `SETTINGS_ENABLE_CONNECT_PROTOCOL=1`. 
* add marker interface `Http2WebsocketHandler` that is used by  netty's http2 handlers to decide if pipeline actually supports websocket-over-http2. It helps with websocket requests incorrectly treated as CONNECT requests.
* if server opted for websocket-over-http2, and there is single appropriate handler on pipeline (implements marker `Http2WebsocketHandler`), then `:protocol` pseudo header is treated as acceptable.

This should work unless some 3rd party grabbed ENABLE_CONNECT_PROTOCOL settings code (0x08) for other purposes.

**Comment by ejona86** [comment]
>> This code in the sample is invalid

> It is valid as soon as channel pipeline contains rfc8441 websocket-over-http2 handlers. 

No, it is not. Because RFC 8441 also requires accepting the `:protocol` header, which the code does not do.

> In this particular case system does understand :protocol because It is an implementation of rfc8441.

The "system" includes HpackDecoder, which obviously does _not_ support RFC 8441.

This isn't a case of "I made Netty support RFC 8441" but rather "I want to make Netty support RFC 8441." This is a feature request to figure out how Netty can allow supporting RFC 8441.

> by requiring validateHeaders = false on the server for this use case

That's actually _required_ by HTTP/2. You are no longer HTTP/2 (with or without RFC 8441) if you disable those checks. As I said, I think those checks are put in the wrong place as ideally you'd be able to allow an additional header to be validated properly. You should not disable the checks completely (unless potentially you reimplemented them yourself).

> server opts-in for websocket-over-http2 with SETTINGS_ENABLE_CONNECT_PROTOCOL=1.
add marker interface Http2WebsocketHandler that is used by netty's http2 handlers to decide if pipeline actually supports websocket-over-http2...

This is a very implicit approach. I'd expect we'd want a more explicit approach. For example, providing the Http2WebsocketHandler to the HTTP/2 code to be used if websocket connect is used (similar to existing Upgrade handling). (If the HTTP/2 code has to know about Http2WebsocketHandler already, I see little point in implicit wiring.)

But it also sort of looks like there is no need for it to be Websocket-specific. SETTINGS_ENABLE_CONNECT_PROTOCOL is intended to be generic. So maybe we just need an option for enabling SETTINGS_ENABLE_CONNECT_PROTOCOL in the innards and then let your handler handle the CONNECT request completely. I'd have to look at the code more to see if that behavior should be enabled by the SETTINGS_ENABLE_CONNECT_PROTOCOL setting directly or whether we'd want an API when building the HTTP/2 classes and have the Netty internals set that setting.

**Comment by normanmaurer** [comment]
@ejona86 @mostroverkhov so I am a bit lost here... what do you propose to moving forward here ?

**Comment by ejona86** [comment]
Netty probably needs direct support of the `:protocol` header. It is unclear whether we have an option to enable that support or whether we do it implicitly based on the SETTINGS.

**Comment by mostroverkhov** [comment]
@normanmaurer Looking at ejona86's suggestions 
> I think part of the problem here though is that this verification is being done in the hpack decoder. That doesn't seem appropriate, as the pseudo headers are part of HTTP/2, not HPACK.

> As I said, I think those checks are put in the wrong place as ideally you'd be able to allow an additional header to be validated properly.

I read them as a hint to have headers validation pluggable, with rfc7540 as default, and optional rfc8441 (that is also part of this project). 

I am happy with any solution which allows using netty's http2 handlers for websocket-over-http2, and seems there are no significant blockers other than `:protocol` pseudo-header validation issue.

**Comment by mostroverkhov** [comment]
@normanmaurer @ejona86 I have made few changes related to this on https://github.com/mostroverkhov/netty/tree/header-validators just to start things going.  

`AbstractHttp2ConnectionHandlerBuilder` is extended with protected `validateHeaders(Http2HeadersValidationType http2HeadersValidationType)`. Method is exposed on `Http2FrameCodecBuilder` and `Http2ConnectionBuilder`.
Public `Http2HeadersValidationType` is enum comprised of `NONE, RFC7540, RFC8441`.

**Comment by normanmaurer** [comment]
@ejona86 @carl-mastrangelo can you have a look ?

**Comment by mostroverkhov** [comment]
@normanmaurer It turned out netty's http2 headers validation is basically a "plug" because It accounts only for small subset of what's stated explicitly in specification [8.1.1.2](https://tools.ietf.org/html/rfc7540#section-8.1.2.2) and [8.1.1.3](https://tools.ietf.org/html/rfc7540#section-8.1.2.3). Because netty's validation checks are far from being exhaustive, and also are blocker for any websockets-over-http2 implementation, I ended up doing my own [validation](https://github.com/jauntsdn/netty-websocket-http2/blob/develop/netty-websocket-http2/src/main/java/com/jauntsdn/netty/handler/codec/http2/websocketx/Http2WebSocketValidator.java) of both http and websocket headers

**Comment by mostroverkhov** [comment]
It seems this is fixed already by https://github.com/netty/netty/pull/11192 in a very straightforward way, closing
