### ISSUE TITLE
How to configure ALPN On Android Device （Netty Http2 Server）

### ISSUE THREAD

**Issue by lmh1986** [netty/netty#10431]
background:
We are trying to use the Netty server based on http2 (SSL) to our Android project, and we plan to run the server on the Android device.Use this device as a routing node for other terminals in the LAN. We have implemented ssl in the current situation, but we have encountered problems with the ALPN configuration.

I have referenced a lot of information about Http2 ALPN on google, but almost all of them are configuration information on the web side, did not find anything about Android (maybe this case is relatively rare)

This problem has been bothering me for many days, and now the most urgent thing is how to use Android Studio /Gradle tools,
Configure the ALPN item correctly and implement Http2.

Any help would be greatly appreciated. Thanks!

Expected behavior
Run Netty Http2 server on Android Device

Actual behavior
We are having trouble configuring ALPN on Android Studio.

Steps to copy
Refer to the official example on Netty-http2, using Keystore type BKS instead of JKS. ALPN config problems are prone to

Mesh version
4.1.5.Final

JVM version (e.g. java -version)
openjdk version 1.8.0_202

Operating system version (e.g. uname -a)
Android Device 9.0

eg: 
    I try to config alpn like below,but nothing help.
  
![image](https://user-images.githubusercontent.com/4550759/88639153-0a7dd000-d0ef-11ea-9f6d-03e9a039da6d.png)

**Comment by hyperxpro** [comment]
Did you take a look at HTTP/2 Examples?

**Comment by lmh1986** [comment]
> Did you take a look at HTTP/2 Examples?

Yes. That's the first things i had done , but when i config the sslcontext and run the server on android device ,i got the alpn issue. I sure that this issue come from Http2ServerInitializer-->configureSsl-->sslCtx.newHandler(ch.alloc()). 

I then searched Google for a lot of information about the alpn configuration and how it works on android devices, but I couldn't find anything of value, so I had to ask you for help here.

**Comment by hyperxpro** [comment]
Show me `SslContextBuilder` code

**Comment by lmh1986** [comment]
> Show me `SslContextBuilder` code

Hi hyperxpro, this is SslContextBuilder's code and it also refer from HTTP/2 Examples.
![image](https://user-images.githubusercontent.com/4550759/89115101-c572e880-d4b6-11ea-9462-ffd5abbaa806.png)

and once i use following code to configure ssl , ALPN exceptions must appear.
![image](https://user-images.githubusercontent.com/4550759/89115124-f0f5d300-d4b6-11ea-965b-81f8da794f66.png)

I have no idea. Any help would be greatly appreciated. Thanks!

**Comment by normanmaurer** [comment]
Sorry I have no idea about android... maybe @ejona86 knows ?

**Comment by ejona86** [comment]
Jetty's ALPN boot is only for OpenJDK; it isn't possible to use it on Android (there is no `-Xbootclasspath`). Using it compile-time does nothing; it is supposed to be used at runtime.

Android uses Conscrypt. But there's three different Conscrypt instances: the one provided as part of the OS (on non-ancient devices), the one provided by Google Play Services Dynamic Security Provider (and thus should be preferred over the OS one because it is more up-to-date), and Conscrypt itself. Their respective package names are `com.android.org.conscrypt`, `com.google.android.gms.org.conscrypt`, `org.conscrypt`.

`org.conscrypt` is available on OpenJDK as well. This is the version that Netty supports. Using `org.conscrypt` on Android is possible, but rarer, as it is large (MBs). I typically only see people discussing using it for China-deployed apps, since Google Play Services isn't available there. You could deploy `org.conscrypt:conscrypt-android` with your app and it would work.

Starting in Android 10, Android added the "Java 9 ALPN APIs." Conscrypt supports those APIs when the system supports them. So in Android 10+ you could use Netty with the OS-provided Conscrypt or the Google-Play-Services Conscrypt.

**Comment by lmh1986** [comment]
@ejona86 

Thanks for your important answer. I believe this information will be of great help to my problems which I have meet. At this moment,I had took the alternative and switch to the HTTP1.1 scenario for the time being. Once I finish the urgent matters at hand, I will go back to study using Conscrypt to realize ALPN scheme according to the information you provided. Thanks again for your help !

**Comment by normanmaurer** [comment]
I think we can close this for now
