### ISSUE TITLE
Is it possible to close connection when server receive SYN from client?

### ISSUE THREAD

**Issue by ctlove0523** [netty/netty#10913]
I have a tcp server and i want to control concurrency of establish connection between client to my server,like one second only process 100 establish connection request,the 101 request will be refused.So I need close connection in second step of 3-way-handshake.
![](https://camo.githubusercontent.com/9fa277572eb26f706f221812d4fb67f03b9e654a4a2b94ea8abcfb1ae95bef8b/687474703a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f612f61322f5463705f73746174655f6469616772616d5f66697865642e737667)

## Motivation
If we can do something in step 2 of 3-way-handshake,then we can make a **RateLimiter** to protect our server avoid run out of CPU.

## Desired solution
add method like `ChannelHandlerContext fireSyncReceived();` in `ChannelHandlerContext`

**Comment by hyperxpro** [comment]
I have this feature in a private source branch because my application requires low-level info. You can't get into like `SYN` received in Netty because it makes no sense for a normal application.

For Connection RateLimiter, checkout https://github.com/shieldblaze/ExpressGateway/blob/main/security/src/main/java/com/shieldblaze/expressgateway/security/NACL.java
