### ISSUE TITLE
ThreadSanitizer detected data race in EpollEventLoop

### ISSUE THREAD

**Issue by sanjaypujare** [netty/netty#11219]
### Expected behavior
ThreadSantizer doesn't find any race conditions

### Actual behavior

ThreadSanitizer found data race as follows:

Code in io.netty.channel.epoll.EpollEventLoop.java:521
```
            try {
                eventFd.close();
            } catch (IOException e) {
                logger.warn("Failed to close the event fd.", e);
            }
````
Code in io.netty.channel.epoll.EpollEventLoop.java:183
```
    protected void wakeup(boolean inEventLoop) {
        if (!inEventLoop && nextWakeupNanos.getAndSet(AWAKE) != AWAKE) {
            // write to the evfd which will then wake-up epoll_wait(...)
            Native.eventFdWrite(eventFd.intValue(), 1L);
        }
    }
```

Access to `eventFd` (which is a `FileDescriptor`) should be protected with a lock.

### Steps to reproduce

Run a bigtable test with TSAN enabled for 100 runs.

### Netty version
4.1.52.Final
### JVM version (e.g. `java -version`)
JDK11
### OS version (e.g. `uname -a`)
Not known

**Comment by hyperxpro** [comment]
Please upgrade to the latest version of Netty and see if the issue still persists.

**Comment by normanmaurer** [comment]
@sanjaypujare actually I think this is a false postive and harmless. Using the eventFD in a multi-threaded environment is actually valid and expected. @ejona86 WDYT ?

**Comment by ejona86** [comment]
@normanmaurer, no, if this is still occurring (compare to #9362) I don't think it is harmless, because it is a race with `close()`. We can't be writing to arbitrary fds. This was what https://github.com/netty/netty/pull/9535 fixed before, and there was a "fix" before that one. But #9535 _felt_ really good, so I'm quite uncertain why we'd be seeing it again.

@YifeiZhuang had noticed this recently and we were going to delay a bit before opening an issue. But a separate report from outside the team got routed to @sanjaypujare who didn't know that was going on.

**Comment by njhill** [comment]
The only things I can think of:
- One of the "safeguard" timeouts was hit, in which case there might be a `Missed eventfd write (not seen after > 1 second)` message in the log (is there?). We probably should have logged similarly [here](https://github.com/netty/netty/blob/7b9a97a81f10ea574a8e6f2596075615d2eeb185/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L513) and [here](https://github.com/netty/netty/blob/7b9a97a81f10ea574a8e6f2596075615d2eeb185/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L523).
- There are invalid assumptions in how the thread sanitizer instruments file descriptors. There's no java memory barrier between a last write and the close, so maybe it's mistaking that for a race somehow (false positive)? i.e. I assume it's possible for the EL thread to close the fd before the write syscall in the other thread _returns_, even though the underlying write must have completed since the closing thread must have seen the corresponding edge event.

**Comment by ejona86** [comment]
Here's the fuller report:
```
  Write of size 8 at 0x7ba0000187b0 by thread T52:
    #0 close llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1729:3 (blah+0x14587b7)
    #1 netty_unix_filedescriptor_close third_party/java_src/netty4/transport-native-unix-common/src/main/c/netty_unix_filedescriptor.c:81:8 (blah+0x18fb577)
    #2 <null> <null> (0x7f6b02a10f25)
    #3 io.netty.channel.unix.FileDescriptor.close()V FileDescriptor.java:79 
    #4 io.netty.channel.epoll.EpollEventLoop.cleanup()V EpollEventLoop.java:522 
    #5 io.netty.util.concurrent.SingleThreadEventExecutor$4.run()V SingleThreadEventExecutor.java:1036 
    #6 io.netty.util.internal.ThreadExecutorMap$2.run()V ThreadExecutorMap.java:74 
    #7 io.netty.util.concurrent.FastThreadLocalRunnable.run()V FastThreadLocalRunnable.java:30 
    #8 java.lang.Thread.run()V Thread.java:835 
    #9 (Generated Stub) <null> 

  Previous read of size 8 at 0x7ba0000187b0 by thread T56 (mutexes: write M123286043293359664):
    #0 eventfd_write llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:6705:3 (blah+0x1481f1e)
    #1 netty_epoll_native_eventFdWrite third_party/java_src/netty4/transport-native-epoll/src/main/c/netty_epoll_native.c:149:20 (blah+0x18f9e3a)
    #2 <null> <null> (0x7f6b02a10f25)
    #3 io.netty.channel.epoll.EpollEventLoop.wakeup(Z)V EpollEventLoop.java:186 
    #4 io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(JJLjava/util/concurrent/TimeUnit;)Lio/netty/util/concurrent/Future; SingleThreadEventExecutor.java:670 
    #5 io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(JJLjava/util/concurrent/TimeUnit;)Lio/netty/util/concurrent/Future; MultithreadEventExecutorGroup.java:163 
    #6 io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Lio/netty/channel/EventLoopGroup;)V Utils.java:435 
    #7 io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Ljava/lang/Object;)V Utils.java:398 
    #8 io.grpc.internal.SharedResourceHolder$2.run()V SharedResourceHolder.java:139 
    #9 io.grpc.internal.LogExceptionRunnable.run()V LogExceptionRunnable.java:43 
    #10 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; Executors.java:515 
    #11 java.util.concurrent.FutureTask.run()V FutureTask.java:264 
    #12 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V ScheduledThreadPoolExecutor.java:304 
    #13 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V ThreadPoolExecutor.java:1128 
    #14 java.util.concurrent.ThreadPoolExecutor$Worker.run()V ThreadPoolExecutor.java:628 
    #15 java.lang.Thread.run()V Thread.java:835 
    #16 (Generated Stub) <null> 
```

I do notice how close() is last, which isn't as concerning as the other ordering. I see another report that is the same. But I need to look at how we guarantee it is always last.

> One of the "safeguard" timeouts was hit, in which case there might be a Missed eventfd write (not seen after > 1 second) message in the log (is there?).

I don't see any such log for one report. I'm trying to get the logs for the other report. TSAN does introduce overhead, so it may make those timeouts more likely to be hit.

> There's no java memory barrier between a last write and the close, so maybe it's mistaking that for a race somehow (false positive)?

Maybe. Since we read from the same fd before closing it (IIRC), which is something that would be done in C-based event loop code as well, I'd sort of expect it to handle that correctly without knowledge of the Java memory semantics. The tool is very much a "C++ tool adapted to work with Java", but the problem reported here is more a C problem. Maybe C stacks generally need some other synchronization in place since they don't have a GC, or some such "using it in a new way."

**Comment by njhill** [comment]
> I do notice how close() is last, which isn't as concerning as the other ordering.

Why is it concerning at all? (not questioning, asking out of ignorance)

> Since we read from the same fd before closing it 

Actually we don't read before closing it, the way eventfd is used we don't need to. Maybe that's what's unique about this case?

**Comment by ejona86** [comment]
> Why is it concerning at all? (not questioning, asking out of ignorance)

It can happen when you "win a race" but the race is still present. Since there appears to be no synchronization there is nothing that _guarantees_ a problematic ordering won't take place. I'd say the majority of problems TSAN finds are like that.

**Comment by njhill** [comment]
@ejona86 makes sense, thanks! My guess is that it doesn't recognize the causal relationship between the fd write completion and detected epoll event.
