### ISSUE TITLE
HttpPostMultipartRequestDecoder IndexOutOfBoundsException error with netty 4.1.65.Final

### ISSUE THREAD

**Issue by liubao68** [netty/netty#11334]
The problem happens when using latests vert.x version. see https://github.com/eclipse-vertx/vert.x/issues/3949
But I guess is a problem with netty. 

### Expected behavior
Uploading multiple form datas/files will success. 

### Actual behavior
Fails ramdomly. 

### Steps to reproduce
See original issue. I have a project test case, but not have a minimal test case with netty yet. 

### Netty version
4.1.65.Final . After  I change to 4.1.59.Final, this problem is gone.

**Comment by fredericBregier** [comment]
@liubao68 I think I have found the reason.

@normanmaurer except a check that was missing in the multipartDecoder, i've found a possible issue while debugging within `UnpooledUnsafeDirectByteBuf` (at least there).
The reason we did not get this issue before in the Junit test was because the underlying check of access to the `undecodedChunk` while using `buffer.getByte(fullPosition)` is only checking the following the following in MathUtil:

    /**
     * Determine if the requested {@code index} and {@code length} will fit within {@code capacity}.
     * @param index The starting index.
     * @param length The length which will be utilized (starting from {@code index}).
     * @param capacity The capacity that {@code index + length} is allowed to be within.
     * @return {@code false} if the requested {@code index} and {@code length} will fit within {@code capacity}.
     * {@code true} if this would result in an index out of bounds exception.
     */
    public static boolean isOutOfBounds(int index, int length, int capacity) {
        return (index | length | capacity | (index + length) | (capacity - (index + length))) < 0;
    }

But the underlying buffer has a capacity bigger than writerIndex, so accessing `buffer.getByte(writerIndex)` does not thrown an `IndexOutOfBoundsException` (index = writerIndex, length = 1, capacity = 2048).

So when I try to reproduce this issue, I am in fact unable to do so, since there is never such an issue but it should.

I will propose first a fix for the multipart decoder (simple).
But I don't know how to adress this second issue (it should raized an `IndexOutOfBoundsException` if it is a `read` operation).
