### ISSUE TITLE
QueryStringDecoder doesn't parse encoded question mark

### ISSUE THREAD

**Issue by doom369** [netty/netty#11471]
URL like this is not parsed:

`https://host/path%3Fparam=1`

This one works:

`https://host/path?param=1`

```
        String uri = "https://host/path%3Fparam=1";
        QueryStringDecoder queryDecoder = new QueryStringDecoder(uri);
        assertNull(queryDecoder.parameters().get("param")); //true, is null
```

**Comment by normanmaurer** [comment]
@slandelle can you have a look ?

**Comment by slandelle** [comment]
@doom369 This is the expected result.

`https://host/path%3Fparam=1` is an URI with a `/path?param=1` path and no query parameter.

Then, `QueryStringDecoder`'s javadoc is wrong in many places, eg `Splits an HTTP query string into a path string and key-value parameter pairs.` while it actually expects a relative URL. In particular, in the above example, `queryDecoder.path()` will return `https://host/path?param=1` because QueryStringDecoder assumes everything before the `?` is the path and doesn't deal with scheme, user-info, scheme, port, etc...
It would be worth revisiting the javadoc. `QueryStringDecoder` is definitely not an URI parser.

**Comment by doom369** [comment]
I see. Ok. No problem.
