### ISSUE TITLE
``netty-all`` does not really manage the versions of each module

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#11826]
SpringBoot has specified ``<netty.version>4.1.69.Final</netty.version>``  I hope to use 4.1.70 to overwrite the lower version of netty, but when I use ``netty-all``, I find that its dependent sub module is still the lower version

``netty-all`` does not really manage the versions of each module

![image](https://user-images.githubusercontent.com/13413715/140938569-4d2733a0-8fc2-458e-9ce2-6163bf304c9e.png)

**Comment by chrisvest** [comment]
Maven doesn't rely on any interpretation of versions for resolving transitive dependencies, but instead follows the structure of the connected pom files: http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

You need a dependency management section in your pom in order to control how the transitive dependencies are resolved.

**Comment by chrisvest** [comment]
Do you get the right versions if you add the following to your pom file?

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>4.1.70</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by brucelwl** [comment]
Thank
