### ISSUE TITLE
Add Unpooled.unreleasableBuffer(..) 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#1197]
Often it may be useful to create an unreleasable view on a ByteBuf and so prevent from have it freed. This is especially true if a user wants to manage its ByteBuf by him own. In fact I added it in vert.x because I needed it so I think it is time to bring it into Netty.

**Comment by luengnat** [comment]
@normanmaurer I encountered an issue with the inadvertent use of this one in Vertx's Buffer.buffer(ByteBuf). To make sure it works fine with pooling, I release the buffer after it has been written out. It seems to work fine in most of the case. However, when there is a backpressure, this buffer may be held for later flush cycle. This results in  an unpredictable lifetime of the buffer itself. Since I have release() the buffer, the buffer is then eligible to be reused in other tasks. This leads to a corruption of the buffer before it has been written out when another task overwrites the pending buffer. I think there is really no good way of managing a lifecycle of a buffer in Vert.x's callback model using this because
1. This prevents buffer pooling as the reference counting is not managed
2. There is no mechanism to be notified when the buffer is still in use after write() call

Do you think there is a better way to handle this?

**Comment by luengnat** [comment]
I question this because I wish it is either better documented in Vert.x or Netty should not allow a pooled buffer to be wrapped by Unpooled.unreleasableBuffer by default. The only use-case I can see is only if the buffer wrapped by Unpooled.unreleasableBuffer will only be used in a short single-threaded context. Otherwise, it seems to be almost always wrong to do so.

**Comment by Scottmitch** [comment]
can you provide a link where a pooled buffer is made unreleasable (via wrapping in `Unpooled.unreleasableBuffer`)?

**Comment by luengnat** [comment]
Vert.x is doing that inside Buffer.buffer(ByteBuf) that ultimately calls   

```
BufferImpl(ByteBuf buffer) {
    this.buffer = Unpooled.unreleasableBuffer(buffer);
  }
```

**Comment by Scottmitch** [comment]
I'm not familiar with vertx but this does sound suspicious if `buffer` comes from a pooled allocator ... have you filed an issue with the vertx folks?

**Comment by luengnat** [comment]
Not yet. What I would like to bring up is that there is no good mechanism to detect that within netty. @Scottmitch do you think it's possible to detect whether the ByteBuf is pooled or not?

**Comment by normanmaurer** [comment]
I guess we could add something like isPooled()

**Comment by Scottmitch** [comment]
@normanmaurer - if we do want to support this ... once we can extend APIs i would prefer to put a method on the allocator ... basically to ask the allocator if it allocated the buffer.

**Comment by vietj** [comment]
@normanmaurer +1 for isPooled() instead of https://github.com/eclipse/vert.x/pull/1561/files#diff-edb16f8f08fc84c8d4c27b8cf87cce0aR113
