### ISSUE TITLE
[feautre request] Add a util method to get maxDirectMemory

### ISSUE THREAD

**Issue by Shoothzj** [netty/netty#12103]
Netty's `PlatformDependent.maxDirectMemory()` is powerful and general.
In other project, we want to read the `maxDirectMemory` too. 
But we can't directly use `PlatformDependent.maxDirectMemory()` , because it will wrong if user set `io.netty.maxDirectMemory` greater than zero. 
Instead of copy and paste netty's code(Under Apache License), I want a UtilityClass to get `PlatformDependent.maxDirectMemory0` result.

I am not very familiar with netty code,  I can work on this under guides.

Thanks for your help.

**Comment by normanmaurer** [comment]
@chrisvest what do you think... Not sure we want to expose just another public method.

**Comment by franz1981** [comment]
@normanmaurer it's -1  to me, but I would like to understand why @Shoothzj need it/the exact use case

**Comment by Shoothzj** [comment]
@franz1981 It's started with https://github.com/apache/bookkeeper/pull/2989 when locating a `Out of DirectMemory Error`. We found the the maxDirectMemory read by bookkeeper is not correct with *huawei jdk 11*, but the result read by netty is correct.
I want to improve the maxDirectMemory readed by bookkeepe but without the `io.netty.maxDirectMemory`.

Please point out if I didn't make it clear. My English is not good. Thanks
cc @normanmaurer

**Comment by franz1981** [comment]
wdyt @normanmaurer ?

I know that Netty's `OutOfDirectMemoryError` throwing condition is tied with the Netty's notion of max direct memory, hence if we allow the exception to leak ie `OutOfDirectMemoryError` is public, maybe makes sense our limit to leak as well. 
Another option for @Shoothzj could be, if we change `OutOfDirectMemoryError` in order to expose exception fields that represent our limits/current values ie 
`requestedCapacity, usedCapacity, DIRECT_MEMORY_LIMIT as max allowed capacity`

**Comment by chrisvest** [comment]
@normanmaurer @franz1981 I don't see a big problem in exposing `maxDirectMemory0` as `estimateMaxDirectMemory`.

**Comment by johnou** [comment]
technically it wouldn't even be part of the public API, last I recall PlatformDependent is in the "internal" package, that said could annotate it as UnstableApi?
