### ISSUE TITLE
StacklessClosedChannelException caught JavaFlightRecorder in Vert.X

### ISSUE THREAD

**Issue by asurovenko-zeta** [netty/netty#12168]
### Expected behavior
There are no any exception

### Actual behavior
There are a lot of exceptions caught JavaFlightRecorder (io.netty.channel.StacklessClosedChannelException)

### Netty version
4.1.74.Final

### JVM version (e.g. `java -version`)
15.0.1

### OS version (e.g. `uname -a`)
AWS EC2 Instance (Linux ip-<IP>.ec2.internal 4.18.0-257.el8.x86_64 #1 SMP Thu Dec 3 22:16:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

Why such exceptions are happening? What the cause of it?

```
void java.lang.Exception.<init>():55
void java.io.IOException.<init>():47
void java.nio.channels.ClosedChannelException.<init>():53
void io.netty.channel.StacklessClosedChannelException.<init>():29
StacklessClosedChannelException io.netty.channel.StacklessClosedChannelException.newInstance(Class, String):41
void io.netty.channel.AbstractChannel$AbstractUnsafe.close(ChannelPromise):607
void io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.close(ChannelPromise):815
void io.netty.channel.DefaultChannelPipeline$HeadContext.close(ChannelHandlerContext, ChannelPromise):1352
void io.netty.channel.AbstractChannelHandlerContext.invokeClose(ChannelPromise):622
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.close(ChannelPromise):606
void io.netty.handler.codec.compression.JdkZlibEncoder$2.operationComplete(ChannelFuture):267
void io.netty.handler.codec.compression.JdkZlibEncoder$2.operationComplete(Future):264
void io.netty.util.concurrent.DefaultPromise.notifyListener0(Future, GenericFutureListener):578
void io.netty.util.concurrent.DefaultPromise.notifyListenersNow():552
void io.netty.util.concurrent.DefaultPromise.notifyListeners():491
Promise io.netty.util.concurrent.DefaultPromise.addListener(GenericFutureListener):184
ChannelPromise io.netty.channel.DefaultChannelPromise.addListener(GenericFutureListener):95
ChannelFuture io.netty.channel.DefaultChannelPromise.addListener(GenericFutureListener):30
void io.netty.handler.codec.compression.JdkZlibEncoder.close(ChannelHandlerContext, ChannelPromise):264
void io.netty.channel.AbstractChannelHandlerContext.invokeClose(ChannelPromise):622
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.close(ChannelPromise):606
ChannelFuture io.netty.channel.DefaultChannelPipeline.close(ChannelPromise):994
ChannelFuture io.netty.channel.AbstractChannel.close(ChannelPromise):268
ChannelFuture io.netty.channel.embedded.EmbeddedChannel.close(ChannelPromise):568
ChannelFuture io.netty.channel.embedded.EmbeddedChannel.close():555
boolean io.netty.channel.embedded.EmbeddedChannel.finish(boolean):503
boolean io.netty.channel.embedded.EmbeddedChannel.finish():483
void io.netty.handler.codec.http.HttpContentEncoder.finishEncode(List):341
boolean io.netty.handler.codec.http.HttpContentEncoder.encodeContent(HttpContent, List):272
void io.netty.handler.codec.http.HttpContentEncoder.encodeFullResponse(HttpResponse, HttpContent, List):227
void io.netty.handler.codec.http.HttpContentEncoder.encode(ChannelHandlerContext, HttpObject, List):189
void io.netty.handler.codec.http.HttpContentEncoder.encode(ChannelHandlerContext, Object, List):56
void io.netty.handler.codec.MessageToMessageCodec$1.encode(ChannelHandlerContext, Object, List):67
void io.netty.handler.codec.MessageToMessageEncoder.write(ChannelHandlerContext, Object, ChannelPromise):89
void io.netty.handler.codec.MessageToMessageCodec.write(ChannelHandlerContext, Object, ChannelPromise):116
void io.vertx.core.http.impl.HttpChunkContentCompressor.write(ChannelHandlerContext, Object, ChannelPromise):38
void io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Object, ChannelPromise):717
void io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Object, ChannelPromise):709
void io.netty.channel.AbstractChannelHandlerContext.write(Object, boolean, ChannelPromise):792
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.write(Object, ChannelPromise):702
void io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChannelHandlerContext):303
void io.netty.handler.stream.ChunkedWriteHandler.flush(ChannelHandlerContext):132
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush0():750
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush():742
ChannelHandlerContext io.netty.channel.AbstractChannelHandlerContext.flush():728
void io.netty.channel.ChannelDuplexHandler.flush(ChannelHandlerContext):127
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush0():750
void io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Object, ChannelPromise):765
void io.netty.channel.AbstractChannelHandlerContext.write(Object, boolean, ChannelPromise):790
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Object, ChannelPromise):758
void io.vertx.core.net.impl.ConnectionBase.write(Object, Boolean, ChannelPromise):178
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, boolean, ChannelPromise):230
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, ChannelPromise):215
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, FutureListener):211
void io.vertx.core.http.impl.Http1xServerResponse.end(Buffer, PromiseInternal):407
Future io.vertx.core.http.impl.Http1xServerResponse.end(Buffer):382
```

**Comment by zhrgithub** [comment]
你猜猜是什么原因造成的  哈哈哈


| |
zhr
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年03月12日 ***@***.***> 写道：

Expected behavior

There are no any exception

Actual behavior

There are a lot of exceptions caught JavaFlightRecorder (io.netty.channel.StacklessClosedChannelException)

Netty version

4.1.74.Final

JVM version (e.g. java -version)

15.0.1

OS version (e.g. uname -a)

AWS EC2 Instance (Linux ip-.ec2.internal 4.18.0-257.el8.x86_64 #1 SMP Thu Dec 3 22:16:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

Why such exceptions are happening? What the cause of it?

void java.lang.Exception.<init>():55
void java.io.IOException.<init>():47
void java.nio.channels.ClosedChannelException.<init>():53
void io.netty.channel.StacklessClosedChannelException.<init>():29
StacklessClosedChannelException io.netty.channel.StacklessClosedChannelException.newInstance(Class, String):41
void io.netty.channel.AbstractChannel$AbstractUnsafe.close(ChannelPromise):607
void io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.close(ChannelPromise):815
void io.netty.channel.DefaultChannelPipeline$HeadContext.close(ChannelHandlerContext, ChannelPromise):1352
void io.netty.channel.AbstractChannelHandlerContext.invokeClose(ChannelPromise):622
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.close(ChannelPromise):606
void io.netty.handler.codec.compression.JdkZlibEncoder$2.operationComplete(ChannelFuture):267
void io.netty.handler.codec.compression.JdkZlibEncoder$2.operationComplete(Future):264
void io.netty.util.concurrent.DefaultPromise.notifyListener0(Future, GenericFutureListener):578
void io.netty.util.concurrent.DefaultPromise.notifyListenersNow():552
void io.netty.util.concurrent.DefaultPromise.notifyListeners():491
Promise io.netty.util.concurrent.DefaultPromise.addListener(GenericFutureListener):184
ChannelPromise io.netty.channel.DefaultChannelPromise.addListener(GenericFutureListener):95
ChannelFuture io.netty.channel.DefaultChannelPromise.addListener(GenericFutureListener):30
void io.netty.handler.codec.compression.JdkZlibEncoder.close(ChannelHandlerContext, ChannelPromise):264
void io.netty.channel.AbstractChannelHandlerContext.invokeClose(ChannelPromise):622
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.close(ChannelPromise):606
ChannelFuture io.netty.channel.DefaultChannelPipeline.close(ChannelPromise):994
ChannelFuture io.netty.channel.AbstractChannel.close(ChannelPromise):268
ChannelFuture io.netty.channel.embedded.EmbeddedChannel.close(ChannelPromise):568
ChannelFuture io.netty.channel.embedded.EmbeddedChannel.close():555
boolean io.netty.channel.embedded.EmbeddedChannel.finish(boolean):503
boolean io.netty.channel.embedded.EmbeddedChannel.finish():483
void io.netty.handler.codec.http.HttpContentEncoder.finishEncode(List):341
boolean io.netty.handler.codec.http.HttpContentEncoder.encodeContent(HttpContent, List):272
void io.netty.handler.codec.http.HttpContentEncoder.encodeFullResponse(HttpResponse, HttpContent, List):227
void io.netty.handler.codec.http.HttpContentEncoder.encode(ChannelHandlerContext, HttpObject, List):189
void io.netty.handler.codec.http.HttpContentEncoder.encode(ChannelHandlerContext, Object, List):56
void io.netty.handler.codec.MessageToMessageCodec$1.encode(ChannelHandlerContext, Object, List):67
void io.netty.handler.codec.MessageToMessageEncoder.write(ChannelHandlerContext, Object, ChannelPromise):89
void io.netty.handler.codec.MessageToMessageCodec.write(ChannelHandlerContext, Object, ChannelPromise):116
void io.vertx.core.http.impl.HttpChunkContentCompressor.write(ChannelHandlerContext, Object, ChannelPromise):38
void io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Object, ChannelPromise):717
void io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Object, ChannelPromise):709
void io.netty.channel.AbstractChannelHandlerContext.write(Object, boolean, ChannelPromise):792
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.write(Object, ChannelPromise):702
void io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChannelHandlerContext):303
void io.netty.handler.stream.ChunkedWriteHandler.flush(ChannelHandlerContext):132
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush0():750
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush():742
ChannelHandlerContext io.netty.channel.AbstractChannelHandlerContext.flush():728
void io.netty.channel.ChannelDuplexHandler.flush(ChannelHandlerContext):127
void io.netty.channel.AbstractChannelHandlerContext.invokeFlush0():750
void io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Object, ChannelPromise):765
void io.netty.channel.AbstractChannelHandlerContext.write(Object, boolean, ChannelPromise):790
ChannelFuture io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Object, ChannelPromise):758
void io.vertx.core.net.impl.ConnectionBase.write(Object, Boolean, ChannelPromise):178
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, boolean, ChannelPromise):230
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, ChannelPromise):215
void io.vertx.core.net.impl.ConnectionBase.writeToChannel(Object, FutureListener):211
void io.vertx.core.http.impl.Http1xServerResponse.end(Buffer, PromiseInternal):407
Future io.vertx.core.http.impl.Http1xServerResponse.end(Buffer):382
