### ISSUE TITLE
transport-native-epoll 4.1.79-Final does not include OSGI processor directive fix

### ISSUE THREAD

**Issue by jcallin** [netty/netty#12646]
### Expected behavior
https://mvnrepository.com/artifact/io.netty/netty-transport-native-epoll/4.1.79.Final contains an artifact

https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.79.Final/netty-transport-native-epoll-4.1.79.Final-linux-aarch64.jar

As fixed in https://github.com/netty/netty/pull/12498

### Actual behavior
https://mvnrepository.com/artifact/io.netty/netty-transport-native-epoll/4.1.79.Final contains an artifact

https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.79.Final/netty-transport-native-epoll-4.1.79.Final-linux-aarch_64.jar (Note the `_` included between `aarch` and `64`)

### Steps to reproduce
Examine artifacts at https://mvnrepository.com/artifact/io.netty/netty-transport-native-epoll/4.1.79.Final

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1.79-Final

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

**Comment by chrisvest** [comment]
The processor directive is correct in the `MANIFEST.MF`. Isn't that what matters?

**Comment by jcallin** [comment]
I guess I don't fully understand what is happening under the hood, but shouldn't something like the following be added like was added in `netty-tcnative`? https://github.com/netty/netty-tcnative/pull/733/commits/97e1e0e66f5b2ae640dbc8c622bc1fd02a8a94ac

```
                <!-- In OSGi specification, the alias of x86_32 is x86... -->
                <condition property="nativeCode.processor" value="x86">
                  <equals arg1="${os.detected.arch}" arg2="x86_32" />
                </condition>
                <!-- ... and aarch_64 is aarch64 -->
                <condition property="nativeCode.processor" value="aarch64" else="${os.detected.arch}">
                  <equals arg1="${os.detected.arch}" arg2="aarch_64" />
                </condition>
```

Again, I don't really know how this works, but the resolver (Coursier) on my system is trying to resolve https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.79.Final/netty-transport-native-epoll-4.1.79.Final-linux-aarch64.jar and it cannot be found. However, if I add an `_` between `aarch` and `64` I can manually find the jar... this might not be a problem with this project I figured I would double check since I'd been following the `tc-native `fix. `tc-native` 2.0.54-Final actually also has an artifact with an `_` published so maybe that is not the problem...

**Comment by chrisvest** [comment]
Maybe raise the issue with the OSGi project, because we don't really have the expertise in Netty to tell what part is wrong.

**Comment by gspadotto** [comment]
As far as OSGi is concerned, [this line](https://github.com/netty/netty/blob/netty-4.1.79.Final/transport-native-epoll/pom.xml#L342) is correct and that's all that's required for dependency resolution at runtime in an OSGi container, regardless of the name of the containing jar file. 

I don't know Coursier and how it resolves what it has to resolve, but it seems that [here](https://github.com/netty/netty/blob/netty-4.1.79.Final/transport-native-epoll/pom.xml#L349) is where you state what the jar **file name** will be, whilst [here](https://github.com/netty/netty/blob/netty-4.1.79.Final/transport-native-epoll/pom.xml#L222-L223) is where you define the values for the aarch64 maven properties.

So my suggestion is: study which info Coursier relies on in order to look up files while "resolving".
