### ISSUE TITLE
Netty5 artifacts for MacOS have wrong natives libraries names

### ISSUE THREAD

**Issue by violetagg** [netty/netty#12861]
`netty5-resolver-dns-native-macos-5.0.0.Alpha5-osx-x86_64.jar`
Has a wrong native library name - `libnetty_resolver_dns_native_macos_x86_64.jnilib`
- It should be `netty5` not `netty`

`netty5-transport-native-kqueue-5.0.0.Alpha5-osx-x86_64.jar`
Has a wrong native library name - `libnetty_transport_native_kqueue_aarch_64.jnilib`
- It should be `netty5` not `netty`
- The classifier should be `x86_64` not `aarch_64`

I think that the issue is the newly introduced maven profile `mac-m1-cross-compile`

### Expected behavior
Native libraries are found

### Actual behavior
Native libraries cannot be found

### Netty version
5.0.0.Alpha5

**Comment by normanmaurer** [comment]
Will checkAm 03.10.2022 um 21:41 schrieb Violeta Georgieva ***@***.***>:﻿
netty5-resolver-dns-native-macos-5.0.0.Alpha5-osx-x86_64.jar
Has a wrong native library name - libnetty_resolver_dns_native_macos_x86_64.jnilib

It should be netty5 not netty

netty5-transport-native-kqueue-5.0.0.Alpha5-osx-x86_64.jar
Has a wrong native library name - libnetty_transport_native_kqueue_aarch_64.jnilib

It should be netty5 not netty
The classifier should be x86_64 not aarch_64

I think that the issue is the newly introduced maven profile mac-m1-cross-compile
Expected behavior
Native libraries are found
Actual behavior
Native libraries cannot be found
Netty version
5.0.0.Alpha5
