### ISSUE TITLE
New HTTP header validation rules introduce backward compatibility issues

### ISSUE THREAD

**Issue by valfirst** [netty/netty#13005]
Should the same validation rules be applied for both HTTP/1 and HTTP/2? This change introduces backward compatibility issues:

_Originally posted by @valfirst in https://github.com/netty/netty/pull/12760#discussion_r1024140480_

**Comment by chrisvest** [comment]
Header validation being too relaxed has been a liability on a few occasions. Those tests are trying to add invalid header values, and since the correct default approach for a low-level library like Netty is to follow the standards closely, you get validation errors. Stripping out invalid header value characters is something you can do on a higher level, or in a `DefaultHttpHeaders` subclass, so you are not locked in, but it's how Netty should behave by default.
