### ISSUE TITLE
IndexOutOfBoundsException when upgrading from 4.1.87 to 4.1.88

### ISSUE THREAD

**Issue by slandelle** [netty/netty#13213]
Hey there,

We're experiencing test failures when our CI tries to automatically upgrade from 4.1.87 to 4.1.88. I can reproduce locally.

One of the broken test is https://github.com/gatling/gatling/blob/main/gatling-http-client/src/test/java/io/gatling/http/client/BasicHttpTest.java#L261-L289.

I can work on a pure netty reproducer, unless this immediately rings a bell for you guys :)

Java version: 1.8.0_342
OS: irrelevant, happens both on Linux and MacOS.

Cheers

```
[error] Caused by: java.lang.IndexOutOfBoundsException: index: -2147483630, length: 2147483647 (expected: range(0, 2048))
[error]     at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
[error]     at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
[error]     at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
[error]     at io.netty.buffer.ByteBufUtil.lastIndexOf(ByteBufUtil.java:718)
[error]     at io.netty.buffer.AbstractByteBuf.indexOf(AbstractByteBuf.java:1254)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:1022)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:633)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:284)
[error]     at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[error]     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[error]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[error]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[error]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[error]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[error]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[error]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[error]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[error]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by normanmaurer** [comment]
Doesn’t ring a bell :( Am 13.02.2023 um 09:17 schrieb Stephane Landelle ***@***.***>:﻿
Hey there,
We're experiencing test failures when our CI tries to automatically upgrade from 4.1.87 to 4.1.88. I can reproduce locally.
One of the broken test is https://github.com/gatling/gatling/blob/main/gatling-http-client/src/test/java/io/gatling/http/client/BasicHttpTest.java#L261-L289.
I can work on a pure netty reproducer, unless this immediately rings a bell for you guys :)
Cheers
[error] Caused by: java.lang.IndexOutOfBoundsException: index: -2147483630, length: 2147483647 (expected: range(0, 2048))
[error]     at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
[error]     at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
[error]     at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
[error]     at io.netty.buffer.ByteBufUtil.lastIndexOf(ByteBufUtil.java:718)
[error]     at io.netty.buffer.AbstractByteBuf.indexOf(AbstractByteBuf.java:1254)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:1022)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:633)
[error]     at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:284)
[error]     at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[error]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[error]     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[error]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[error]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[error]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[error]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[error]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[error]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[error]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[error]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[error]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[error]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by franz1981** [comment]
@slandelle  although we didn't have failures on the vertx CI, I see an `indexOf` popping up there -> are you using the snapshot of netty right? 
In case, it could be due to https://github.com/netty/netty/pull/12321

**Comment by slandelle** [comment]
> Are you using the snapshot build of Netty right?

Hey @franz1981 
Thanks for chiming in.
No, I'm using the [4.1.88.Final that was released yesterday](https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.88.Final/). We use scala-steward to automatically create PRs with library updates.

> In case, it could be due to https://github.com/netty/netty/pull/12321

This PR is shipped in stable 4.1.88.Final :)

**Comment by slandelle** [comment]
@franz1981 Do you want me to revert this commit locally and check if tests pass again? Do you want me to build a pure netty test?

**Comment by franz1981** [comment]
@slandelle 

Re 
> Do you want me to revert this commit locally

that would be great, to double check if it's something other (I don't think so, but better be safe)

The pure netty test would be the best in case you cannot do the former, please

**Comment by normanmaurer** [comment]
@franz1981 wanted to write the release news today... release was done yesterday while recovering from jet lag :/

**Comment by slandelle** [comment]
@franz1981 I confirm that reverting #12321 fixes the issue.

**Comment by franz1981** [comment]
@normanmaurer 
> .. release was done yesterday while recovering from jet lag :/

take care bud!!!

**Comment by slandelle** [comment]
@franz1981 Please let me know if you want me to try a patch.

**Comment by normanmaurer** [comment]
@slandelle @franz1981 IMHO we should revert this commit and do another release asap. We can look into the fix then and buy us some time. WDYT ?

**Comment by normanmaurer** [comment]
@slandelle please do

**Comment by franz1981** [comment]
@slandelle if you have a netty reproducer will speedit up a lot (I'm not very familiar with Scala but it seems a fairly simple test, I'm surprised we're not covered on this, nor on vertx o netty)

The faulty code is likely on https://github.com/netty/netty/issues/13213#issuecomment-1427607489 
and it's likely a missing `size` reset somewhere

**Comment by slandelle** [comment]
@franz1981 My current test suite uses Netty for the client but Jetty as the server so that I get more chances to uncover bugs with different stacks. Before trying to build a pure netty test, I think we should identify the kind of payload that causes this issue. I'm going to add logs on my side.

**Comment by slandelle** [comment]
Here's the response payload that causes the decoder to crash (client side):

```
11:42:45.566 [DEBUG] i.n.h.l.LoggingHandler - [id: 0x6f931cd0, L:/127.0.0.1:59258 - R:localhost/127.0.0.1:59255] READ: 273B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 44 61 74 65 3a 20 4d 6f 6e 2c 20 31 33 20 46 |.Date: Mon, 13 F|
|00000020| 65 62 20 32 30 32 33 20 31 30 3a 34 32 3a 34 35 |eb 2023 10:42:45|
|00000030| 20 47 4d 54 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 | GMT..Content-Ty|
|00000040| 70 65 3a 20 74 65 78 74 2f 68 74 6d 6c 3b 63 68 |pe: text/html;ch|
|00000050| 61 72 73 65 74 3d 75 74 66 2d 38 0d 0a 58 2d 43 |arset=utf-8..X-C|
|00000060| 6c 69 65 6e 74 50 6f 72 74 3a 20 35 39 32 35 38 |lientPort: 59258|
|00000070| 0d 0a 58 2d 50 61 74 68 49 6e 66 6f 3a 20 2f 66 |..X-PathInfo: /f|
|00000080| 6f 6f 2f 62 61 72 0d 0a 58 2d 41 63 63 65 70 74 |oo/bar..X-Accept|
|00000090| 3a 20 2a 2f 2a 0d 0a 58 2d 48 6f 73 74 3a 20 6c |: */*..X-Host: l|
|000000a0| 6f 63 61 6c 68 6f 73 74 3a 35 39 32 35 35 0d 0a |ocalhost:59255..|
|000000b0| 58 2d 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 |X-Content-Length|
|000000c0| 3a 20 33 0d 0a 54 72 61 6e 73 66 65 72 2d 45 6e |: 3..Transfer-En|
|000000d0| 63 6f 64 69 6e 67 3a 20 63 68 75 6e 6b 65 64 0d |coding: chunked.|
|000000e0| 0a 53 65 72 76 65 72 3a 20 4a 65 74 74 79 28 39 |.Server: Jetty(9|
|000000f0| 2e 34 2e 35 30 2e 76 32 30 32 32 31 32 30 31 29 |.4.50.v20221201)|
|00000100| 0d 0a 0d 0a 33 0d 0a 66 6f 6f 0d 0a 30 0d 0a 0d |....3..foo..0...|
|00000110| 0a                                              |.               |
+--------+-------------------------------------------------+----------------+
```

**Comment by normanmaurer** [comment]
Reverted via 9993e07356ea39edf14008789d3377d2bb62ea92. Lets investigate in parallel while I do an "emergency" release

**Comment by franz1981** [comment]
Well done @normanmaurer thanks

**Comment by slandelle** [comment]
@franz1981 The issue happens because I set `maxHeaderSize` to `Integer.MAX_VALUE` when creating the `HttpClientCodec`. You can reproduce in `HttpClientCodecTest` if you change the parameter.

**Comment by franz1981** [comment]
Oki @slandelle so this is indeed a missing test on us I can tell

**Comment by franz1981** [comment]
It's surprising it was working before given that we check ++size < max somewhere wow

**Comment by franz1981** [comment]
@slandelle 
So the max header size value is the only way to trigger it, I can send a fix very soon and if you tell is the CI is green, we are free I think, @normanmaurer ?
I am still finishing lunch 😃

**Comment by normanmaurer** [comment]
@franz1981 so you think I should wait with the release ?

**Comment by violetagg** [comment]
I can run Reactor Netty although I do not see the issue that @slandelle reported.

**Comment by slandelle** [comment]
> I would leverage the @slandelle test suite if he agree, is currently covering few cases we won't cover (and I include VertX as well)

I can build and test any branch you wish.

>  using such larger header max size, will probably blow up the client/server much earlier, but still...is a good test.

Basically, we're lifting a security limit. When we used to enable it, we had to deal with "how do I fix this?" and "but why?! it works fine with curl!". So well, Gatling is a test tool, we gave up on teaching people on a different concern.

Then, I do have another concern here.
When testing with `HttpClientCodecTest`, I realized that when `failOnMissingResponse` is enabled (default), decoding failure actual causes get swallowed and the user visible error is a `io.netty.handler.codec.PrematureChannelClosureException: channel gone inactive with 1 missing response(s)` triggered in `channelInactive`.
Not sure this is the desired behavior.

**Comment by slandelle** [comment]
Note: failure happens when `maxHeaderSize` is `Integer.MAX_VALUE` or `Integer.MAX_VALUE - 1` but not when it's `Integer.MAX_VALUE - 2` 🤷 That's a funny one.

**Comment by slandelle** [comment]
I reckon I might be the only person disabling this limit, sorry for this 😂

**Comment by franz1981** [comment]
@slandelle https://github.com/franz1981/netty/tree/4.1_fix_max_int_head_size

thanks god you have done it dear, I've added the test and I bet there are others that should be add!

**Comment by slandelle** [comment]
@franz1981 Just tested your fix. All good!

**Comment by franz1981** [comment]
Nice! so it pass your test suite for other tests too @slandelle ? just to be safer

**Comment by slandelle** [comment]
Yes, our whole test suite passes.

**Comment by franz1981** [comment]
Awesome news and sorry again for the bug, next time I'll run your test suite in case.
Just a qq, can you join quickly on Discord's netty channels? got few questions for you related performance (that could be beneficial by Gatlin as Netty users)

**Comment by slandelle** [comment]
> Just a qq, can you join quickly on Discord's netty channels?

Sure. I wasn't aware of this Discord server. What's the name? Is it public? I can't find it in Discord's search engine.

**Comment by franz1981** [comment]
I've mentioned there, name is https://discord.gg/KA8T3bWd

**Comment by slandelle** [comment]
@franz1981 Connected. I see your messages but can't reply yet :)

<img width="447" alt="Screenshot 2023-02-13 at 14 44 04" src="https://user-images.githubusercontent.com/849197/218474137-a8226de3-06ac-40e0-b63f-762587a41d0e.png">

**Comment by hyperxpro** [comment]
> @franz1981 Connected. I see your messages but can't reply yet :)
> 
> <img alt="Screenshot 2023-02-13 at 14 44 04" width="447" src="https://user-images.githubusercontent.com/849197/218474137-a8226de3-06ac-40e0-b63f-762587a41d0e.png">

Sorry, I enforced those limits on Discord to prevent guerrilla marketing spam. 😅
