### ISSUE TITLE
No next available bitmap index found 

### ISSUE THREAD

**Issue by wangjing112** [netty/netty#13461]
### Expected behavior
no exception
### Actual behavior
throw this exception
### Steps to reproduce
unknow

### Minimal yet complete reproducer code (or URL to code)
java.lang.AssertionError: No next available bitmap index found (bitmapIdx = -1), even though there are supposed to be (numAvail = 1) out of (maxNumElems = 32) available indexes.
	at io.netty.buffer.PoolSubpage.allocate(PoolSubpage.java:95)
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:169)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
### Netty version
4.1.82
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)
centos7
Linux raid-us-prod-outside01 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@chrisvest can you have a look ?

**Comment by chrisvest** [comment]
I've looked at this before, but not been able to crack it so far.
If @laosijikaichele or @jchrys have ideas, I'd be happy to hear them.

**Comment by jchrys** [comment]
I appreciate being included in this discussion.

Based on my preliminary investigation,
If someone intentionally or inadvertently manages to trigger a double-free situation, 
the described state can potentially be reproduced by following these steps:

```
Step1. When the bitmap is fully utilized:
bitmap: [1,1,1,1,1,1,1,1] numAvail=0, maxNumElem=8, nextAvail=-1

Step2. Free the bitmap index: 0
bitmap: [0,1,1,1,1,1,1,1] numAvail=1, maxNumElem=8, nextAvail=0

Step3. Free the bitmap index: 0 again (double-free)
bitmap: [1,1,1,1,1,1,1,1] numAvail=2, maxNumElem=8, nextAvail=0

Step4. Attempt to allocate (in this step, it will use the cached value from the nextAvail member variable, 
which will bypassing the allocation status of bitmap[0])
bitmap: [1,1,1,1,1,1,1,1] numAvail=1, maxNumElem=8, nextAvail=-1

Step6. Attempt to allocate again (in this step, it will iterate through bitmap, 
but will throw an error since there's no available slot & this PoolSubpage will be removed)
bitmap: [1,1,1,1,1,1,1,1] numAvail=1, maxNumElem=8, nextAvail=-1
```

**Comment by laosijikaichele** [comment]
Thanks for the detailed steps from @jchrys , I reproduce the error with following code:
```
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PoolArenaMetric;
import io.netty.buffer.PoolSubpageMetric;
import io.netty.buffer.PooledByteBufAllocator;

public class TestCapacity {

    public static void main(String[] args) throws InterruptedException {

        for(int i =0; i< 31; i++) {
            PooledByteBufAllocator.DEFAULT.heapBuffer();
        }

        final ByteBuf buf = PooledByteBufAllocator.DEFAULT.heapBuffer( );
        final int ENLARGE_CAPACITY = 512;
        Thread thread_1 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });
        Thread thread_2 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });

        thread_1.start();
        thread_2.start();

        thread_1.join();
        thread_2.join();

        PoolArenaMetric metric = PooledByteBufAllocator.DEFAULT.metric().heapArenas().get(0);

        PooledByteBufAllocator.DEFAULT.heapBuffer();
        PooledByteBufAllocator.DEFAULT.heapBuffer();

    }
}

```
Run the main method above, there is a good chance to reproduce the error(If not, just re-run it).

The reason is because the method `ByteBuf.capacity(int newCapacity)` is not thread-safe, which is designed to be so.

But IMHO, the `ByteBuf.capacity(int newCapacity)` is also a kind of 'alloc' operation, and I think it may be also should be thread-safe, just like the allocation method. Refer https://github.com/netty/netty/issues/8079#issuecomment-401259398

**Comment by normanmaurer** [comment]
Thanks… will have a look tomorrow Am 08.07.2023 um 16:44 schrieb old driver ***@***.***>:﻿
Thanks for the detailed steps from @jchrys , I reproduce the error with following code:
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PoolArenaMetric;
import io.netty.buffer.PoolSubpageMetric;
import io.netty.buffer.PooledByteBufAllocator;

public class TestCapacity {

    public static void main(String[] args) throws InterruptedException {

        for(int i =0; i< 31; i++) {
            PooledByteBufAllocator.DEFAULT.heapBuffer();
        }

        final ByteBuf buf = PooledByteBufAllocator.DEFAULT.heapBuffer( );
        final int ENLARGE_CAPACITY = 512;
        Thread thread_1 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });
        Thread thread_2 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });

        thread_1.start();
        thread_2.start();

        thread_1.join();
        thread_2.join();

        PoolArenaMetric metric = PooledByteBufAllocator.DEFAULT.metric().heapArenas().get(0);

        PooledByteBufAllocator.DEFAULT.heapBuffer();
        PooledByteBufAllocator.DEFAULT.heapBuffer();

    }
}


Run the main method above, there is a good chance to reproduce the error(If not, just re-run it).
The reason is because the method ByteBuf.capacity(int newCapacity) is not thread-safe, which is designed to be so.
But IMHO, the ByteBuf.capacity(int newCapacity) is also a kind of 'alloc' operation, and I think it may be also should be thread-safe, just like the allocation method. Refer #8079 (comment)
