### ISSUE TITLE
Netty seemingly inactive since 2015 on mvnrepository.com

### ISSUE THREAD

**Issue by veita** [netty/netty#13489]
On [mvnrepository.com](https://mvnrepository.com/search?q=netty) the last releases of Netty artifacts (group `io.netty`) seem to be from 2012 and 2015.

This comes from alpha versions published in Maven Central back then (e.g. https://repo1.maven.org/maven2/io/netty/netty-all/).

It maybe could be fixed by setting the `latest` and `release` elements in the Maven metadata accordingly.

https://repo1.maven.org/maven2/io/netty/netty-all/maven-metadata.xml

**Comment by hyperxpro** [comment]
Sounds good, would you like to do a PR?

**Comment by sh-cho** [comment]
I just wonder, is it possible to modify 'latest', 'release' elements in `maven-metadata.xml` of maven central repository?

**Comment by jprante** [comment]
Either the obsolete 5.0.0.Alpha1 and 5.0.0.Alpha2 are removed from Maven Central (maybe Sonatype can help?) or Netty is moving to 5.0.0+ and releasing new jars to Maven Central which will override the status quo.

Netty main branch is at 5.0.0.Alpha6-SNAPSHOT so I am hoping the latter will soon happen.

**Comment by chrisvest** [comment]
Netty 5 (the new effort, not the obsolete 2015 one) has a `netty5-` prefix in all its artefact ids, so 5 and 4.1 can co-exist in projects and on the classpath. That's why those old artefacts are not replaced in the search results by the newer ones.

Removing artefacts from Maven Central is something that's almost never done, and certainly not for reasons like this.
