### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by guozhongdong** [netty/netty#13554]
### Expected behavior
memory leak 
my code uses Netty to handle message listening logic. After running for approximately 2 months, the memory usage rate exceeds 90%.
![image](https://github.com/netty/netty/assets/16163847/b4024fbc-d4e9-4c15-b796-464d8d83daf4)

![image](https://github.com/netty/netty/assets/16163847/62281d63-bf77-41e3-bb97-f1cbd4e0b07d)

From the graph, it can be seen that **PoolThreadCache** is ultimately referenced by **FinaLizer**. I suspect that there might be an issue with the finalize() method, but I'm not sure how to resolve it specifically.

### Netty version
4.1.70.Final

### JVM version (e.g. `java -version`)
jdk1.8.0_191
-Xms5120 -Xmx 5120

**Comment by chrisvest** [comment]
Yeah, try upgrading to 4.1.96.Final so you get https://github.com/netty/netty/pull/13510

It might help.

I suspect you are creating and throwing away many threads, or you are creating and throwing away many PooledByteBufAllocators, since there's at most one PoolThreadCache per pooled allocator, per thread.

You should also look into reusing your resources better.

**Comment by normanmaurer** [comment]
Closing for now
