### ISSUE TITLE
Is Netty 5.x Alpha releases official releases?

### ISSUE THREAD

**Issue by edmundham** [netty/netty#13668]
Hi Netty team, 

This is just a general question so I removed all the pre-defined issue template.

Are Netty 5.x releases final releases? I'm a little confused due to the naming of the releases e.g. `5.0.0.Alpha5`. Are they still in testing, i.e. not official releases? I believe they are just because you have all the migration guide and such, but I wanted to make sure.

Also, Is Netty 5.x in active development? Just wanted to check as it seems Netty 5.x doesn't have frequent releases compared to Netty 4.1.x releases.

Thanks in advance!

**Comment by normanmaurer** [comment]
no there's are not final... These are alpha releases and so have no API guarantees etc. And yes both, 5 and 4 are in active development atm

**Comment by edmundham** [comment]
Hi @normanmaurer Thanks for your reply.

Do you know when can we expect 5.x final releases?

**Comment by normanmaurer** [comment]
Unfortunately I dont know.

**Comment by TaylorSMarks** [comment]
@normanmaurer - There's a CVE for all Netty 4 versions. It looks like this was fixed in Netty 5 over five years ago.

CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-4586
Fix: https://github.com/netty/netty/issues/8537

I don't think it's viable to suggest people wait an indefinite number of additional years for this security fix to be released.
