### ISSUE TITLE
PR #13381 is incompatible with RHEL8 openjdk with FIPS enabled

### ISSUE THREAD

**Issue by brian-dellisanti-hcl** [netty/netty#13840]
### Expected behavior
A server SslContext is successfully constructed by SslContextBuilder.

### Actual behavior
Initialization of the SSLContext fails with an exception:
```
Exception in thread "main" javax.net.ssl.SSLException: failed to initialize the server-side SSL context
	at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:299)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:251)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:472)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:610)
	at bdd.FIPSBug.main(FIPSBug.java:25)
Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
	at java.base/sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)
	at java.base/sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:95)
	at java.base/javax.net.ssl.SSLContext.init(SSLContext.java:297)
	at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:283)
	... 4 more
```
The change in PR #13381 wraps the JVMs trust managers with its own to supply better diagnostics, but this is rejected by the JVM. In FIPS mode, OpenJDK will only accept its own X509TrustManagerImpl class.

### Steps to reproduce

Configure RHEL 8 to run in FIPS mode: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening

Create an a server SslContext with SslContextBuilder supplying null for the trust manager factory.

### Minimal yet complete reproducer code (or URL to code)
```
package bdd;

import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManagerFactory;

import io.netty.handler.ssl.SslContextBuilder;

public class FIPSBug {
    public static void main(String[] args)
    throws Exception {
        KeyStore ks = KeyStore.getInstance("JKS");
        ks.load(Files.newInputStream(Path.of("keystore.jks")), "changeit".toCharArray());
        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(ks, "changeit".toCharArray());

        if (!Boolean.getBoolean("nonetty")) {
            SslContextBuilder
                .forServer(kmf)
                .trustManager((TrustManagerFactory) null)
                .build();
        }
        else {
            SSLContext ctx = SSLContext.getInstance("TLS");
            ctx.init(kmf.getKeyManagers(), null, null);
        }

        System.out.println("OK");
    }
}
```

### Netty version
4.1.95+ (PR #13381)
Tested with 4.1.100

### JVM version (e.g. `java -version`)
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux ip-10-134-119-133.ec2.internal 4.18.0-477.13.1.el8_8.x86_64 #1 SMP Thu May 18 10:27:05 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@brian-dellisanti-hcl I suspect we could try in a static block first if we can use it and if not fail back to the non-wrapping one.

**Comment by normanmaurer** [comment]
@brian-dellisanti-hcl PTAL https://github.com/netty/netty/pull/13842

**Comment by brian-dellisanti-hcl** [comment]
@normanmaurer Code looks reasonable to me. If there's a way to get the jars out of the PR, I can try them in my environment, but I don't see how to do that.

**Comment by normanmaurer** [comment]
@brian-dellisanti-hcl you would need to build it yourself. I can provide you with a netty-handler jar tho if this is good enough. Let me know

**Comment by brian-dellisanti-hcl** [comment]
@normanmaurer OK, I ran a local build and it got far enough to get the jars I need to test. Looks good!

**Comment by vkpo** [comment]
But in my case this static block solutions is not helping me to get out of this issue.  It is working fine while initializing JDK ssl context inside static block as it is not wrapped with EnhancedTrustManager initially due to that wrapTrustManager boolean value is being set to True. 

In the Next call to "newSSLContext" function while initializing the JDK ssl context it is getting failed as it is getting converted to EnhancedTrustManager  object. Anyone suggest the solutions to unblock from here

**Comment by normanmaurer** [comment]
@vkpo can you please show the stack trace ?

**Comment by vkpo** [comment]
> @vkpo can you please show the stack trace ?


Error while reloading certs j.s.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
s.s.s.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:132)\n\tat s.s.s.SSLContextImpl.engineInit(SSLContextImpl.java:94)
j.n.s.SSLContext.init(SSLContext.java:297)
i.n.h.s.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:334)\n\t... 10 common frames omitted
Wrapped by: j.n.s.SSLException: failed to initialize the server-side SSL context
i.n.h.s.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:350)
i.n.h.s.JdkSslServerContext.<init>(JdkSslServerContext.java:302)
i.n.h.s.SslContext.newServerContextInternal(SslContext.java:472)
i.n.h.s.SslContextBuilder.build(SslContextBuilder.java:610)
c.o.p.v.n.ReloadSslContextProvider.reloadSslContext(ReloadSslContextProvider.java:99)
j.u.c.Executors$RunnableAdapter.call(Executors.java:515)
j.u.c.FutureTask.runAndReset(FutureTask.java:305)
j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
j.l.Thread.run(Thread.java:834)

**Comment by normanmaurer** [comment]
@vkpo hmm ... this makes no sense to me. it should only wrap it if `WRAP_TRUST_MANAGER` is false which should be the case here.

**Comment by vkpo** [comment]
> if `WRAP_TRUST_MANAGER`

When the  JdkSslServerContext class loaded for the first time, it will execute the static block with WRAP_TRUST_MANAGER  set to false. Due to that TrustManagers are not getting converted to EnhancingX509ExtendedTrustManager and in FIPS mode I am not getting errors with [chooseTrustManager](https://github.com/openjdk/jdk/blob/jdk8b01/jdk/src/share/classes/sun/security/ssl/SSLContextImpl.java#L119) function. But once it is successfully executed in stack block, WRAP_TRUST_MANAGER  is being set to true. 

After the above step, when i am initializing the Netty SSLContext using Netty SslContextBuilder class in my code i am facing issues inside  [newSSLContext function](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java#L334) which is in the same [JdkSslServerContext class](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java) where it initializing the JDK SSL context again in line number [334](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java#L334)

I might be interpreting it wrong, kindly help me to understand what exactly this [checkIfWrappingTrustManagerIsSupported](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java#L77C17-L77C55) is doing here. As this is getting passed through without any exceptions in my case, due to that WRAP_TRUST_MANAGER is being set to true  but later i am  facing the errors with Netty SslContextBuilder when initializing the SSLContext

**Comment by slandelle** [comment]
`WRAP_TRUST_MANAGER` is a final boolean , so it's not possible that its value changes after initialization under normal operation.

I see 2 possibilities:
1. your analysis is wrong and `WRAP_TRUST_MANAGER` doesn't change value
2. something is tempering it, eg with reflection. In this case, this tempering would happen outside netty's official code. You have to investigate your own code or your FIPS JVM from Red Hat.

**Comment by vkpo** [comment]
> `WRAP_TRUST_MANAGER` is a final boolean , so it's not possible that its value changes after initialization under normal operation.
> 
> I see 2 possibilities:
> 
> 1. your analysis is wrong and `WRAP_TRUST_MANAGER` doesn't change value
> 2. something is tempering it, eg with reflection. In this case, this tempering would happen outside netty's official code. You have to investigate your own code or your FIPS JVM from Red Hat.

@slandelle 

1. [wrapTrustManager ](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java#L66C17-L66C33) local variable value is used for initializing  WRAP_TRUST_MANAGER final boolean if no exceptions are thrown inside [checkIfWrappingTrustManagerIsSupported](https://github.com/netty/netty/blob/netty-4.1.108.Final/handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java#L77C17-L77C55) it will be set to true otherwise false
2. No i am not tempering in my code

**Comment by normanmaurer** [comment]
@vkpo if `WRAP_TRUST_MANAGER` is once set to false it will never wrap it so this makes no sense
