### ISSUE TITLE
Support thread affinity in native transport

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#2381]
We could support thread affinity in the native transport to minimize jitter. Alternative there is https://github.com/OpenHFT/Java-Thread-Affinity

**Comment by maseev** [comment]
Why not just adding information about thread affinity and [Java-Thread-Affinity](https://github.com/OpenHFT/Java-Thread-Affinity) library to the Netty's documentation? This particular library works just perfectly out of the box and can be easily integrated with Netty:

```java
final int acceptorThreads = 1;
final int workerThreads = 10;
EventLoopGroup acceptorGroup = new NioEventLoopGroup(acceptorThreads);
ThreadFactory threadFactory = new AffinityThreadFactory("atf_wrk", AffinityStrategies.DIFFERENT_CORE);
EventLoopGroup workerGroup = new NioEventLoopGroup(workerThreads, threadFactory);

ServerBootstrap serverBootstrap = new ServerBootstrap().group(acceptorGroup, workerGroup);
```

It supports plenty of, so called, [affinity strategies](https://github.com/OpenHFT/Java-Thread-Affinity/blob/master/affinity/src/main/java/net/openhft/affinity/AffinityStrategies.java) which can be combined in order to fit for every imaginable use case.

**Comment by trustin** [comment]
It switched to LGPLv3 some time ago. We'd better get the AL2 version and shade it.

**Comment by maseev** [comment]
@trustin FYI [Java-Thread-Affinity](https://github.com/OpenHFT/Java-Thread-Affinity) is [now licensed](https://github.com/OpenHFT/Java-Thread-Affinity/blob/master/LICENSE) under Apache 2.0.

**Comment by maseev** [comment]
Do you mind if I submit a PR?

**Comment by normanmaurer** [comment]
@maseev @trustin actually I am not sure why we even need to share it at all... Why we not just let users know that they can use it ? I mean there is no gain in shading it IMHO.

**Comment by johnou** [comment]
@maseev iirc you are free to edit the Wiki directly https://github.com/netty/netty/wiki

**Comment by maseev** [comment]
[Here](https://github.com/netty/netty/wiki/Thread-Affinity), have a look.

**Comment by maseev** [comment]
Can we close it now?

**Comment by caoli5288** [comment]
I try this library with netty-4.1.9 but all threads in eventloopgroup locked on the same core. Any one got expected behavior?

**Comment by maseev** [comment]
How did you determine that all threads are locked on the same CPU core?

**Comment by caoli5288** [comment]
@maseev See this screenshot. ![](https://cloud.githubusercontent.com/assets/3120587/25790054/588da402-33e8-11e7-96c3-143af455976e.png)

**Comment by maseev** [comment]
What version of the java-thread-affinity library are you using?

**Comment by caoli5288** [comment]
@maseev maven's newest version 3.0.6

**Comment by caoli5288** [comment]
@maseev Do you have any idea?

**Comment by maseev** [comment]
@caoli5288 Here's a simple [project](https://github.com/maseev/echo) that can help you with your problem, I suppose.
That's how it looks like starting a server with 2 worker threads and connect two clients:

![selection_002](https://cloud.githubusercontent.com/assets/3434800/25806725/60ebe8e8-342e-11e7-9d71-2d3cf20b33a9.png)
![selection_001](https://cloud.githubusercontent.com/assets/3434800/25806724/60e01cf2-342e-11e7-96fe-c0281a1c1afc.png)

But you'll still get context switching (your worker threads will jump from core to core) unless you isolate you CPU cores from the OS scheduler.

**Comment by caoli5288** [comment]
@maseev Yes. I have read this http://netty.io/wiki/thread-affinity.html. My code like
```java
ThreadFactory threadFactory = new AffinityThreadFactory("netty-io", AffinityStrategies.DIFFERENT_CORE);
EventLoopGroup group = new NioEventLoopGroup(8, threadFactory);
```
![qq 20170508231451](https://cloud.githubusercontent.com/assets/3120587/25810949/37705be6-3444-11e7-9f90-fecb18baa905.png)

But all threads use same core. :/

**Comment by maseev** [comment]
@caoli5288 Try to build and run this echo project I mentioned earlier. I bet you'll be able to use more than 1 CPU core. Otherwise, it's kinda difficult to say why your application is using only one core without a minimal reproducer. Did you isolate your CPU cores by any chance?

**Comment by caoli5288** [comment]
@maseev It's [BungeeCord](https://github.com/SpigotMC/BungeeCord). I try to add thread-affinity to this project and got this issue.

**Comment by maseev** [comment]
@caoli5288 Well, again, it's hard to say what went wrong without looking at your code. It would be also great to have a look at the `isolcpus` parameter in your `grub.conf' file. 

I have no trouble whatsoever running this code on my laptop or on the server machine. It would be great to have a minimal reproducer of your problem. You can also point to your version of BungeeCord where you implemented a thread affinity feature. This might help solve your issue.

**Comment by caoli5288** [comment]
@maseev No `isolcpus` set yet and newest bungeecord git version I used. You are a minecraft player? :-?
I extends the `ThreadFactory` and let it log which cpu the thread assigning to. then log shown threads assigning diff cpus but server load still under a same cpu core. What?

**Comment by maseev** [comment]
> No isolcpus set yet and newest bungeecord git version I used

Alright. So, this is not a misconfiguration problem in the `isolcpus` section, I suppose.

> You are a minecraft player?

No, I'm not, unfortunately.

> I extends the ThreadFactory and let it log which cpu the thread assigning to. then log shown threads assigning diff cpus but server load still under a same cpu core. What?

I think it would be better if you could upload your version of this project with the affinity feature implemented and tell us how to build and test it. 
Otherwise, it's kinda difficult to guess what's actually going on.

**Comment by caoli5288** [comment]
@maseev https://github.com/caoli5288/bungee/ It is a minecraft server clust proxy so you need setup some minecraft server to test it. :/

**Comment by caoli5288** [comment]
@maseev I see you just let worker group under thread-affinity but I use a mixed group. is this the reason?

**Comment by caoli5288** [comment]
@maseev Use ·AffinityThreadFactory· in only worker group got balanced cpu usage. Once it is applied to the boss group, cpu load will focus on the first boss thread. Puzzling.

**Comment by maseev** [comment]
@caoli5288 

> I see you just let worker group under thread-affinity but I use a mixed group. is this the reason?

No, I don't think so. I've just checked it and it works as expected. When you use a single event loop group instance it just means that you'll be sharing threads from this group for accepting new connections and handling already connected clients. 

In my case, when I use only one event loop group, I can only bind a single worker thread to the CPU core because I have only two physical cores on my laptop and `java-thread-affinity` library uses physical cores for binding threads and it doesn't look at virtual cores (Intel Hyper-Threading technology, for example), if I'm not mistaken.

You can try to write a simple Java application which would start a bunch of threads and bind them to the `free` CPU cores via `AffinityThreadFactory`. 

Just to make sure the problem is in the `java-thread-affinity` library itself and not in Netty.

**Comment by normanmaurer** [comment]
This can be closed now. See https://github.com/netty/netty/wiki/Thread-Affinity
