### ISSUE TITLE
Problem with ChunkedFile in HttpStaticFileServerHandler

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#2474]
I made some tests with the example HttpStaticFileServer.
I download a file but I cancel the download on client side before completion. So only some bytes are transferred. I see different results for DefaultFileRegion (useSendFile = true) and ChunkedFile (useSendFile = false).

With ChunkedFile I don't see an exception that the connection was closed by client.
But DefaultFileRegion throws such a message.

I am testing with Windows 7.
Please send the 1337 USD bug bounty to my bank account :D

**Comment by jwboardman** [comment]
I also noticed that HttpStaticFileServer wasn't setting the transfer encoding to chunked in the case of SSL, so I added that to mine just before the initial ctx.write(response) like this:

```java
if (ctx.pipeline().get(SslHandler.class) != null) {
    HttpHeaders.setTransferEncodingChunked(response);
}
```

Unfortunately it didn't fix the issue, but it does seem to me that this should be there.

**Comment by lukehutch** [comment]
The full recipe you need is pretty complex, because HttpChunkedInput writes a LastHttpContent but DefaultFileRegion doesn't. This is what I have currently:

    RandomAccessFile fileToServe = null;
    try {
        // Create new RandomAccessFile (which allows us to find file length etc.)
        long lastModifiedEpochSeconds = theFile.lastModified() / 1000;
        fileToServe = new RandomAccessFile(theFile, "r");

        DefaultHttpResponse httpRes = new DefaultHttpResponse(HttpVersion.HTTP_1_1,
                HttpResponseStatus.OK);
        HttpHeaders headers = httpRes.headers();
        // ... [Add HTTP headers here -- ommitted for brevity] ...
        ctx.write(httpRes);

        // For HEAD requests, don't send the body
        if (request.isHEADRequest()) {
            ctx.writeAndFlush(LastHttpContent.EMPTY_LAST_CONTENT);
            fileToServe.close();
            return;
        }

        ChannelFuture lastContentFuture;
        if (ctx.pipeline().get(SslHandler.class) == null) {
            // Use FileRegions if possible, which supports zero-copy / MMIO
            ctx.write(new DefaultFileRegion(fileToServe.getChannel(), 0, fileLength),
                    ctx.newProgressivePromise());
            // Write the end marker
            lastContentFuture = ctx.writeAndFlush(LastHttpContent.EMPTY_LAST_CONTENT);
        } else {
            // Can't use FileRegions / zero-copy with SSL
            // N.B. HttpChunkedInput will write the end marker (LastHttpContent) for us, see:
            // https://github.com/netty/netty/commit/4ba2ce3cbbc55391520cfc98a7d4227630fbf978
            lastContentFuture = ctx.write(new HttpChunkedInput(
                    new ChunkedFile(fileToServe, 0, fileLength, 1)),
                    ctx.newProgressivePromise());
        }

        // Close the file and possibly the connection after the last chunk has been sent. We
        // can't close the file in a finally block, because the file writing is asynchronous,
        // and the file shouldn't be closed until the last chunk has been written. 
        final RandomAccessFile fileToClose = fileToServe;
        lastContentFuture.addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture future) {
                try {
                    fileToClose.close();
                } catch (IOException e) {
                }
                future.channel().flush();
                if (!request.isKeepAlive()) {
                    future.channel().close();
                }
            }
        });

    } catch (Exception e) {
        if (fileToServe != null) {
            try {
                fileToServe.close();
            } catch (IOException e1) {
            }
        }
        throw new InternalServerErrorException(request, "Exception serving static file", e);
    }

**Comment by Scottmitch** [comment]
@WhiteTrashLord @lukehutch - Thanks for the details!

@normanmaurer - would you mind taking a closer look?

**Comment by lukehutch** [comment]
You're welcome. You can see my complete working HTTP server here, in case it's helpful: https://github.com/lukehutch/gribbit/blob/master/src/gribbit/request/handler/HttpRequestHandler.java

**Comment by jwboardman** [comment]
Super helpful, thank you so much for sharing!

**Comment by lukehutch** [comment]
@jwboardman : Good catch, I'm not sure of the answer to that, and don't have the time to test it right now, but I would love to hear the answer to that question. I updated my code to set the header, thanks for pointing it out. It's probable if you set Content-Length but don't sent Transfer-Encoding (which is what I was doing), then you'll get corrupted content, because there will be a "\r\n" inserted between chunks.

**Comment by lukehutch** [comment]
PS when I say "my complete working HTTP server", actually, based on @jwboardman's comment, I'm guessing my code is actually still not working in the case of file sending, pending having this bug fixed. (i.e. don't look to my code to try to figure out why file sending is not working for you, since I hit the same problem, and Norman hasn't commented yet).

**Comment by jwboardman** [comment]
@lukehutch no problem, I'm glad I was able to help since you've helped so much with your code!

**Comment by bobwenx** [comment]
the `DefaultFileRegion` and `ChunkedWriteHandler/HttpChunkedInput` will close `RandomAccessFile` automatically.

**Comment by welarson** [comment]
@lukehutch Looking at your code real quick, shouldn't the write for HttpChunkedInput be a writeAndFlush?

    lastContentFuture = ctx.write(new HttpChunkedInput(
                new ChunkedFile(fileToServe, 0, fileLength, 1)),
                ctx.newProgressivePromise());

That could prevent the fire from being sent. That was a bug in the HttpStaticFileServer example that has been fixed recently.

**Comment by normanmaurer** [comment]
@welarson you are right... writeAndFlush is needed.

**Comment by lukehutch** [comment]
@welarson @normanmaurer thanks, my code was based on the old (buggy) version of HttpStaticFileServer. I believe this will solve the issue for me at least. One question though: I assumed that adding a ChannelFutureListener that calls future.channel().flush() was the right way to flush the channel asynchronously, but this bug was triggered because the ChannelFutureListener is not even invoked until the write operation has completed. But is flush() a non-blocking call? The docs don't specify whether it is blocking or nonblocking, but all POSIX-like filesystem flush operations are by convention blocking calls, so it would be good to document the non-blocking nature of Netty's flush() and writeAndFlush() methods, if flush() is indeed nonblocking.

@bobwenx Thanks for the tip that there's no need to add another listener to close the file.
