### ISSUE TITLE
ChannelFuture sync method throws undeclared checked exceptions

### ISSUE THREAD

**Issue by slominskir** [netty/netty#2597]
From a usability and maintenance point of view I think throwing undeclared checked exceptions is a mistake.  I believe the sync method should be deprecated.  I spent a few minutes scratching my head trying to figure out how this could possibly be happening until I found this document explaining what was going on:

https://www.securecoding.cert.org/confluence/display/java/ERR06-J.+Do+not+throw+undeclared+checked+exceptions

This certainly breaks the "do the least surprising" thing rule of API design.

One of the side effects of this is you cannot for example catch a java.net.ConnectException directly since the compiler will say that it is never thrown.

**Comment by yeroc** [comment]
Is this change not being considered at all even for Netty 5?  I don't see any change made to the Javadoc. I agree with others that this is extremely bad practice for Java API.

**Comment by drtimwright** [comment]
It would be really good if the Netty API declares all the checked exceptions that are thrown. Throwing undeclared checked exceptions is considered very bad practice. And, probably like many other people here, I've just wasted several hours trying to figure out WTF was happening.

**Comment by Lewik** [comment]
Now I know about Unsafe class. Thx a lot.
You know, it's not a bad idea to make Netty 4` or Netty 4-1 or smth like that with out ninja-execeptions-that-suddenly-thrown-from-nowhere at all. For example - even with BC I'd spent several hours for refactor code for that.

Or may be you can wrapped it with real stacktrace or link to here

**Comment by trustin** [comment]
The thing is changing the behavior of `sync()` is going to introduce another set of surprises to an existing user because their code will stop to compile as soon as `sync()` has a throws clause. We might want to add a `throws` clause to `sync()` or find a better way to solve this issue, but there's nothing much we can do but documenting this behavior until we release a new major version.

**Comment by drtimwright** [comment]
Personally, I would happily have my code stop compiling due to this change.  Easy to fix my code :)

Tim
Sent from phone. 




On Wed, Feb 17, 2016 at 1:42 AM -0800, "Trustin Lee" <notifications@github.com> wrote:












The thing is changing the behavior of sync() is going to introduce another set of surprises to an existing user because their code will stop to compile as soon as sync() has a throws clause. We might want to add a throws clause to sync() or find a better way to solve this issue, but there's nothing much we can do but documenting this behavior until we release a new major version.

**Comment by trustin** [comment]
Alternatively, we could deprecate `sync*()` and add replacement methods that throws a `RuntimeExecutionException` which is similar to `ExecutionException` but is a `RuntimeException` in 4.1. I guess we need a good name for the new method.

BTW, you can always use `get()` instead of `sync()` which throws `ExecutionException`.

@normanmaurer @Scottmitch @nmittler Thoughts?

**Comment by Scottmitch** [comment]
@trustin - Although not ideal API can't be changed.  As you indicate `get()` can be used and I'm not convinced adding another method is justified in this case.

Another option is just to document `sync` that it can throw a `Throwable` (or `Exception`).

**Comment by trustin** [comment]
@Scottmitch I'm with you. Just wondering what the community really wants..

**Comment by tomaszszlek** [comment]
Hi, In my opinion at least declare "throws Exception" for sync signature will work for me as it adds significant information to API. If you can add it in some major release it would be nice.
