### ISSUE TITLE
Channel.isWritable() does not work when SslHandler is used

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#2752]
`SslHandler` queues pending writes until the user call `flush()` , because of this nothing is passed through to the `ChannelOutboundBuffer`. This means the pendingOutboundBytes are not updated and so `Channel.isWritable()` will not change. This is bad as it means that the user has no way to know if he/she uses to much memory.

There are two ways to fix it:
 1) Make `ChannelOutboundBuffer.increase/decreaseOutboundBytes(...)` public and trigger it in `SslHandler`
 2) Add a "proper" `PendingWritesQueue` to the `io.netty.channel` package and use this in `SslHandler`. This way we could keep the method package private.

I kind of prefer 2) as it would also allow a user to re-use it without care too much about implementation details.

@trustin wdyt ?

**Comment by smaldini** [comment]
@Scottmitch @normanmaurer it does seem a regression has been introduced recently and defeat this fix due to SslHandler now using CoalescingBufferQueue from this commit https://github.com/netty/netty/commit/86e653e04fb452c92154e39cd7189615dc0ec323. 
As a result, backpressured based flush flow using isWriteable are broken and streams are getting aggregated forever until manual flush. Since there is no public api around this queue, its also impossible to track down externally. What should be done there ?
