### ISSUE TITLE
Logging direction of the connection

### ISSUE THREAD

**Issue by IgorAlelekov** [netty/netty#2944]
Netty 4.0.21 channel's method toString() incorrect outputs direction of the connection:
[id: 0x9f79a8ce, /172.16.2.216:45678 => /172.16.1.10:49839]. Here 45678 is the server port.
It can confuse users in log files analysis. Is it possible to change direction of the arrow for server side connections?

**Comment by jiafu1115** [comment]
@normanmaurer @trustin I think we don't need to express the directions due to we can't make sure the directions, even we know, if we only want to print the channel info instead to express the directions. the direction will confuse us again.

so I fix it by； https://github.com/netty/netty/pull/4782
<->  <!>
or  <=> <:> what's better?

**Comment by trustin** [comment]
@jiafu1115 Thanks! Left a comment in the PR.

**Comment by IgorAlelekov** [comment]
@jiafu1115 @normanmaurer @trustin 
Certainly, you should know who is the server and who is the client and print it in the channel info
This info might be usefull in log files analysis in multi channel environment

**Comment by jiafu1115** [comment]
when one app server use netty as server and client . swap the address may help to provide more infos. so what about just keep swap logical. such as if local address is first address.it is client connection.if it is second.it is client connection. so what about just add < before the => and keep the swap logical.

**Comment by trustin** [comment]
@IgorAlelekov Let's continue the discussion from [here](https://github.com/netty/netty/pull/4782#issuecomment-177782683)
