### ISSUE TITLE
using MaxAge in DefaultCookie generates an invalid cookie string

### ISSUE THREAD

**Issue by elad-yosifon** [netty/netty#3355]
according to RFC6265,
http://tools.ietf.org/search/rfc6265#section-4.1.2.2,
http://tools.ietf.org/search/rfc6265#section-5.2.2 

**MaxAge cookie should only contain digits**

#### How to reproduce:
```java 
DefaultCookie cookie = new DefaultCookie("key", "value");
cookie.setMaxAge(10);
System.out.println(cookie.toString());
```
#### expected result:
```
key=value, maxAge=10
```

#### actual result:
```
key=value, maxAge=10s
```

**Comment by slandelle** [comment]
No. You're supposed to use CookieEncoder to encode a Cookie, not toString.
RFC6265 support has just made it in master and 4.1 branches.

**Comment by elad-yosifon** [comment]
@slandelle if that's the case the toString() method should throw a RuntimeException instead of returning an invalid output.

I've fixed it just for being on the safe side of things. 
I discovered this issue after using it that way on production... :worried:

**Comment by slandelle** [comment]
First, check [toString's javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#toString()) and you'll realize it's very generic. It doesn't provide any contract for building logic upon and should only be used for logging.

Then, it's impossible to have one single method for encoding cookies as it depends on the side you are: server or client. Check RFC6265 again and you'll see that clients must only send the name-value pairs.

**Comment by elad-yosifon** [comment]
I get what you are saying..  but the fact is that toString() was overridden with a server side implementation.. which is invalid.

**Comment by slandelle** [comment]
No, it was overridden to display the object's internal state instead of just the hashcode. It just happens to be similar, as it's quite standard to display attributes as `key`=`value` pairs.

For example, it lack the `Expires` attribute of the server side encoded form, as it's not part of the state, but computed from maxAge.

Do you see anything in DefaultCookie#toString() javadoc that would make one think that it could be used as a replacement for ServerCookieEncoder? No, and that's a good thing because it would be very wrong from an API design perspective.

**Comment by trustin** [comment]
It's not a bug. You must use `ServerCookieEncoder` instead.
