### ISSUE TITLE
memcache client library discussion

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3437]
@daschl - I wanted to talk to you a bit about your java memcache client experience.  I see you have contributed the binary protocol to netty 4 about a year ago.  However I also see you have contributed to  other java based clients more recently (https://github.com/couchbase/spymemcached and https://github.com/dustin/java-memcached-client).  My questions are:

1. Are you using Netty's codec-memcache, and if so to what capacity (in production, couchbase)?
2. If you are using codec-memcache can you describe your experience, and if you are not using it...why not (performance, features, stability, political, etc...)?
3. Are you still using spymemcached, and is the couchbase fork the preferred repo?
4. Do you have any metrics comparing spy vs. codec-memcache?

**Comment by daschl** [comment]
Hi @Scottmitch,

alright, first up some clarifications: I'm working for Couchbase where I maintain both the old and new Couchbase JVM SDK. I tell you this because: the "old" uses and extends spymemcached while the new one is built exclusively on netty and uses codec-memcache. 

re 1: We are using codec-memcache in production in the new Couchbase Java SDK (which is currently in version 2.1.0). I've pulled it out of the 4.1 tree since we are using it with 4.0 right now (https://github.com/couchbase/couchbase-jvm-core/tree/master/src/main/java/com/couchbase/client/deps/io/netty/handler/codec/memcache)

re 2: I wrote codec-memcache for the main reason that I wanted to migrate a new SDK completely on top of netty. Since couchbase uses the binary protocol only (and @normanmaurer will agree with me at this point that it is the only sane option ;)) I wanted to contribute it back for greater good. We had no problem running it in production and it works great for us, but keep in mind that we are only using it from a client perspective. There might be bugs in the server-side protocol parts which are not as battle tested.

re 3: Our old SDK (1.4.x right now) is built on top of spymemcached (tried and true) and I'm still maintaining it. Let me know if you need anything related to that (in any case @normanmaurer has my private infos and you can get in touch with me directly if you want). Actually if you check both repos they are the same. Dustin Sallings ("spy") who wrote it in the early days used to work at couchbase for a long time and I ended up maintaining it for 2 years now :). The couchbase one is the canonical one, but we are using gerrit for code review (and github just ends up to be a mirror).

re 4: It's a little unfair comparison because spy is a full client and codec-memcache is just the protocol bits. Both are very efficient. Of course if you want plug and play spy is the way to go, but codec-memcache gives you more flexibility and is the way to go in a netty environment. If you want implementation guidance help I can get you started and you can check out our client parts here: https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/endpoint/kv/KeyValueHandler.java

Now one more final thing: the reason we moved away from spy was neither political nor strictly related to performance. The thing is, we moved away from being a cache to a document oriented database which provides lots of "services" (key value, secondary indexes, views,...). We also have dynamic node scaling which spy was not designed for in the first place. So we had to put more and more hacks in place to make it all fit together nicely and also ended up with more IO endpoints and thread pools that we wanted to.

When we redesigned the SDK we decided to put it onto a central IO foundation, chose netty and now we can run all protocols through it in a efficient fashion. We expose this through a message oriented, async (rxjava) based core layer where we can put language bindings on top. This provides the best of both worlds :)

Let me know if you have more questions!

**Comment by Scottmitch** [comment]
@daschl - Thanks for the very thorough response!  I think I have all the info I need for now.  I will let you know if I have any further questions.
