### ISSUE TITLE
HTTP/2 Data Frame Error Case Handling

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3557]
We should investigate how we behave when we receive a DATA frame and the stream state is not OPEN or HALF CLOSED.  We are currently sending a connection error if we fail to find the stream object [DefaultHttp2ConnectionDecoder.java#L190](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L190) which may not be correct in all situations.  Depending on how the stream was closed (assuming it was closed) we may still have to count this against the connection flow control window.

**Comment by Scottmitch** [comment]
From PR #3516:

@buchgr in reference to [DefaultHttp2ConnectionDecoder.java#L190](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L190):

> @Scottmitch @nmittler I was thinking about using `stream(streamId)` instead of `requireStream(streamId)` here and simply ignore the frame if the stream doesn't exist. My reasoning is that `requireStream(streamId)` raises a connection error and would thus close the whole connection. So e.g. if we receive a data frame for a stream that is already closed & garbage collected we would fail every stream on the connection. IMHO it's much more reasonable to just ignore this frame and continue processing the other streams. WDYT?

@scottmitch:
> @buchgr - I agree the connection error may not be the right thing to do here. [section 6.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.1):

> > If a DATA frame is received whose
   stream is not in "open" or "half closed (local)" state, the recipient
   MUST respond with a stream error (Section 5.4.2) of type
   STREAM_CLOSED.

> We do that [DefaultHttp2ConnectionDecoder.java#L255](https://github.com/buchgr/netty/blob/fix_goaway/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L255) but we have to get the stream first to get here...

> Some things we should watch out for is when is it OK to send a RST_STREAM frame.

> [section 6.4](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.4):

> > RST_STREAM frames MUST NOT be sent for a stream in the "idle" state.

> Also we may want to be careful about sending on streams that *may* have existed...but in this case I think we are OK sending the RST_STREAM [section 5.4.2](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.4.2):

> > Normally, an endpoint SHOULD NOT send more than one RST_STREAM frame
   for any stream.  However, an endpoint MAY send additional RST_STREAM
   frames if it receives frames on a closed stream after more than a
   round-trip time.  This behavior is permitted to deal with misbehaving
   implementations.

@nmittler:

> @Scottmitch @buchgr Hmm ... this is actually a little tricky. [section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1):
> > An endpoint MUST NOT send frames other than PRIORITY on a closed
      stream.  An endpoint that receives any frame other than PRIORITY
      after receiving a RST_STREAM MUST treat that as a stream error
      (Section 5.4.2) of type STREAM_CLOSED.  Similarly, an endpoint
      that receives any frames after receiving a frame with the
      END_STREAM flag set MUST treat that as a connection error
      (Section 5.4.1) of type STREAM_CLOSED, unless the frame is
      permitted as described below.

> So judging by that text, it depends on how the stream was closed as to whether it should be a connection error or a stream error.

> Also WRT flow control (same section):
> > Flow controlled frames (i.e., DATA) received after sending
      RST_STREAM are counted toward the connection flow control window.
      Even though these frames might be ignored, because they are sent
      before the sender receives the RST_STREAM, the sender will
      consider the frames to count against the flow control window.

> So if our endpoint terminated the stream, we still have to apply flow control to any received DATA frames.

**Comment by Scottmitch** [comment]
From @nmittler in https://github.com/netty/netty/pull/3516#discussion_r27603491
> If we are no longer guaranteed that we will maintain stream objects for 5 seconds, should we separately maintain some history of streams that have recently closed and under what conditions?  This history could then be garbage collected in a similar way to what we were doing before.  Something like this perhaps:

> ```java
class StreamHistory {
   enum CloseState {
       CLOSED_NORMALLY,
       RESET_SENT,
       RESET_RECEIVED
   }
   int id;
   long time;
   CloseState closeState;
}
```

> This should be much lighter weight than keeping the entire stream around, and it might help us to make better decisions about what to do about historical streams.  WDYT?

**Comment by Scottmitch** [comment]
@nmittler - I'm reading the spec the same way you are.  I have opened https://github.com/http2/http2-spec/issues/743 to see if perhaps we can get some additional clarity before implementing this historical closure feature.

**Comment by nmittler** [comment]
@Scottmitch sgtm ... thanks!

**Comment by ejona86** [comment]
If we need to maintain old streams: I propose that we keep two IntObjectHashMaps: recentlyClosed and aging. They would map from stream id to @nmittler's CloseState. When an unexpected stream's frame is found we would look in both maps. When a stream is closed it is added to recentlyClosed.

Every time a timer would expire, we would clear aging and then swap recentlyClosed and aging. This prevents us from having to store the time the stream was closed and means the only object allocation is the array within IntObjectHashMap.

It would be left to discussion on whether we should clear() the map or create a new replacement map (because clear is O(n) the size of the hash table).

**Comment by buchgr** [comment]
@ejona86 +1

> It would be left to discussion on whether we should clear() the map or create a new replacement map (because clear is O(n) the size of the hash table).

@ejona86 +1 for clearing it. Even for very big maps the memory usage would only be in the low megabytes.

**Comment by nmittler** [comment]
@ejona86 sgtm

**Comment by nmittler** [comment]
@Scottmitch @buchgr @ejona86 actually in the interest of keeping things simple ...

What if we brought back the `Http2StreamRemovalPolicy` in some fashion? It seems like a cleaner solution in general since there will only ever need to be a single map for the streams ... they all stay there until they're officially removed (say after ~5 seconds of being closed or until they're allowed to be removed from the tree).

IIRC, one of the motivations for doing immediate removal was to avoid keeping the data around but I believe that @buchgr realized that it wasn't that big of a deal WRT memory pressure.

WDYT?

**Comment by Scottmitch** [comment]
@ejona86 @nmittler @buchgr  This sounds like a reasonable approach if we have to keep history.  I'm pushing toward not keeping history though.  This would increase complexity and potentially hurt performance / memory metrics.  Most importantly I'm not sure what additional value keeping the history would provide.  The specification may "technically" require it, but there may be other ways to react if a peer is misbehaving this badly. We may be able to get away with:
1. Always updating the connection flow control window.
2. Responding with an error (stream or connection).
3. Closing the connection...the peer is misbehaving sufficiently bad we may not want to talk to it anymore (seems to be what the http2 spec folks are thinking https://github.com/http2/http2-spec/issues/743#issuecomment-93546306).

Step 2 and 3 I'm still thinking about what would be appropriate....if we need both, if we can get away with a stream error, etc...

WDYT?

**Comment by buchgr** [comment]
> IIRC, one of the motivations for doing immediate removal was to avoid keeping the data around but I believe that @buchgr realized that it wasn't that big of a deal WRT memory pressure.

It's not as a big deal as I initial thought because we had a memory leak :-). It's still a big deal in terms of latency, because it helps keep the heap several times smaller (depending on your app ofc) and thus your GC pauses are a lot shorter (have seen up to 10x on avg GC time).

I don't think keeping additional state around would be a big deal (just not the stream object itself). If we can get away with not keeping state around and can simply ignore everything that's not active and has a stream identifier < highest stream identifier, I would also prefer that.

@Scottmitch regarding your points 2 and 3. Can we maybe get away with ignoring anything the first time and if we receive frames over a period of time (or some fixed) on a closed stream, then we send a RST_STREAM and if that doesn't help then we close the connection? That way we would only have to keep state for misbehaving streams around.

**Comment by nmittler** [comment]
@buchgr I'm not sure that keeping around the `Http2Stream` would necessarily be all that bad.  It won't have any children (and in fact before removal we can swap it's map out for an empty one). The only thing of significance are the properties (it may be possible to further reduce this data after closure as well, on a per-property basis).  Plus we can play around with the garbage collection interval (maybe something smaller like 2 seconds is better?).

If we need history, this seems like the simplest solution WRT code complexity.  But as @Scottmitch said, not having the code require history would be even better if that's possible.

**Comment by buchgr** [comment]
> @buchgr I'm not sure that keeping around the Http2Stream would necessarily be all that bad.

@nmittler As I said above, in our benchmarks we see GC times roughly 10x higher and heaps being 5x bigger with the 5 second policy. 

Doing a top of the envelop calculation tells me that the `DefaultStream` object is roughly 50 bytes in size without the map. Eric's stream history proposal would take 4 bytes per stream (the stream id) with zero allocations as after some start up time the hash maps would remain at some "fixed" size. So that would make the heap a lot smaller.  Furthermore, GC times are mostly driven by the number of surviving objects (it has to copy those). So say we do 20K streams per second on a connection, with the 5 second policy we keep up to 100k stream objects around. With Eric's proposal we keep maybe a few hundred around (whatever the number of concurrent requests is) and we don't have to iterate over all those closed streams every ~5 seconds, we just swap out the map and zero out the memory.

**Comment by nmittler** [comment]
@buchgr yup agreed ... if we need to preserve history that sounds like the best alternative.

@Scottmitch are you currently investigating whether or not we can do this without history? If so, I'll hold off implementing anything until you report back.

**Comment by Scottmitch** [comment]
@nmittler - Yes hold off.  For this issue I don't think we will need it...a misbehaving peer is a misbehaving peer....we may not want to complicate our logic to try to compensate.  Unless there is a legitimate race condition we need to account for, and we can't get by with a simple `streamId < nextStreamId && streamId is a legit peer stream id` lets not do history.

**Comment by nmittler** [comment]
@Scottmitch we've got at least 3 different bugs discussing history ATM :). Just as a point of reference here is some discussion related to a lightweight history: https://github.com/netty/netty/issues/3653#issuecomment-94176994

**Comment by nmittler** [comment]
@Scottmitch now that #3685 is in, can we close this?

**Comment by Scottmitch** [comment]
@nmittler - Yes sir!  Thanks again for the fix!
