### ISSUE TITLE
When using netty for a large file upload, how can I get uploaded size while upload is in progress?

### ISSUE THREAD

**Issue by karuturi** [netty/netty#3636]
I am running the sample code from https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http/upload/HttpUploadServerHandler.java

I would like to get the upload percentage in writeHttpData if the datatype is FileUpload

StackOverflow post: http://stackoverflow.com/questions/29507687/

**Comment by fredericBregier** [comment]
@normanmaurer @trustin @Scottmitch 
Before starting anything, I would like to propose you the general idea:

Motiviations:
Currently, while adding the next buffers to the decoder (`decoder.offer()`), there is no way to access to the current HTTP object being decoded since it can only be available currently once fully decoded by `decoder.hasNext()`.
Some could want to have a '%' of progression on the overall transfer but also per HTTP object.

Modifications (proposal):
1) For HTTP object, each (AbstractHttpData) has 2 protected properties named `definedSize` and `size`, respectively the supposely final size and the current (decoded until now) size.
`definedSize` is potentially not the real size in particular for FileUpload due to the encoding size (for instance 7bit) and the real final size (8bit). I have no particular idea on how to managed this (any idea?) in order to be alway "exact".

However, we could at least provide a method `definedSize()` to get the current value for `definedSize`. The `size` attribute is reachable by the `length()`method.

Note however there are 2 different ways that currently managed the `definedSize`:
a) Attribute: it is reset each time the value is less than actual (when a buffer is added, the value is increased) since the final length is not known (no `Content-Length`)
b) FileUpload: it is set at startup from the lengh provided (but shall be the encoded size)

So these differences could lead in wrong perception;
a) Attribute: `definedSize` = `size` always
b) FileUpload: `definedSize` >= `size` always (and probably always > )

Therefore we should be clear in the comment of the method `definedSize()` of its behavior.

2) In the `InterfaceHttpPostRequestDecoder` (and the derived classes), we could add a new method: `decoder.currentDecodingHttpData()` which will return a HttpData (if any) as the current `Attribute` or `FileUpload` (the 2 generic types), which will allow then the programmer to check according to the real type (`instance of`) the 2 methods  `definedSize()` and `length()`.

This method will check if `currentFileUpload` or `currentAttribute` are null and returns the one (only one could be not null) that is not null.

Note that if this method returns null, it might mean 2 situations:
a) the last `HttpData` (whatever attribute or file upload) is already finished and therefore accessible through `next()`
b) there is not yet any `HttpData` in decoding (body not yet parsed for instance)


Result (proposal):
The coding from developper side could looks like (from HttpUloadServerHandler):

    private void readHttpDataChunkByChunk() {
        try {
            while (decoder.hasNext()) {
                HttpData data = decoder.next();
                if (data != null) {
                    // Start of ADDITION for information of last decoding status
                    if (httpData instance of FileUpload) {
                          long currentSize = httpData.length();
                          // do something with it, as setting to 100% the status for this file
                          // in order to fix the 7bit vs 8bit size issue
                    }
                    // End of ADDITION
                    try {
                        // new value
                        writeHttpData(data);
                    } finally {
                        data.release();
                    }
                }
            }
            // Start of ADDITION for information of partial decoding
            HttpData httpData = decoder.currentDecodingHttpData();
            if (httpData != null && httpData instance of FileUpload) {
                long predictiveSize = httpData.definedSize();
                long currentSize = httpData.length();
                // do something with it as currentSize/predictiveSize in %
            }
            // End of ADDITION
        } catch (EndOfDataDecoderException e1) {
            // end
            responseContent.append("\r\n\r\nEND OF CONTENT CHUNK BY CHUNK\r\n\r\n");
        }
    }

**Comment by fredericBregier** [comment]
@karuturi Just to note that the fix was not pushed to 4.0 and 3.X since it would have add some public methods, therefore impacting the interface by additions, which is not allowed for those releases (stability of interfaces).

**Comment by karuturi** [comment]
Thanks a lot @fredericBregier for fixing this and driving it to completion.
Will upgrade to 4.1 when its released.
