### ISSUE TITLE
DefaultHttp2RemoteFlowController should observe Channel.isWritable

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3783]
HTTP/2 flow control is useful for the remote to indicate how much memory they are willing to spend on a connection or stream. It is not a good indicator of how much memory the local side is willing to spend or how much is necessary to spend. In many cases the ideal flow control window would be the size of the bandwidth-delay project and _neither_ side would need to buffer, as the data packets are "buffered" within the network itself. There are also legitimate cases where the flow control window could be 2^31 - 1.

The flow controller primarily limits the amount it writes to the Channel by the remote connection flow control window. However, it should also limit its writes by Channel.isWritable(). This would enable normal high and low watermark writing and would prevent potentially large amounts of data to be queued. Over-queuing increases the latency of other potentially-more-important frames, such as WINDOW_UPDATEs, RST_STREAM, SETTINGS, PING, and GOAWAY. It would also delay the effect of received PRIORITY, RST_STREAM, and GOAWAY frames.

**Comment by Scottmitch** [comment]
@ejona86 - Agreed this should be done at some level. I need to think if it makes sense to put directly in the flow controller or have it at a higher level. I think for most protocols this mechanism and auto_read are done outside the codec.  Let me think...and thanks for bringing this up!

[channelWritabilityChanged](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/ChannelHandler.java#L237) is also useful in this context.

**Comment by ejona86** [comment]
@Scottmitch, I don't see a good way to do it except in the flow controller. If we receive a WINDOW_UPDATE of 1 GB, then only the flow controller is consulted...

Other codecs don't have flow control and don't have multiplexing, so it seems hard to learn what is most appropriate.

**Comment by ejona86** [comment]
For more info about the issue, I came across an article about [the need for TCP_NOTSENT_LOWAT](https://insouciant.org/tech/prioritization-only-works-when-theres-pending-data-to-prioritize/) and the importance of disassociating the network flow control window from the buffering necessary to get performance for a protocol like HTTP/2. It is basically the identical problem I am concerned with here, but at a different layer in the stack.

**Comment by Scottmitch** [comment]
@ejona86 - Sorry I've been busy lately.

How do you use auto_read? I'm wondering if auto_read should be turned off (if it is on) temporarily if the channel is not writeable.  No sense in reading data to do more stuff, until the peer is ready to receive some data.

**Comment by ejona86** [comment]
auto_read _must_ be on for the connection. This is [explicitly stated in the HTTP/2 spec](https://httpwg.github.io/specs/rfc7540.html#rfc.section.5.2.2.p.4). Basically, without reading there is no way to get `WINDOW_UPDATE`s and other control messages, which results in deadlock.

**Comment by Scottmitch** [comment]
@ejona86 - Good point.  However this leaves us vulnerable to resource exhaustion.  A peer could send an infinite amount of data and not read anything (or read much slower than writing).  I think we need to account for situations where peer consumption/production rates are different such that we don't allow for resource exhaustion.

The situation we would be accounting for with toggling auto_read is when the TCP socket is not writeable. In this case reading a `WINDOW_UPDATE` frame would not have much impact because we cannot write anything anyways (lower protocol layer is "stuck").

I'm not sure how realistic the risk of deadlock is here because once the other side acknowledges a sufficient amount of TCP packets we will then start reading again.  I think we are in a slightly different situation than the section of the specification you referenced.  In our situation we are not trying to be "smart" and estimate how much/often we are reading based upon projections of bandwidth delay product, but instead we are in the situation where part of the transport is known to be saturated.  So while it is important to read in a timely manner, the timeliness seems to be relative to each peer's ability to consume/produce data.

**Comment by ejona86** [comment]
> A peer could send an infinite amount of data

The only way you can push back is via HTTP/2's flow control. If you ignore it, then yes, you can run out of memory, but that would be true with plain TCP as well.

>  and not read anything (or read much slower than writing).

They would actually have to read, in order to get the WINDOW_UPDATES. They could just assume they will have enough window, but if they ever exceed the window then the connection will be killed.

> The situation we would be accounting for with toggling auto_read is when the TCP socket is not writeable.

That still deadlocks. If both sides buffered 1M worth outgoing data then both would end up stopping reading and neither queue could drain.

The only real solution here is "push back with HTTP/2 flow control."

**Comment by Scottmitch** [comment]
@ejona86 - Agreed.  HTTP/2 flow control should be sufficient to prevent deadlock and resource exhaustion.  I'll pull together a PR.

**Comment by Scottmitch** [comment]
I have a PR pending for this....

**Comment by Scottmitch** [comment]
@ejona86 - See PR #3864.

I think this approach will be sufficient for flow controlled frames.  However we are still vulnerable to resource exhaustion for non flow controlled frames.  I think we can handle this in a followup PR though.  Let me know if you agree with this or if you don't think it is an issue.

**Comment by Scottmitch** [comment]
Took a while but PR #3864 should resolve this.

**Comment by nmittler** [comment]
Yay! :)
