### ISSUE TITLE
Netty 3.9.3: 100% CPU usage under windows

### ISSUE THREAD

**Issue by spinscale** [netty/netty#3857]
Hey,

I have one system (not reproducible so far), that got stuck with 100% CPU usage without doing anything. What got stuck was a `ClientBootstrap`. This is a `hot_threads` output of elasticsearch

```
::: [node01][node01][node01][inet[/AAA.BBB.CCC.DDD:9300]]{data=false, master=true}

   131.3% (656.2ms out of 500ms) cpu usage by thread 'elasticsearch[node01][transport_client_worker][T#4]{New I/O worker #4}'
     10/10 snapshots sharing following 16 elements
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
       sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:415)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   128.1% (640.6ms out of 500ms) cpu usage by thread 'elasticsearch[node01][transport_client_worker][T#16]{New I/O worker #16}'
     10/10 snapshots sharing following 16 elements
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
       sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:415)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   90.6% (453.1ms out of 500ms) cpu usage by thread 'elasticsearch[node01][transport_client_worker][T#5]{New I/O worker #5}'
     10/10 snapshots sharing following 16 elements
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
       sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
       sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:415)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

Dont wonder about the `org.elasticsearch.common.netty` package prefix, this is just netty being shaded.

I dont think this is an epoll issue, but I found this JDK bug at http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6778476 - however the JDK being used is `1.8.0_25` - I also found a couple of long fixed JDK bugs...

I wont be able to provide more information unfortunately, so feel free to close this due to lack of further information. Maybe you have experienced something like this already and can point me to a direction.

Thanks!

**Comment by spinscale** [comment]
This issue looks similar but has been marked as fixed https://github.com/netty/netty/issues/302

**Comment by normanmaurer** [comment]
@spinscale this can not be an epoll issue as epoll is only used on linux ;) That said I have no idea what this is about :/

**Comment by normanmaurer** [comment]
@spinscale the jdk bug kind of looks promising.. Unfortunately I have no windows at all and so it may be hard to reproduce here

**Comment by virtman** [comment]
Had same issues by some users on Windows(2012 etc) as server with Java 8.0.45 and  -Dorg.jboss.netty.epollBugWorkaround=true definetively fixes issue because it stops to happen, I do not think it is contingent probability, but seems to be the Java issue. More over when bug happens, it affects not only Netty, but any Java NIO based implementation even when the Java programs are running in separate Java processes, so issue is system wide.

**Comment by spinscale** [comment]
@normanmaurer @virtman how can changing the epoll setting have any effect if this is only supposed to work under Linux? Does the epoll workaround do more than its name claims?

**Comment by virtman** [comment]
@pinscale 
When I got this problem for first time reported (i use Netty heavily in my project), I got access to this problematic WINDOWS server, I have than created many dumps and have analyzed them.
Than I have noticed the issue happens inside NIO select function, where Netty waits for selector until being available, but on some Windows systems in rare cases happening sporadically Java did not block it even if it should when there was no connection to select, so selector runned in loop by stealing all CPU time driving it to 100%..
So I looked in Netty sources and noticed the code, that is not enabled by default, but has to be activated with -Dorg.jboss.netty.epollBugWorkaround=true
This code notices when selector has run in loops to fast without selecting valid connection and resets the selector.
And this activation of -Dorg.jboss.netty.epollBugWorkaround=true
helped me to work around the issues with selector.
The code does not check, if Java machine runs under Linux, Mac or Windows, it just get's activated by -Dorg.jboss.netty.epollBugWorkaround=true
You are highly deceived by "epoll" definition without understanding, that this bug happens not only on Linux, but on Windows too, but may be initiated by other cause than on Linux.
But to not reinvent the wheel I call this problem epollbug, since workaround helps there ;-)
The biggest problem is, this issue happens, even if you have two parallel running Java machines that reuse NIO selectors, even when these are two different NIO frameworks like Netty and Apache MINA.
That means, when you run one instance
1. java.exe ....netty.jar yourprojectnio
2. java.exe ...mina-core.jar othernioproject
than even being two different processes they get same selector bug at SAME TIME.
This leads me to assumption, the bug happens somewhere in Windows drivers/stack/whatever.. 
May be it is cleanly Java bug, but in such case I wonder, why it happens with two different processes at same time, so best assumption, the bug is much deeper.
Anyway by Netty -Dorg.jboss.netty.epollBugWorkaround=true the bug does not anymore cause sleepless support nights ;-)

**Comment by spinscale** [comment]
@virtman thx so much for taking the time to write up this explanation, owing you are beer for that one. Very helpful! I'll test and report back.

**Comment by AlexSylka** [comment]
looks like i have the same bug. I am using java 8. Don't know if it's related somehow to jdk defects. 
<img width="1440" alt="screen shot 2016-03-21 at 11 40 16 pm" src="https://cloud.githubusercontent.com/assets/1628459/13936048/a8d69988-efc3-11e5-98ba-85bfc4fb2033.png">

**Comment by spinscale** [comment]
closing for now, as we are on netty 4 in master now

**Comment by ratcashdev** [comment]
I think I am running into this with `java-11-openjdk-11.0.6.10-1.el7_7.x86_64` and `Linux  3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
the CPU utilization is howevering around 50% with an idle server, and the stack trace shows for all `nioEventLoopGroup` threads this:
```
"nioEventLoopGroup-1-3" - Thread t@20
   java.lang.Thread.State: RUNNABLE
        at java.base@11.0.6/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.6/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.6/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        - locked <342094a> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <7d39bb68> (a sun.nio.ch.EPollSelectorImpl)
        at java.base@11.0.6/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:807)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

   Locked ownable synchronizers:
        - None

```
