### ISSUE TITLE
OpenSslEngine is public, but Jdk*SslEngine is package-private

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3895]
Is there a reason for the different visibility between the SslEngine implementations? I couldn't find usages of OpenSslEngine within Netty outside of io.netty.handler.ssl. Was this on purpose, or accidental?

**Comment by Scottmitch** [comment]
Here is a related PR for the JDK stuff https://github.com/netty/netty/pull/2966. Names previously used to include `Jetty`.  Scope of classes was keep package private because there was no need to expose them.  `OpenSslEngine` appears to have been `public` from its inception https://github.com/netty/netty/commit/a72230061df5ebee2d1a9f595c9f9ae5ee9868fc.

Do you have a need to extend the engines?

**Comment by normanmaurer** [comment]
It's by purpose to expose some Openssl specific stuff

**Comment by normanmaurer** [comment]
@ejona86 I will close for now... Please re-open if you think there is an issue :)
