### ISSUE TITLE
Review PooledByteBufAllocator in respect of jemalloc 4.x changes

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3910]
There are some interesting changes in jemalloc. We should review our PooledByteBufAllocator and see if we can incorporate some stuff as it was written with jemalloc 3 in mind.

See also:
https://www.youtube.com/watch?v=RcWp5vwGlYU
https://github.com/jemalloc/jemalloc/blob/dev/ChangeLog
https://github.com/jemalloc/jemalloc/milestones/4.0.0

**Comment by normanmaurer** [comment]
@trustin FYI as you write the initial impl :)

**Comment by normanmaurer** [comment]
@Scottmitch also FYI :)

**Comment by Scottmitch** [comment]
@normanmaurer - Thanks for reporting.

**Comment by ywengineer** [comment]
I found another malloc (tcmalloc) from google similar to jemalloc. it includes some useful tools (heap checker and heap profiler) as well. safari and chrome using tcmalloc.

**Comment by normanmaurer** [comment]
I will try to god this over the next weeks :)

**Comment by bwzhang2011** [comment]
@normanmaurer, take a look at https://github.com/jemalloc/jemalloc/releases/tag/4.1.0, what about netty plan change according to new jemalloc version

**Comment by DATuan91** [comment]
As jemalloc release version 5, can you take a look and review netty's implementation.
[](https://github.com/jemalloc/jemalloc/releases)

**Comment by yuanrw** [comment]
Hi, I have some ideas. There are some inspirations from  jemalloc 4.
1. Split chunk into runs which are multiple of page size rather than power of 2 of page size. It can greatly reduce internal fragments. Use pairing heaps to manage runs (each heap manage the same size of runs), so that we always get a run with smaller id first to avoid dispersedly using runs.
2. Make cache size in PooledThreadCache dynamic. Change cache size according to previous usage of cache. It can improve cache utilization rate.
Do you think it worth a try? I’d love to contribute it :) @normanmaurer @trustin @Scottmitch

**Comment by normanmaurer** [comment]
@yuanrw would love to review a PR :)

**Comment by yuanrw** [comment]
- [ ] Add more size classes. Update Chunk structure. Update PooledByteBufAllocator.
- [ ] Introduce low water for PoolThreadCache, make cache size dynamic.
- [ ] Add more performance tests, includes multi-threaded/single-threaded benchmark, memory usage benchmark.
