### ISSUE TITLE
Java 9 and sun.misc.Unsafe

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#4044]
I just read that Oracle wants to change the access of sun.misc.Unsafe in Java 9.
When you want to use it, you must set a new flag for the JVM.

What does this mean for Netty? Will you try to get rid of all Unsafe usages?
I don't think that I will have any problems to set this flag in the future.

**Comment by buchgr** [comment]
Java 9 is more than a year out and it adds VarHandles which will be able to make up for Unsafe usage in Netty http://openjdk.java.net/jeps/193

**Comment by normanmaurer** [comment]
@buchgr must disagree VarHandles will not be able to act as full Unsafe replacement ;) But we will see ...

**Comment by buchgr** [comment]
@normanmaurer You are right. It doesn't replace every bit of functionality of `Unsafe`, but what I was trying to say is that I think it can replace Netty's usage of Unsafe.

AFAIK the most important and critical use of Unsafe in Netty is the allocator? With var handle you can still get off heap access to a direct byte buffer, so that should be fine.

Obviously you know Netty a lot better than me. Do you know of a place where Netty currently uses Unsafe, that can't be replaced by var handle?

**Comment by Scottmitch** [comment]
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2015-August/004433.html

Looks like current proposal for Unsafe and Cleaner is to keep them around for java9.

**Comment by normanmaurer** [comment]
Yeah Unsafe will stick around in Java9 and we have a job that runs our test suite on java9. So closing this
