### ISSUE TITLE
PooledDuplicatedByteBuf instances are not always recycled

### ISSUE THREAD

**Issue by merlimat** [netty/netty#4066]
PooledDuplicatedByteBuf and PooledSlicedByteBuf are instantiated from a Recycler object when when `duplicate()` or `slice()` methods are called on a pooled buffer. 
However theses objects are only recycled if the call to `release()` them is triggering the wrapped buffer to deallocate, otherwise the objects will be GCed together with the DefaultHandle instances allocated to track them.

Eg: 
```java
ByteBuf b = PooledByteBufAllocator.DEFAULT.buffer(100);
b.retain();
ByteBuf dup = b.duplicate(); // Duplicate allocated from recycler
dup.release();  // duplicated releases but no recycled
b.release();  // Return buffer to pool and recycle pooled buffer
```

Is there any way that this could be improved? 
Could it make sense to recycle the duplicated buffer in the release() method, even though that doesn't trigger a deallocation? I know that in my specific case I could make sure to just not touch the dup buffer after calling release(), but would this be true in general?

**Comment by Scottmitch** [comment]
I guess one of the issues is the `PooledDuplicatedByteBuf` and `PooledSlicedByteBuf` share a reference count with the wrapped buffer. Because this is the case we can not be sure when a release call to a duplicated or sliced buffer is made that is safe to recycle the object (what if retain is called on the dup)? We could add an additional reference count in `AbstractDerivedByteBuf` to know when it is OK to recycle. This seems reasonable to me...just as with any `ByteBuf` people should not be using the duplicate/slice after their respective reference counts are depleted...the debate is the `slice` and `duplicate` buffers being exceptions to this rule justified/intentional?

Unless we consider this a bug this would be change in behavior and we may have to add new or modify existing interfaces (add parameter to `ByteBuf.slice(..)` and `ByteBuf.duplicate(..)` to specify behavior) to get the new behavior. @normanmaurer @trustin?

**Comment by merlimat** [comment]
I was trying the approach you describe by making `AbstractDerivedByteBuf` to inherit from `AbstractReferenceCountedByteBuf`, the only problem is that starting the `refCnt` from 1 might not be correct, because if I do: 
```java
ByteBuf b = PooledByteBufAllocator.DEFAULT.buffer(100);
ByteBuf dup = b.duplicate(); // dupCnt == 1
dup.retain();  // dupCnt == 2
dup.release();  // dupCnt == 1 --> dup is not recycled
b.release();
```

I'll try to put the `refCnt` logic into `AbstractDerivedByteBuf` and handle the start from 0 case.

**Comment by Scottmitch** [comment]
@merlimat - What is your expectation for the example you gave? You retained the `dup` so you should have to call `release` 2 times right?  I think care just needs to be taken to ensure the retain/release also gets properly distributed to the wrapped buffer.

**Comment by Scottmitch** [comment]
@merlimat - After further review I don't think the `RECYCLE` mechanism provides any benefit in the majority of cases.  Currently the "derived" buffer will only ever be recycled if the release call is made on the "derived" object, and the "wrapped" buffer ends up being "fully released" (aka refcount goes to 0).  From my experience this is not the common use case and thus the "derived" buffers will not be recycled.  I have consulted with @normanmaurer and I am going to remove the recycle feature for the pooled derived objects because it adds complexity/overhead in the majority of cases.

**Comment by Scottmitch** [comment]
Closing as we no longer pool derived buffers as of https://github.com/netty/netty/pull/4138

**Comment by merlimat** [comment]
Sounds good. Thanks!
