### ISSUE TITLE
Removing ByteToMessageCodec from pipeline does not post remaining bytes to channel

### ISSUE THREAD

**Issue by yawkat** [netty/netty#4087]
Netty Version: 5.0.0.Alpha2

Context:
I have a line-based protocol that upgrades to a binary protocol. After removing the line decoder (extending ByteToMessageCodec) during the upgrade, I lost buffered data from the line decoder.

Removing a ByteToMessageDecoder from a channel pipeline will fire the buffered bytes in that decoder into the channel to make them available to other channel handlers. Removing a ByteToMessageCodec, however, does not do the same and instead silently discards the data.The javadoc of ByteToMessageCodec states that it should behave like a combination of ByteToMessageDecoder and MessageToByteEncoder, which it does not in this case.

**Comment by normanmaurer** [comment]
@yawkat sounds like a bug... looking into it now.

**Comment by yawkat** [comment]
I *think* delegating `channelInactive` and `handlerRemoved` to the decoder should fix it if that helps.

**Comment by normanmaurer** [comment]
@yawkat yep something like that... working on it :)

**Comment by ctron** [comment]
I do think this change added a rather strange behavior to netty.

Assuming you have chain of:
* LengthFieldBasedFrameDecoder
* MyCodec -> based on ByteToMessageCodec
* ...

In the past once the channel got closed, nothing happened. Which is somewhat expected.

With this change "MyCodec" gets it's `decode` method called with an empty buffer. Thus the initial idea of adding a `LengthFieldBasedFrameDecoder` before the `ByteToMessageCodec` in order to ensure that only complete frames are passed on is irrelevant now, since `MyCodec` now always has to check for an empty buffer, or it will result in an `IndexOutOfBounds` exception.

**Comment by ctron** [comment]
Maybe a solution would be to only fire `decode` when there is actual data in the buffer.

**Comment by normanmaurer** [comment]
Maybe we should only forward if it's not caused by a close of a Channel?

**Comment by ctron** [comment]
I am just digging through the source.

So `ByteToMessageDecoder` has `decodeLast` which is especially for this case. Defaulting to a call to `decode`. Same for the `ByteToMessageCodec`. So I would say, this is the same behavior now for both classes, which this issue is actually about.

However IMHO this is not what it should be in the first place looking at the idea in the javadoc of the `ByteToMessageDecoder`. However this may be just my point of view :wink: 

I guess I will open a new issue for this.
