### ISSUE TITLE
Consider swapping to the nghttp2 priority algorithm

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4462]
https://docs.google.com/presentation/d/1x3kWQncccrIL8OQmU1ERTJeq7F3rPwomqJ_wzcChvy8/edit

**Comment by nmittler** [comment]
FYI @normanmaurer @Scottmitch @louiscryan

**Comment by Scottmitch** [comment]
@nmittler - Yes I need to think about slide 10 a bit more...haven't had cycles but seems different than what we do.

**Comment by ejona86** [comment]
That scheduler looks good, and is the approximate form of what I would expect most priority-aware schedulers for HTTP/2 to look like. We may want to tweak some details though.

That scheduler design is well-known to networking: it is "weighted fair queuing" (WFQ). However, normal WFQ is based on packets (with already-determined size), so it does have some modifications. With HTTP/2, CPU schedulers tend to be a better fit than networking schedulers, because for efficiency they have to introduce the idea of a quantum (like `minAllocationChunk` in #4464) and because they tend to react rather than predict.

Linux's [O(1) scheduler](https://en.wikipedia.org/wiki/O(1)_scheduler#Overview) has the same approach as the scheduler in #4464 (round-robin). And Linux's [Completely Fair Scheduler](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/Documentation/scheduler/sched-design-CFS.txt) (CFS; sections 1-3 apply to this discussion) has the same approach as seen in nghttp2. Note that I believe CFS uses a red-black tree instead of a heap just because it is slightly better suited to the kernel; they could have used a heap if they wanted.

Fair queuing in general is based on simulating "ideal" hardware that is natively able to process in parallel. E.g., if you had 3 streams, it would send bits for each stream simultaneously but at 1/3 the rate. You "simply" "monitor" how that ideal hardware would have progressed and have your real system approximate that.

The primary change I would suggest is to make the pseudo time concrete, namely: "bytes written." Linux's CFS uses "nanoseconds" as its pseudo time, which makes it much easier to understand.

That also means that the priority accounting would be different. If we keep the sum of weights of _active_ streams per queue and then:
```
t[i] = t_last[p] + nsent[i] * sum_of_weights / weight[i]
```

So if we have three active streams, each with default priority 16, then if one is scheduled to send 10 bytes you would increment t[i] by 30 bytes (which agrees with the "ideal" model, since it should go 1/3 the rate).

It looks like `nsent` is just a quantum (100 bytes) in the presentation. Instead, I'd suggest we peek() at the next item in the queue, use its time + a quantum (say, 1K).

**Comment by Scottmitch** [comment]
I will throw together a PR for this.

**Comment by normanmaurer** [comment]
@Scottmitch w000t!

**Comment by nmittler** [comment]
@Scottmitch, you may want to chat with @ejona86 about this ... he had some ideas for the implementation that may just involve a slight tweak of the algorithm used for the uniform distributor.

**Comment by Scottmitch** [comment]
@nmittler - Sgtm. I was planning on coordinating when I got back tommorow. The tips above are helpful too.
