### ISSUE TITLE
disruptor

### ISSUE THREAD

**Issue by carrot-garden** [netty/netty#447]
Norman:

I really like what you guys do with your revolutionary changes for netty 4; 

in the spirit of "revolutionary changes", do you think you could take a look on
http://code.google.com/p/disruptor/

the idea would be to replace netty pipeline with a disruptor ring buffer;
presumably, it will make it X 100 faster;

I hope you can find time to take a deeper look and share your thoughts;

thank you;

Andrei.

**Comment by oracleocm** [comment]
@hepin1989 哥们,还是用数t据说话..你看上面 youtobe 里面那俩老外 表现的多好，你好厉害。89年的 就熟悉的这么多

**Comment by hepin1989** [comment]
@oracleocm netty will not dependent on other project ,you can see it right?

**Comment by oracleocm** [comment]
@hepin1989 wo jue de tamen shi zai xiagao

**Comment by normanmaurer** [comment]
@oracleocm please speak english in our issue tracker.

**Comment by daschl** [comment]
@hepin1989 that is true, there are no plans to have a dependency on a third party project any time soon.

**Comment by daschl** [comment]
@normanmaurer that guy is a bot I think (https://github.com/oracleocm?tab=activity)

**Comment by hepin1989** [comment]
@normanmaurer what he said in chinese PINYIN is that :"what they are doing is stupid."shame of that!

**Comment by trustin** [comment]
This thread went way too far. Closing and locking.

So far, nobody is known to have attempted to replace Netty's internal event queue with Disruptor. I guess it's because it's impossible to do that in a single simple short-term task.  If you are interested, please consider to propose the necessary internal changes in a new pull request or a new discussion issue.

**Comment by normanmaurer** [comment]
@trustin +1
