### ISSUE TITLE
io.netty.util.Recycler.WeakOrderQueue.Link.next may needs to be synced

### ISSUE THREAD

**Issue by shawn11ZX** [netty/netty#4493]
As I read through the source code of Recycler.java, I understand the WeakOrderQueue is used when a resource is recycled in a thread other than the one from which it's allocated.

Each 16 items of resource is put in a Link item, which itself has a read pointer and writer pointer. The writer pointer is based on AtomicInteger because it's need to be read by a different thread that write it.

Since the field Link.next is also read by a different thread that write it, it may need some sync too.

**Comment by Scottmitch** [comment]
@normanmaurer - Assigned to you :smile:

**Comment by normanmaurer** [comment]
@belliottsmith WDYT ? (as the code was contributed by you :))

**Comment by belliottsmith** [comment]
// a queue that makes only moderate guarantees about visibility: items are seen in the correct order,
    // but we aren't absolutely guaranteed to ever see anything at all, thereby keeping the queue cheap to maintain

The general idea of the WeakOrderQueue is that behaviour can piggyback on the many other "volatile" work done in the system, since we don't care about promptness, and even in a bizarre system that never touches volatile, eventually all memory operations are made visible (only risk would be this code somehow being inlined into a gigantic loop wherein the state mutations are optimised into local ones... but I don't want to see that loop :).

However, the Recycler imposes guarantees anyway, just a step backwards, in `Stack.scavenge()`; if no forward progress is made in consuming the current queue, the cursor is reset by reading its head pointer (which is volatile).  So it's guaranteed to have visibility, but the guarantee is only enforced when we cannot proceed without it.

**Comment by normanmaurer** [comment]
@belliottsmith makes sense and thanks for the fast reply! @shawn11ZX so I think we can close this.

**Comment by shawn11ZX** [comment]
thanks for the explanation:)
