### ISSUE TITLE
DnsNameResolver design questions

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4529]
Hi there,

Please advice if the bug tracker is not the right place to discuss this.

I'm eager to use the new DnsNameResolver from 4.1, but I have a few questions and hit a few limitations.

First, why does it resolves a `SocketAddress` instead of just a String? It looks to me that the sole purpose of passing a `SocketAddress` is to pass a port, so it can return a `InetAddress`. Isn't this the user's job? It looks like extra allocation to me.

Then, the DnsNameResolver comes with a built-in cache that users have no control on. For example, it would be great if one could know if the response was a cache hit or a cache miss. But everything is either private or package private, so it's very hard to extend/override.

Regards

**Comment by trustin** [comment]
> `SocketAddress` vs String + port

+1. I should change the API.

> DnsNameResolver cache stats

+1. Do you have any additional request wrt DNS resolver cache? e.g. pluggable cache policy

**Comment by slandelle** [comment]
Hey @trustin 

Regarding caching, what I'm trying to do is have each Gatling virtual user have its own cache. I have to check if each having its own DnsNameResolver/cache (and share eventloop) is affordable, or if I have to find another solution, like one global DnsNameResolver but custom key strategy. I'll come up with suggestions.

**Comment by trustin** [comment]
@slandelle Alright. Looking forward to your ideas. Feed back matters. ;-)

**Comment by slandelle** [comment]
Sure. Then, because of Gatling, I usually come up with non standard use cases :)

**Comment by trustin** [comment]
@slandelle That's where excitement comes. :-)

**Comment by slandelle** [comment]
Here's a list of what I'd like to change. Please advice.

1. NameResolver taking a SocketAddresses

I get NameResolver takes a port so it can cache the resolved SocketAddresses.
But I don't see why it takes a full SocketAddress. And the overloads that take a hostname and port actually delegate to the one taking a SocketAddress, creating an unresolved InetSocketAddress, hence an internal InetSocketAddressHolder for nothing.

IMHO:
* I'd remote the overloads that take a SocketAddress
* I'd create a simple dedicated internal immutable class for cache key instead of using SocketAddress.

2. NameResolver.isSupported

I fail to see the intent here, could you please explain? Why would one want to resolve an already resolved address?
If above suggestion is accepted, it looks like it could be dropped

**Comment by slandelle** [comment]
@trustin I can tackle this ASAP if you agree. Then, I can work on the Hosts file resolver and the composite one (I have to port from my own API and from Scala).

**Comment by trustin** [comment]
> `NameResolver` taking a `SocketAddress`

I don't think it should require a port. How about just removing the port part from the `NameResolver` API completely? i.e. replace `SocketAddress address` with `String name` and change the result of resolution to `InetAddress`. What do you think?

> `NameResolver.isSupported()`

When a user attempts to connect to a remote peer, a user may pass a `SocketAddress` that's resolved already. e.g. a user can simply use `new InetSocketAddress(..., ...)`

I agree that we don't really need to have `isSupported()` because of this, because a `NameResolver` implementation can simply check if the `name` string is an IP address already.

**Comment by trustin** [comment]
I spoke too soon. It's been a while since I wrote this API obviously. :-)

> `NameResolver` taking a `SocketAddress`

As you know `SocketAddress` itself does not have the notion of 'port'. I intended to use `SocketAddress` so that some implementations use a dedicated address type, and that address type might not have the notion of 'port' at all.

> `NameResolver.isSupported()`

`Bootstrap` itself cannot assume the type of the `SocketAddress` a user specified as a remote address.  We could have simply passed it to a `NameResolver`, but it would cause a `ClassCastException` because of how Java generics work.  `isSupported()` was introduced to avoid the `ClassCastException` when the type parameter of `NameResolver` is not `SocketAddress` but one of its subtypes.  If we did not use a type parameter for `NameResolver`, we would have not needed `isSupported()` at all.

**Comment by slandelle** [comment]
It's a bit of a pity that InetSockAddresses and InetSocketAddressHolders will have to be instanciated over and over again downstream while the InetAddress will be cached, but I agree that's way cleaner and generic from an API pov.

I will provide a PR for this, and then build on top of it.

Thanks!

**Comment by slandelle** [comment]
I have the feeling that NameResolver is trying to do too many things: resolve names (methods that take a String) and resolve addresses (methods that take a SocketAddress).
Shouldn't it be split in 2: NameResolver and AddressResolver?

**Comment by trustin** [comment]
> Splitting into NameResolver and AddressResolver

+1

> NameResolver taking a String and returning InetAddresses

Perhaps NameResolver should return T? There's no common type for this unfortunately.. Alternatively, we could name it `InetNameResolver`?

> AddressResolver taking a SocketAddress and returning T extends SocketAddress

+1

**Comment by slandelle** [comment]
OK. I'll try to send a PR this week-end.

**Comment by trustin** [comment]
@slandelle Thanks a bunch! :+1:

**Comment by trustin** [comment]
@slandelle Are you working on the cache improvements? I was wondering if we need a dedicated cache interface so that a user can plug it in easily.

**Comment by slandelle** [comment]
@trustin I've started giving it a thought, yes.
My use case is a bit complex and unusual. I need to segregate resolutions depending on who's asked for a resolution. I think creating a `DnsNameResolver` for each would be really expensive (one UDP connection each). So I think I need to overload `resolve` and `resolveAll` so I can a cache instance to  that would be used instead of the global one.

I'd also indeed introduce a dedicated interface so we can abstract getting from and putting in so users can plug in there.

WDYT?

**Comment by slandelle** [comment]
@trustin ping :)

**Comment by trustin** [comment]
@slandelle Sounds good to me. Looking forward to your PR. :-)

**Comment by normanmaurer** [comment]
+1

**Comment by slandelle** [comment]
Will do in 1-2 weeks. Thanks!

**Comment by normanmaurer** [comment]
Awesome! Thanks 👌

**Comment by slandelle** [comment]
@trustin @normanmaurer Sorry for the delay. PTAL at #4668.

**Comment by normanmaurer** [comment]
@slandelle can this be closed now ?

**Comment by slandelle** [comment]
Yes
