### ISSUE TITLE
Replace MessageDigest usage

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#4641]
See 
https://github.com/netty/netty/pull/4594

**Comment by normanmaurer** [comment]
@CodingFabian is this still on your to do list ?

**Comment by CodingFabian** [comment]
yes :) But not sure how worth it actually is.

**Comment by CodingFabian** [comment]
Hi @normanmaurer,
please find 2 proposals for using bouncycastle code.
Actually I would vote for a third one: take the optimized one and replace byte[] with ByteBuf (it then also brings its on Pack.* methods).
But because i  am not versed in writing ByteBuf code, I thought Ill first check if that could be the way to go and ask for advice how to best change the methods to use ByteBuf

**Comment by normanmaurer** [comment]
Let us close this for now as won't fix.
