### ISSUE TITLE
Use Http2GoAwayException consistently

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4710]
The HTTP/2 codec handles GO_AWAY differently depending on when it occurs.

1. If you have a buffered stream and receive a GO_AWAY, the buffered stream is terminated with a StreamBufferingEncoder.Http2GoAwayException that contains the details.
2. If you were to create a stream after a GO_AWAY was received, we will invoke the default encoder logic, which will cancel the stream with an Http2Exception.

Application code should be able to reliably handle `Http2GoAwayException` without worrying about the distinction here. We should promote Http2GoAwayException to a top-level exception and always return that for all GO_AWAY cases.

**Comment by Scottmitch** [comment]
@nmittler - Are thinking about expanding  [connection().goAwayReceived()](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L146) to other frame types?

**Comment by nmittler** [comment]
@Scottmitch err no ... I suspect that this just requires a change to `StreamBufferingEncoder`.  Were you thinking that some sort of expansion to the connection interface is needed?

**Comment by Scottmitch** [comment]
> Were you thinking that some sort of expansion to the connection interface is needed?

@nmittler - Nope. Seems like `StreamBufferingEncoder` already does account for not allowing new streams via the link I provided above, and existing streams are cleaned up via a connection listener [onGoAwayReceived](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L115). I'm just curious as to what cases were missed, or what I'm missing.

**Comment by nmittler** [comment]
@Scottmitch I think the problem here is that `GO_AWAY` is handled differently depending on when it occurs.

1. If you have a buffered stream and receive a `GO_AWAY`,  the buffered stream is terminated with a `StreamBufferingEncoder.Http2GoAwayException` that contains the details.
2. If you were to create a stream after a `GO_AWAY` was received, we will invoke the default encoder logic, which will cancel the stream with an [Http2Exception](https://github.com/netty/netty/blob/72accceeacf15d13358d5c46d5c414fc49f6c38d/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L1026).

GRPC, for example, has code that is specifically checking for `Http2GoAwayException` and can return the wrong status if the second condition occurs above.

Maybe what we need to do is to promote `Http2GoAwayException` to a top-level exception and always return that for the GO_AWAY case.  WDYT?

**Comment by Scottmitch** [comment]
@nmittler - I see. If you depend upon this exception and its contents then perhaps it does make sense to promote this exception type.

Can you point me to where this is used in gRPC? I just did a grep on master for `Http2GoAwayException` and didn't find anything.

**Comment by nmittler** [comment]
We currently have our own copy of `StreamBufferingEncoder` and have an [open bug](https://github.com/grpc/grpc-java/issues/1060) to migrate to Netty's version.  Our logic for handling the GO_AWAY exception is [here](https://github.com/grpc/grpc-java/blob/be6008666e9012a35f77defaab8e95730b81b838/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L375).

**Comment by Scottmitch** [comment]
@nmittler - Can you clarify this issue title and description (or open a new issue)? The current title/description doesn't really represent the issue. `StreamBufferingEncoder` does account for `GO_AWAY` it is just that the behavior of the codec (including `StreamBufferingEncoder`) is not always consistent w.r.t to GOAWAY.

**Comment by nmittler** [comment]
@Scottmitch Agreed ... done.

**Comment by ejona86** [comment]
I'm not really for `Http2GoAwayException` being used for case 2, _especially_ if it requires `Http2GoAwayException` to be promoted outside of `StreamBufferingEncoder`.

The application needs to be in the loop for go-away processing. If the application is trying to create new streams after it is been notified of the goaway, then that seems like the application needs to be fixed. I feel like this case is a programmer error.

The current use of `Http2GoAwayException` is for when the stream was conceptually-created _before_ the goaway was received, which is part of normal operation. As in, the application didn't do anything wrong, because it couldn't have known the goaway was coming. The specialized exception is actually only necessary because of timing issues where StreamBufferingEncoder cancels the pending operations before all listeners have been notified of the goaway (including the application). If there is a preferred way to prevent the timing issue I'd recommend doing that and trashing `Http2GoAwayException` instead of trying to use it in more places.

I don't believe that making goaway "more consistent" is enough to fix the true gRPC bug. There are many possible other reasons that the channel may be unusable for new streams (e.g., there was an io error). I believe that these today would report an error of ClosedChannelException (similar to grpc/grpc-java#1330), which is very non-helpful and unrelated to goaway.

**Comment by Scottmitch** [comment]
I agree with @ejona86 .... if there is another more generic way lets seek that out.

I wonder if it makes sense to propagate `Http2Connection.Listener` events for these "future streams". We would have to be sure the listeners can differentiate these streams as "future streams", but then we may not have to have an alternative interface to notify for "future stream lifecycle" events. @nmittler - WDYT, any other ideas?

**Comment by nmittler** [comment]
I don't think that we can really change `Http2Connection.Listener` since the `StreamBufferingEncoder` is a plug-in and `Http2GoAwayException` is not part of the API contract in any way.

I think for now, we just leave the Netty code as-is and possibly revisit when we get to child-channels.
