### ISSUE TITLE
setAutoRead (false) does not work from inside channelRead ()?

### ISSUE THREAD

**Issue by scramjet** [netty/netty#4895]
Hello, I have some Netty logic that is acting essentially as an HTTP proxy. After establishing an incoming HTTP connection with a client, in the channelRead () call that receives the client's `HttpRequest` message, I open an outgoing HTTP connection to a backend service. Just before opening the outgoing connection I `setAutoRead (false)` on the client channel to delay reading the HTTP request body until I have a connection to write it to — the handler for the outgoing channel then sets `setAutoRead` to true when the channel is opened. However, Netty still immediately delivers the `HttpContent` message from the client to my handler, causing it to drop the data.

I've seen other similar issues reported here (and fixed) e.g. #2977 #2375 #2958. I do have an SslHandler in the pipeline, but the issue persists with it removed.

The project is in Clojure, so I'm not posting code, but happy to describe the logic in more detail if needed.

Netty 4.0.34, OS X 10.11.3, Java 8.

**Comment by Scottmitch** [comment]
What transport are you using (NIO, EPOLL) and do you set a custom `RecvByteBufAllocator`?

**Comment by scramjet** [comment]
NIO, no other customisations

**Comment by Scottmitch** [comment]
@scramjet - Sounds like this is reliably reproducible? If so could you either:

1. Provide a reproducer. OR:
2. Put a breakpoint on [AbstractNioByteChannel.java#L143](https://github.com/netty/netty/blob/netty-4.0.34.Final/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L143) after the first read occurs and describe the behavior (what is the value of `config.isAutoRead()`, do you re-enter your channelRead before this point is hit, etc...).

**Comment by scramjet** [comment]
Yes, it is reproducible.

Because this is Clojure, debugging at the Java level is going to be tricky (and I really don't fancy rewriting the relevant logic in Java). I'll have a play with hooking into the process with jdb, and if that doesn't work I'll find another way.

Thanks,

Matt.

**Comment by normanmaurer** [comment]
@scramjet any updates ?

**Comment by scramjet** [comment]
Hi Norman,

sorry, no update yet. I'm right in the middle of things, and for now I've added a temporary buffer as a workaround.

I'll set up an IntelliJ project and put a breakpoint in the suggested location when I get some time.

**Comment by rkapsi** [comment]
@scramjet @normanmaurer @Scottmitch - I'm reading a bit in the tea leafs here but I believe the described behavior can be explained by stuff that is happening in the `HttpObjectDecoder` on lines 231-232 or 251-252 (easy case) and generally (let's say line 279) if there is enough input available to emit multiple events.

My understanding of `setAutoRead()` has always been that ChannelHandlers are free to emit as many events as their like from some input and they're not subject to the auto read flag which leads to trouble in downstream handlers if they depend on `setAutoRead()` and expect one message at a time.

We solve the problem in two ways:

1. We accept all connections with auto reading turned off and use `read()` exclusively.
2. There is a ChannelHandler sitting right behind the HttpServerCodec that acts as a buffer and is feeding off `read()`, `channelRead()` and `channelReadComplete()`

**Comment by scramjet** [comment]
Hi Roger, that sounds totally plausible and reasonable. And thanks very much for looking into it.

It sounds like the temporary buffer I've added in my handler is effectively using solution number 2, which I'm fine with for now. If it comes up again, I'll look into a more reusable solution.

Cheers,

Matthew.

**Comment by Scottmitch** [comment]
@scramjet - Just wanted to clarify the expected behavior of `autoRead` ...

`autoRead` is used to determine if when the current read loop finishes, if we should keep the `read` operation set on the select mechanisms (epoll, nio's epoll, etc...). How much the read loop can read per event loop wake up is controlled via [RecvByteBufAllocator](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/RecvByteBufAllocator.java). The default `RecvByteBufAllocator` will read at most 16 times (for most channel types) from the socket, or if `autoRead` is turned off (and a [few more boarder conditions](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultMaxMessagesRecvByteBufAllocator.java#L99)). However keep in mind this is at the level of reading from the socket, a single socket read may be translated to `[0, n)` events depending on what is in the pipeline and what data has been read. As suggested by @rkapsi if your handlers have specific limitations regarding how many messages can be handled you will have to implement some sort of queuing mechanism (manually calling `read()` has the same behavior that a single socket read can result in `[0, n)` events in the pipeline).

**Comment by scramjet** [comment]
@Scottmitch I appreciate you taking the time to detail that. Yes, now that it's been pointed out, it's obvious why an intermediate codec might generate several messages for a single read. With that in mind, the solution I have is perfectly acceptable, and I see that a solution is in the works to address this more generally.

Thanks again,

Matthew.
