### ISSUE TITLE
Channel (EPOLL) gets closed before response is consumed #2

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5082]
Netty 4.1.0.Final-SNAPSHOT

I have an unit test which I originally created for #3709 and it has started failing as of 04/04/16 (Monday). It's possible that it's related to #5061 (got merged on Friday and we pulled the latest nightly on Monday).

I'm still looking but the summary of the unit test looks like this:

1. Netty HTTP client
2. Auto-Reading is turned off
3. A handler that calls `ctx#read()` as long as `!(msg instanceof LastHttpContent)`
4. Jetty HTTP server

The test issues 50 requests in a loop (one at a time) and waits for the response. Each request opens a new connection and Jetty is explicitly flushing the response and closing the connection. The test fails if no response arrives in ~5 seconds or so. Everything runs on localhost.

It's occasionally failing if EPOLL is being used. It never fails if NIO is being used. It also appears to never fail in EPOLL or NIO if I turn auto reading on from the get go (and change the handler a little bit to accommodate for it).

**Comment by normanmaurer** [comment]
@rkapsi can you check if https://github.com/netty/netty/pull/5067 fixes it ?

**Comment by rkapsi** [comment]
Checking...

**Comment by rkapsi** [comment]
@normanmaurer nope, the problems seems actually more persistent.

**Comment by normanmaurer** [comment]
@Scottmitch can you check ?

**Comment by Scottmitch** [comment]
yes will check

**Comment by rkapsi** [comment]
I can probably turn my test into a self-contained standalone version if needed.

**Comment by normanmaurer** [comment]
@rkapsi that would help a lot !

**Comment by Scottmitch** [comment]
yes please :+1:

**Comment by rkapsi** [comment]
@normanmaurer @Scottmitch please see https://github.com/Squarespace/netty-issue-5082

**Comment by Scottmitch** [comment]
@rkapsi - thanks! looking now.

**Comment by Scottmitch** [comment]
@rkapsi - Thanks again for the unit test! I found the issue:

- The initial read for the channel never gets done because by the time it executes the channel is not active [1]
- The channel is not active because it is closed [2] due to a RDHUP event we receive.
- We call epollInReady before we close [3] but return early because `readPending == false` [4].

I pushed some new code to #5067 to address the issue ... can you please verify?

[1] https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L768
[2] https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L377
[3] https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L370
[4] https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L826

**Comment by Scottmitch** [comment]
looks like github is experiencing some issues https://status.github.com/ ... doesn't look like the push operation made it to github's servers...

> 13:54 PDTGitHub.com is unavailable while we resolve an issue with one of our backend services.
