### ISSUE TITLE
Allow Netty-epoll use from preloaded System library

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5122]
In the same vein as #5043, it would be really useful if there was some way to use Netty's epoll without it doing the library initialization itself.   The fix would be pretty much the same as here: 379ad2c02ed0c0ae9f94e4081e3f910ece6380b7

cc: @nmittler

**Comment by nmittler** [comment]
This one may be a little trickier because the current implementation of [Native](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/Native.java#L60) assumes that it will throw if the library fails to load, rather than just printing out a debug message and proceeding

Is there some way of determining if the symbols have actually been loaded?

@normanmaurer thoughts?

**Comment by Scottmitch** [comment]
@nmittler - is trying to call a native method and getting a [UnsatisfiedLinkError](https://docs.oracle.com/javase/7/docs/api/java/lang/UnsatisfiedLinkError.html) sufficient for what you need?

**Comment by carl-mastrangelo** [comment]
@Scottmitch  That would probably  be good enough.  It looks like there are some side-effect free methods in Native.java like `offsetofEpollData()`.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - We can also add a side effect free method for this purpose (e.g. `initialize`, `isLinked`, etc...) to be more explicit.

**Comment by normanmaurer** [comment]
@carl-mastrangelo @Scottmitch I think using `offsetofEpollData()` should be good enough for now.
