### ISSUE TITLE
Object allocation concerns

### ISSUE THREAD

**Issue by Jire** [netty/netty#5299]
If Netty is to be used for high-performance, the object allocations must stay minimal. My experience with Netty so far has revealed unfortunate garbage allocations. All of my tests are on the latest 4.1.0.Final-SNAPSHOT from SonaType.

---

**io.netty.util.internal.MpscLinkedQueue$DefaultNode** is one of the biggest sources of pain. These objects are created very often as a result of `MpscLinkedQueue`'s implementation.

The source of this problem is here: https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/common/src/main/java/io/netty/util/internal/MpscLinkedQueue.java#L123

From my debugging results, almost all of the node allocations have duplicate values, thus I assume some type of caching system would be beneficial to prevent creating these nodes for the same values. Preallocating some nodes can also help.

---

**io.netty.util.Recycler$DefaultHandle[]** and **io.netty.util.Recycler$WeakOrderQueue$Link** are both huge sources of garbage! In fact, after some running time `DefaultHandle[]` surpasses `DefaultNode`! The cause of this is the creation of links (`io.netty.util.Recycler$WeakOrderQueue$Link`), which each have an initial size-16 array of `DefaultHandle`.

The source of the problem is here: https://github.com/netty/netty/blob/e10dca76017fee3bcea251f28933c16f4238ad52/common/src/main/java/io/netty/util/Recycler.java#L214

I assume that some type of pooling system for `Link` can be put in place to prevent so many allocations.

---

Profiling results on a server using an event group matching the number of available processors: http://i.imgur.com/9xm3i1O.png

As you can see, these allocations have a severe effect on GC pressure. There are so many allocations and my server is only hosting 2000 connections, `writeAndFlush` is called every 600ms per connection and there is no read activity.

**Comment by normanmaurer** [comment]
@Jire this means you will most likely schedule stuff on the `EventLoop` from outside. Is this true ? Like calling `writeAndFlush(...)` from outside a `ChannelHandler`. What you mean with "nodes have duplicate values" ? Can you give some more details ?

Once I have more info I will look into how to reduce these. 

Thanks for the report!

**Comment by Jire** [comment]
@normanmaurer My application only makes use of the thread's provided to the event loop group. For example, I maintain the reference to the group and schedule tasks here: https://github.com/Jire/Acelta/blob/master/src/main/kotlin/com/acelta/task/Tasks.kt#L16

As for calling `writeAndFlush`, I used your advice to improve performance and grab the channel's event loop to submit the preallocated flushing task: https://github.com/Jire/Acelta/blob/master/src/main/kotlin/com/acelta/net/Session.kt#L32

I did some debugging by printing the value parameters passed into `new DefaultNode<E>`. It revealed that almost all of the `DefaultNode`s are created with identical values, which is why I think a pool/cache system would be very beneficial.

I appreciate you taking my information to your concern, please let me know if there is anything you need me to do. I am currently playing around with ways I can implement my suggestions, and I'll let you know if I come up with any good solutions.

**Comment by normanmaurer** [comment]
@Jire I would be interested to know from where the DefaultNode allocations happen. Like the stack trace of it. Can you provide it ?

**Comment by Jire** [comment]
@normanmaurer This is the stack dump that occurs very often:

[java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at io.netty.util.internal.MpscLinkedQueue.offer(MpscLinkedQueue.java:139)
	at io.netty.util.internal.MpscLinkedQueue.add(MpscLinkedQueue.java:252)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:283)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:672)
	at com.acelta.net.Session.flush(Session.kt:32)
	at com.acelta.game.Player.tick(Player.kt:25)
	at com.acelta.plugin.plugins.LoginPlugin$1$$special$$inlined$invoke$lambda$lambda$1.invoke(LoginPlugin.kt:33)
	at com.acelta.plugin.plugins.LoginPlugin$1$$special$$inlined$invoke$lambda$lambda$1.invoke(LoginPlugin.kt:15)
	at com.acelta.task.Tasks$repeating$1.run(Tasks.kt:51)
	at com.acelta.task.StoppableTask.finish(StoppableTask.kt:15)
	at com.acelta.task.TickTask.finish(TickTask.kt:10)
	at com.acelta.task.Tasks.tick(Tasks.kt:34)
	at com.acelta.task.Tasks$1.run(Tasks.kt:19)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:126)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)](url)

**Comment by normanmaurer** [comment]
Most of these issue can prolly fixed by https://github.com/netty/netty/pull/5051 . I will look into it later this week in more detail.

**Comment by Jire** [comment]
@normanmaurer That link was very helpful! I patched my Netty to use the new JCTools like this: https://github.com/Jire/Acelta/blob/master/src/main/java/io/netty/util/internal/PlatformDependent.java#L601

**Comment by normanmaurer** [comment]
@Jire could you share how the impact of the change looks like? Are the GC issues mostly gone?

**Comment by Jire** [comment]
@normanmaurer They are actually COMPLETELY gone with the patch, I can't find a single reminiscence of any of the mentioned objects! :smiley:

**Comment by normanmaurer** [comment]
Wooot! /cc @nitsanw @trustin @nmittler @Scottmitch

**Comment by nmittler** [comment]
@normanmaurer Woot! :)

**Comment by normanmaurer** [comment]
Working on this....

**Comment by normanmaurer** [comment]
@belliottsmith WDYT about the idea of reusing `Link` objects here ?

**Comment by belliottsmith** [comment]
It's a while since I thought about this, but I do recall at the time considering recycling the Links, so I'm sure it's possible.  But it's worth considering that the reason I chose not to introduce the complexity at the time was that these Links *aren't meant to be used* - they're for misbehaving users.  Recycling was (at the time) meant to happen only on the allocating thread, as the prior behaviour was that recycled objects recycled otherwise were just discarded and become garbage themselves (at a much higher rate than Link objects)

I'll try to find some time over the next couple of days to refresh my memory about the design, as I don't think recycling of the Links is 100% obvious - at least with low overhead.  Any approach will either introduce higher costs for recycling with atomicity, or some other weird edge cases in memory usage - though we could certainly bound it.

If this is now considered an acceptable recycle mechanism (rather than a last resort) some more thought could be given to periodically incurring higher recycle costs, that are amortised to only very low increment, that permit more consistent behaviour.  Such as bounding the number of Links any non-owning recycler can populate before we force a more expensive recycle, that reclaims the Links and ensures the items aren't floating indefinitely.  Or increasing the polling frequency of the lazy recycle queue, but only if we detect that it is in use lazily.

**Comment by normanmaurer** [comment]
Yep recycling can happen if the user weites from outside the EventLoop so would be nice to refuce the GC here if possible

**Comment by nitsanw** [comment]
@normanmaurer looked briefly at the recycler, so may not be getting this straight, but it looks like an SPSC queue, if that's the case you could replace with the unbounded SPSC array queue maybe?

**Comment by normanmaurer** [comment]
@nitsanw maybe.... let me check.

**Comment by belliottsmith** [comment]
It is indeed an SPSC, but one that issues fewer memory barriers than even the SpscArrayQueue - although glancing at it, that doesn't seem to be an inherent limitation with SpscArrayQueue, and perhaps it could simply be modified.  I haven't digested BaseSpscLinkedArrayQueue nor SpscGrowableArrayQueue, as they're a little less friendly on the eyes, but one assumes they're similar in that respect.

One thing to consider is that the JCTools impls all use padding extensively, which could be costly, at least on cache occupancy, given how many of these we may have (potentially several per application thread, so we should assume many thousands of instances).  We do not expect contention, so optimising for this is unwelcome in my opinion - but perhaps not unduly. 

More problematic is that they don't automatically _shrink_ which is probably not a good property, as this could rapidly consume huge quantities of memory given the random order in which recycled items will be consumed.  Perhaps this could also be addressed, but that looks like it would require a different implementation.

However it is certainly possible to use SpscGrowableArrayQueue with these caveats.

**Comment by normanmaurer** [comment]
@belliottsmith thanks for having a look. I think really the biggest problem is the "not shrinking" thing that you mention. @nitsanw any idea if you could make it work to shrink ?

**Comment by belliottsmith** [comment]
@normanmaurer @nitsanw bear in mind any shrinking would need to be performed by the _consumer_ as we cannot guarantee producers continue to furnish anything

**Comment by normanmaurer** [comment]
@belliottsmith true... maybe just "reallocate" a new queue once the percent of internal storage and usage becomes to low would be a compromise here. /cc @nitsanw

**Comment by belliottsmith** [comment]
Well... we expect the queue to regularly empty itself, since the consumer drains in batches (which could do with optimising in jctools, as an aside), so we can't simply resize it when it gets low else we'll do it all the time and probably be worse for garbage than we are now.  

Recycling links has the advantage of self-tuning, and producing no garbage globally once a steady state is reached.  Resizing an array queue requires an explicit management algorithm tracking recency of use watermarks for each queue, that probably trades total memory watermark for gc rate, as garbage will be produced when any individual queue is reassessed.

**Comment by normanmaurer** [comment]
@belliottsmith true... So maybe using the `Link` is not really a bad thing at all. That said we may want to increase the size of the array that is stored in the `Link`. Any reason you choose `16` originally ? Just to mimize the memory overhead ?

**Comment by belliottsmith** [comment]
That, and because it is large enough to amortise the costs associated with it well, yet small enough that a majority of accesses will involve only one cache miss.  Certainly nothing stopping making it bigger.

**Comment by Jire** [comment]
@normanmaurer @belliotsmith I think there should be a way to programmatically configure these changes, including changing the MPSC, SPSC, link array size, etc.

Sometimes users want something other than the defaults, and the only way to do that right now is by masking the desired class with a copy and paste containing your changes.

**Comment by normanmaurer** [comment]
@belliottsmith gotcha... So maybe at least we should allow change the size via a System property. 

@Jire I think make everything changeable programmatically is not feasible and even not makes a lot of sense. What we should allow is to adjust some of the parameters tho.

**Comment by belliottsmith** [comment]
@normanmaurer sounds reasonable, yeah

@jire gotta agree with @normanmaurer here; making absolutely everything configurable over time introduces significant burdens, and in this specific case at least the mpsc queue is tightly coupled, and we would lose some of its power by untying them, unless we introduced a new interface for others to implement - but really, who would?  it's a lot of work, and of dubious utility.  Sometimes you just have to let the devs make reasonable tradeoffs for you.

**Comment by normanmaurer** [comment]
@belliottsmith btw after looking again at the `Recycler` implementation I agree with you that once the Stack has "auto tuned" itself it should not produce more `Link` objects and so be mostly GC free. I think this was also what you referred to.

**Comment by belliottsmith** [comment]
Yes, at least once we start recycling them - at the moment the Link objects are discarded by the consumer (the owning thread), but if producers were to reuse them we would reach a steady state pretty rapidly.

It just occurred to me that the issues with the array approach are worse than I had thought, as actually we have one of these queues likely per (application thread * event loop thread) - i.e. perhaps tens of thousands.  So we really want to keep them lean.

There are some simple approaches for redistributing the recycled links that I can think of - for instance if we care we can have a variable for passing back a single recycled link from the consumer to each producer, so that in many cases we incur no synchronisation burden; we then have two options for the "failsafe" general mechanism, that guarantees reuse: 

A global MPMC, or a per-recycler SPMC "queue".  We don't actually need queue semantics, but it's probably not worth exploiting that right now.  We will only go to this queue once every Link items.  If we make Link size >= core count by default, the likelihood of competition is extraordinarily low (since we will clearly be doing much more work than just recycling).  The cost, whatever is incurred, should be well amortised, since I assume one recycled item per recycler represents approximately one query, so this should be a tiny fraction of system work.  Typical cost might be on the order of 100 cycles, so amortised per item we're talking 3-4; nothing we're likely to notice.

There is of course another fantastic optimisation we could do if we wanted, but it's a bit more work: we have many recyclers, and many consumers of these recyclable things.  However the _threads_ involved are often the same - it's only the recycler that is different.  We could centralise the management of all of the different logical recyclers for a given owning thread.  We would have a single queue for each application thread that recycles back to this owner.  This would cut out a whole dimension of costs.

We could couple this with a local buffer that pushes the recycled objects en-masse at the end of serving a query, cutting our synchronisation costs even further, and all but guaranteeing low competition.

**Comment by normanmaurer** [comment]
Thanks for all the comments. I think for now we should not over-engineer it :) So we should a for a simple solution that gives us less GC but still not make too many trade-offs. Do you think you will have some time looking into it? If not I may will do it over the next few weeks...

**Comment by belliottsmith** [comment]
Yes, I should have clarified I was mostly riffing for the long term there, if this garbage mitigation were to become seen as a performance cost centre.

My preference is for the simplest possible approach: enlarging the Link to perhaps 64 items by default (or 4 * core count if higher, say), and recycling them via a single shared MPMC queue.  We can then steadily improve it from there if the MPMC queue turns out to be a drain.  Since the cost is amortised to <1/64, it's unlikely to be an issue, and the simplest follow-up change is to switch to many SPMC queues (one per recycler).  The single MPMC queue should give a lower watermark of memory needed, so if it is fast enough it should probably be preferred.

One possibility to consider this time around is the quick single hand-back recycle from producer direct to consumer, which we could implement very naively if we like, to provide a cheap early mitigation.  i.e. as simple as a single field in the queue for a recycled link, that the producer can poll before going to the MPMC queue when it needs a new Link.  The first Link we recycle from any producer would go there, and the rest (if any) into the MPMC.

**Comment by nitsanw** [comment]
Consider using, or just scavenging for good ideas, stormpot:
https://github.com/chrisvest/stormpot
@chrisvest

**Comment by belliottsmith** [comment]
Thanks for the suggestion - that particular library is a little detailed for me to have time to digest right now, but it looks costlier, as it is a more general purpose centralised pool that seems to primarily utilise blocking queues.

I am a little disappointed to see there is no MPMCLinkedArrayQueue in JCTools ;)

I wrote one a while back, but it's much too complex to want to dust off just for this situation.  What we could do is simply size this queue large enough that we can cope with enough recycles to _minimise_ garbage without guaranteeing absolute zero; like all the other avenues we can then reassess later if there are still users having issues.

@normanmaurer: to answer your question I'd be happy to take a look, but would prefer to defer for a couple of weeks as I have a lot of other commitments right now, and would not want to rush it.

**Comment by normanmaurer** [comment]
Cool :) it's not super urgent so that's fine. If I will find time before I will let you know

**Comment by normanmaurer** [comment]
@Jire @belliottsmith see https://github.com/netty/netty/pull/5327

**Comment by normanmaurer** [comment]
I think we fixed many of the things suggested here. Please open a new issue if you think there are other places we should improve

**Comment by belliottsmith** [comment]
So, apologies for not doing this as I suggested I would - shortly after this ticket, a bunch of others opened up that questioned the very existence of the Recycler, so I thought I'd let the dust settle there before digging in.  I then eventually forgot all about it.

Please do ping me again if in future you think these improvements are worth revisiting, and that they'll survive at least a few months :)
