### ISSUE TITLE
TLS Renegotiation and Handshake Timeout

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5338]
We currently support a timeout for the initial TLS handshake, and if a renegotiation is initiated from the local peer. However this timeout does not apply if renegotiation are initiated by the remote peer. Should we also apply the timeout for remote initiated renegotiation?

Worth considering:
- TLS 1.3 removes renegotiation https://tools.ietf.org/html/draft-ietf-tls-tls13-13#section-1.2
- Given what SSLEngineResult provides ... more investigation is needed to determine how to detect if a remote renegotiation is in process.

**Comment by Scottmitch** [comment]
@normanmaurer @trustin @ejona86 @nmittler - WDYT. Is it worth it ... I'm leaning toward punting on this one but at least wanted to discuss.

**Comment by normanmaurer** [comment]
@Scottmitch I guess it is ok to just "not fix it"

**Comment by ejona86** [comment]
If it's a pain and it's not been shown to be a problem, I'd not bother. In my understanding, lots can go wrong in initial negotiation because of all the broken implementations out there. I'd expect less to go wrong during renegotiation that would just cause a hang. And renegotiation has been on the chopping block for a while now.

**Comment by Scottmitch** [comment]
Thanks for the feedback guys ... Lets consider this a "won't fix" for now
