### ISSUE TITLE
HPACK HeaderField implements Comparable

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5358]
Does HPACK's HeaderField need to implement Comparable? The `equals` comparison utilizes a equality function which "doesn't leak timing info" , but the `compareTo` function makes no such effort. It also does not appear that the `compareTo` method is used in operational code. Can we just remove it?

**Comment by Scottmitch** [comment]
@jpinner - WDYT?

**Comment by jpinner** [comment]
@Scottmitch I don't really remember why initially made HeaderField extend Comparable. The class is package-private and I don't see it used anywhere so it seems safe to remove.

As for timing attacks, it wasn't necessary to have a constant-time `compareTo` function since it isn't called during decoding.

**Comment by Scottmitch** [comment]
thanks @jpinner ! I'll clean this up.

**Comment by normanmaurer** [comment]
@Scottmitch actually I will do this as part of https://github.com/netty/netty/pull/5355 . This allows me to also not port some code ;)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5355
