### ISSUE TITLE
 initialize unreadable chanel with ServerBootstrap

### ISSUE THREAD

**Issue by hustfxj** [netty/netty#5362]
I are using netty 3.9. Now I want to create an unreadbable chanel with serverBootstrap. I won't make the chanel become readable until a event trigger. So how can i  do it?

**Comment by maseev** [comment]
If I understand you correctly, you can set `AUTO_READ` to false, like so `.childOption(ChannelOption.AUTO_READ, false)`. By doing so you'd prevent Channel to read data automatically. After that you can override `userEventTriggered` method in your ChannelInboundHandler and do something like this:

  ```
@Override
  public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
    if (evt instanceof EnableAutoReadEvent) {
      ctx.channel().config().setAutoRead(true);
    }
  }
```

You have to call the ChannelHandlerContext.fireUserEventTriggered method at some point in order to make your channel read data from the wire automatically (i.e. make it readable). Or you can simply call `ctx.channel().config().setAutoRead(true)` when your 'event' happens. I think that'll work out.

**Comment by normanmaurer** [comment]
@hustfxj you could call `channel.setReadable(false)` in the `channelOpen(...)` callback
