### ISSUE TITLE
netty 4.1-dev breaks gRPC master

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5472]
Running gRPC's helloworld-client with the current 4.1 branch fails with 
<img width="1120" alt="screen shot 2016-06-29 at 10 55 44 pm" src="https://cloud.githubusercontent.com/assets/1388179/16469209/0623cdba-3e50-11e6-97e6-08b0e3108f7e.png">

When building gRPC the following tests fail:
```
io.grpc.benchmarks.driver.LoadWorkerTest > runUnaryBlockingClosedLoop FAILED
    java.lang.AssertionError: Server failed to start
io.grpc.benchmarks.driver.LoadWorkerTest > runGenericPingPongAsyncClosedLoop FAILED
    java.lang.AssertionError: Server failed to start
io.grpc.benchmarks.driver.LoadWorkerTest > runUnaryAsyncClosedLoop FAILED
    java.lang.AssertionError: Server failed to start
io.grpc.benchmarks.driver.LoadWorkerTest > runPingPongAsyncClosedLoop FAILED
    java.lang.AssertionError: Server failed to start
```

I made an educated guess, and it seems like things stop working with the HPACK changes b4d4c0034d .

@normanmaurer @Scottmitch @nmittler @ejona86

**Comment by buchgr** [comment]
I don't (yet) know whether it's grpc or netty at fault here, but reporting this already so to maybe hold off releasing 4.1.2 until this is resolved?

**Comment by Scottmitch** [comment]
@buchgr +1 ... lets hold off on the release until we know whats going on ... and fix it if its a Netty issue.

**Comment by normanmaurer** [comment]
@buchgr looking into atm.

**Comment by normanmaurer** [comment]
@buchgr @Scottmitch update... it's definitely a netty bug I introduced. Working on a fix now, stay tuned :)

**Comment by normanmaurer** [comment]
@buchgr @Scottmitch ok I take this back... after poking around a bit I notice its a grpc bug as grpc just assumes that `AsciiString` is always using the whole array. To fix this it should take into account the condition when just a limited range of the array is used. This was no problem before as we always just created AsciiString instances that used the complete backing array. This was changed to eliminate extra memory copies and allocations.

Here is the code that needs to be fixed in GRPC:
https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/Utils.java#L110

@buchgr please fix and test again. If everything works after the fix please close this issue. You can buy me the 🍺 later ;)

**Comment by buchgr** [comment]
thanks @normanmaurer ! fixed by https://github.com/grpc/grpc-java/pull/1995

**Comment by Scottmitch** [comment]
good work @normanmaurer !
