### ISSUE TITLE
HttpClientUpgradeHandler doesn't buffer writes

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5544]
If you have a protocol like http/2, it's natural to try to send messages concurrently, but HttpClientUpgradeHandler will fail messages that are sent while its upgrade is in progress.  Instead of everyone writing something that buffers writes while the upgrade happens, it would make sense to provide an option to buffer writes automatically for the user.

If folks are interested, I can make a PR.

**Comment by mosesn** [comment]
Also, it would be really useful to be able to execute some arbitrary code depending upon whether the upgrade succeeded or failed.  For example, if you want to use multiplexing if the upgrade succeeded, but don't want to have concurrent requests on a connection if it failed, that requires a very different code path.

**Comment by normanmaurer** [comment]
@mosesn sounds good... @nmittler @ejona86 @Scottmitch WDYT ?

**Comment by nmittler** [comment]
@mosesn SGTM

**Comment by ejona86** [comment]
@mosesn, I'm not really sure I understand the plan. You can't send anything until the upgrade happens, because you don't know what protocol is in use. Like you mention a bit, depending on the outcome of the upgrade different frames should be used.

In grpc, we handle this with the same tool as we do SslHandler, which has this restriction:
> You must make sure not to write a message while the handshake is in progress unless you are renegotiating.

But even without that restriction, we have to do things manually because ALPN will choose the protocol. That's the same trouble as we have with HttpClientUpgradeHandler.

**Comment by mosesn** [comment]
@ejona86 we often know in advance which messages we want to send even if we haven't decided on the protocol.  Imagine you choose to only use the feature set from http/1.1, but allow your client to negotiate up to http/2.  You can rely on your upgraded pipeline to ensure the messages are in the correct form when you do, and you know you can send messages down the same connection because http/1.1 supports pipelining, and http/2 supports multiplexing.

Although `SslHandler` is documented that way, in practice it doesn't have the same behavior as `HttpClientUpgradeHandler`, and if you write to it, the writes will be buffered in a `PendingWriteQueue` 

With that said, things are slightly better for `SslHandler` or with ALPN than they are for `HttpClientUpgradeHandler`.  With `HttpClientUpgradeHandler`, the problem is that the upgrade is also a message.  When you send a request with a client using the upgrade handler, you then have to decide whether to send more requests down that connection eagerly, or if you decide you don't want pipelining HOL blocking you have to establish concurrent connections until you find whether you're on http/1.1.  What it comes down to is that we can't treat messages uniformly, because in reality the first message is privileged.

What I'm proposing are two changes in ergonomics.

1.  When possible, allow clients to proceed without knowledge of upgrading.
2.  When clients *must* know of the upgrade, alert them explicitly.

**Comment by ejona86** [comment]
Ah, okay. That sounds fine. It also sounds like you should also update `SslHandler`'s documentation since you're relying on a feature that is explicitly avoided.

Although Channels also can't be written to before active. Is there a push to make everything buffer when necessary, or should we instead push to have a handler that can buffer consistently? gRPC has [AbstractBufferingHandler](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L345) that extending classes call `writeBufferedAndRemove` or `fail`. It was actually non-trivial to handle all the edge cases (reentrancy, flushing at proper time, remaining "alive" after removal), and I wouldn't be surprised if we ignored cases because they couldn't happen in our application. I'm a strong fan of buffering, but want it to be reliable and predictable (and that is across buffering solutions; you may hit one buffer instead of another and you don't want different bugs/gotchas between the two).

> When clients must know of the upgrade, alert them explicitly.

In what way would that be different from the userEvent currently fired? Would it be a Future you could add listeners to, like `SslHandler`?

**Comment by mosesn** [comment]
@ejona86 actually the user event is fine for me, I just didn't realize they were fired.  I'll make a docs PR to add a note to the javadoc for the class.

Good point on `SslHandler`, I'll make a docs PR for that too.

I think it would be nice to provide AbstractBufferingHandler in netty–we've done something similar in finagle.

As an aside, I don't think there's something that says that writes can't happen before channelActive.

**Comment by ejona86** [comment]
> As an aside, I don't think there's something that says that writes can't happen before channelActive.

Yeah, I can't find any either. May @buchgr informed me originally. I did [check the implementation](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L840) before I mentioned it, so I do believe it is factually true, at least on some level.

**Comment by mosesn** [comment]
We ran into a problem where we moved our "let's start writing to the channel" from `channelActive` to a closure we hung off the promise returned by `connect` and suddenly all of the initialization code we had stuck in our `channelActive`s was happening after our writes–we moved the initialization code to `handlerAdded` and it ended up being fine.  So I think the `isActive` mentioned there might be a different kind of "active".

**Comment by ejona86** [comment]
@mosesn, do you not flush from the `handlerAdded`? If you just do a write and no flush, I could see that as working.

**Comment by johnou** [comment]
I was under the impression that writing in handlerAdded is not the right place..?

**Comment by johnou** [comment]
@ejona86 makes sense, thanks for the clarification.

**Comment by mosesn** [comment]
@ejona86 I'm not trying to write in `handlerAdded`–my point was that there is not a guarantee that `channelActive` fires before `write` happens.

**Comment by ejona86** [comment]
@mosesn I think we're splitting hairs then. It seems we are in agreement then that you can't write before the channel is active. Yes, there is a race between the channel going active and `channelActive` being called on your handler, because other handlers and run and futures may be completed.

**Comment by johnou** [comment]
Whilst there may be a race between other futures I am pretty sure @normanmaurer put in a great deal of effort to ensure handlerAdded and channelActive are invoked in the correct order.

**Comment by normanmaurer** [comment]
@mosesn can we close this or is there anything we need to do ?

**Comment by mosesn** [comment]
@normanmaurer I think we can close it.  At the time I didn't understand that channelActive doesn't necessarily come before writing.
