### ISSUE TITLE
Missing images in documentation - "No puml file found!"

### ISSUE THREAD

**Issue by scadgek** [netty/netty#5559]
The documentation page [User guide for 4.x](http://netty.io/wiki/user-guide-for-4.x.html) currently misses two images in the section [Dealing with a Stream-based Transport](http://netty.io/wiki/user-guide-for-4.x.html#dealing-with-a-stream-based-transport). They are currently replaced with a template image saying "No puml file found!".

Here are the two screenshots demonstrating the problem:
![selection_028](https://cloud.githubusercontent.com/assets/3458586/17051934/eeb65ee8-5003-11e6-8d0b-fcc01afeda1b.png)
![selection_029](https://cloud.githubusercontent.com/assets/3458586/17051939/f5258966-5003-11e6-8ad9-53a113a654c7.png)

**Comment by Scottmitch** [comment]
please post the images directly in github so we don't have to follow external links

**Comment by scadgek** [comment]
@Scottmitch fixed that, couldn't find any "attach" button at first

**Comment by Scottmitch** [comment]
@scadgek - Can you try again? I just cleared the cache [1] and it worked for me.

[1] https://help.github.com/articles/why-do-my-images-have-strange-urls/#removing-an-image-from-camos-cache

**Comment by Scottmitch** [comment]
@scadgek - Also clear your browser cache before you try (or use a "incognito"/"private browsing mode")

**Comment by scadgek** [comment]
Oh, now they appear. I didn't even clear the cache.

I thinks now this issue may be closed.

**Comment by ChuntaoLu** [comment]
seems like the missing images issue is happening again?

**Comment by scadgek** [comment]
@ChuntaoLu Not for me - just checked and they're all there.

**Comment by surrealcristian** [comment]
The issue is happening again.

-
 https://camo.githubusercontent.com/24ed1176ecca468dfb2b8b017bb927a8715a16f2/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f3832653366626530653264346466323833323262
- https://camo.githubusercontent.com/5b595baf5071bf669f81d08b7554064f4142cc69/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f6233316330626437626266633639666438326436
- https://camo.githubusercontent.com/24ed1176ecca468dfb2b8b017bb927a8715a16f2/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f3832653366626530653264346466323833323262

**Comment by surrealcristian** [comment]
#7374
