### ISSUE TITLE
use netty as http server , but it only process 6 requests at a time

### ISSUE THREAD

**Issue by enginespot** [netty/netty#5703]
Hello , I want to user netty as http server , so I create a demo which based on hello demo , but it only process 6 requests at a time ,

the main demo code as the follow:

```
ChannelHandlerContext ctx1;
    @Override
    public void channelRead( ChannelHandlerContext ctx, Object msg) {

        ctx1 = ctx;
        Thread t = new Thread(new Runnable(){
            public void run(){
                try {
                    Thread.sleep(60000);
                    FullHttpResponse response = new DefaultFullHttpResponse(HTTP_1_1, OK, Unpooled.wrappedBuffer(CONTENT));
                    response.headers().set(CONTENT_TYPE, "text/plain");
                    response.headers().setInt(CONTENT_LENGTH, response.content().readableBytes());
                    ctx1.writeAndFlush(response);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        t.start();
    }
```

it I send 12 request at the same time ,
the first 6 requests will take about 61 seconds , and also the other 6 requests will take 121 seconds

but as I know the new thread does block channel thread , so all of the request time should around 60 seconds 

by the way , I know I should not use Thread within a Channel Handler , it is only a demo , it is for some complex scene

**Comment by maseev** [comment]
Hi @enginespot. From what I understand, you have a couple of issues with your code example. If you look at your code more carefully, it should be pretty straightforward why it takes so much time to process a single request. Here, have a look:

```java
ChannelHandlerContext ctx1;
    @Override
    public void channelRead( ChannelHandlerContext ctx, Object msg) {

        ctx1 = ctx;
        Thread t = new Thread(new Runnable(){
            public void run(){
                try {
                    Thread.sleep(60000);
                    FullHttpResponse response = new DefaultFullHttpResponse(HTTP_1_1, OK, Unpooled.wrappedBuffer(CONTENT));
                    response.headers().set(CONTENT_TYPE, "text/plain");
                    response.headers().setInt(CONTENT_LENGTH, response.content().readableBytes());
                    ctx1.writeAndFlush(response);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        t.start();
    }
```

First, you start a new thread per HTTP request, which waits 60000 milliseconds (60 seconds or 1 minute) before it would be able to send a response. Was it intentional? If so, I think you shouldn't be surprised why processing a single request takes so much time.

Second, you said that your server is able to process only 6 requests at a time. I don't see where you are initializing an EventLoopGroup, but if you decided to go with the default one (with no arguments) then the number of event loop threads would be computed like [this](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/MultithreadEventLoopGroup.java#L39).

It's also unclear how you send HTTP requests to your server. I personally opened 12 tabs in Google Chrome and sent requests to the HTTP server from every browser's tab. I had the responses back within 10-12 seconds (I changed the sleep timeout to 10 seconds). Maybe you should review how you send HTTP request to the server?

Hope this helps.

**Comment by enginespot** [comment]
Hi @maseev , yes I  do it intentional , since there is an scene , for example , the channel will try to get data source from remote server async , but it will take more time , such as 1 minute

for one http request , it take 60 seconds , it is ok , but other request take 60*2 =120 second , and other take 60*3 =180 seconds , so , it is the question ,

I just debug the helloworld demo , the DEFAULT_EVENT_LOOP_THREADS is 8

I use postman to do the demo , and I tried to send 12 requests with in 10 seconds , and for the first 6 requests , it take 60 seconds , and other take 120 seconds.

**Comment by maseev** [comment]
> I use postman to do the demo , and I tried to send 12 requests with in 10 seconds , and for the first 6 requests , it take 60 seconds , and other take 120 seconds.

Well, if you do the math, it should become pretty clear that postman sends requests in so-called 'blocking' mode. It means that when you send first 6 requests, postman probably sends a first request to the server and put the other 5 requests to the queue (not sure about that, to be honest). When postman receives the response, it sends the second request and so on.

Can you try to send HTTP request from your browser, like I did?

**Comment by enginespot** [comment]
if I tried to use chrome , it also occur the problem , 

for chrome console , there is "stalled" field , the time is about 60 seconds , so hmm... I think the bug has no relationship with client , but netty 

can you reproduce the bug?

**Comment by enginespot** [comment]
you can also use browser , but , I think you should put the time longer and maybe your tab should be a bit more , maybe you hava much more cpu cores.

**Comment by enginespot** [comment]
@maseev so can you reproduce the scene by now?

**Comment by maseev** [comment]
Your problem is probably related to the fact that Netty manages a separate queue for all write (or write and flush) requests that are invoked from outside the event loop. So, when you call `ctx.writeAndFlush` from your thread (which you create per request), you technically put your data to the queue which will be processed later.

**Comment by enginespot** [comment]
Hmm... it should not , since that when I debug it , I find that netty does accept tcp data after the 6 request 

if I use nodejs to do the job within one thread, the performance should be very quickly , but for netty , it blocked 

hmm... maybe it is a bug or I should change channel option or other option?

**Comment by normanmaurer** [comment]
@enginespot I think there a remultiple issues here..

1) You may mess up ordering as you never know when which Thread will run.
2) If your client not uses PIPELINING it will never try to write another request until it receives a response. 

With this in mind it is completely expected what you see I think

**Comment by enginespot** [comment]
![stalled](https://cloud.githubusercontent.com/assets/1422439/17726806/a327b6aa-6487-11e6-9a0a-be6459785378.png)
![stalled2](https://cloud.githubusercontent.com/assets/1422439/17726823/c5bd616a-6487-11e6-82fa-75de11faacda.png)

please view the above file , the default delay time is 2 minutes , for the helloworld demo , I use thread , it is because that there is an sence that ctx.writeAndFlush may come from other thread , and maybe it will take to much time before writeAndFlush , hmm... my main question is that some of http requests stalled.

**Comment by enginespot** [comment]
@normanmaurer @maseev 
I got it , currently I am using chrome browser ,  
Chrome enforces a maximum of six TCP connections per host. If you are requesting twelve items at once, the first six will begin and the last half will be queued. Once one of the original half is finished, the first item in the queue will begin its request process.

https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/understanding-resource-timing

Thanks again.
