### ISSUE TITLE
Investigate / review Recycler usage

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#5904]
This issue is to track the investigation and review of our Recycler usage.

The Recycler was introduced as a light-weight object pool, to reduce GC pressure. We use it in various places, like pooling ByteBuf objects (not the actual memory, just the container), write tasks (When you call write(...) from outside the EventLoop) and many more.

This usage gave us a lot of trouble in the past and also users a hard time when they ended up with a lot of objects in the Reycler due writing to fast etc.

After talking with @Scottmitch we were wondering if most of our usage even make sense, as collecting short-lived objects is very fast and also "cheap" on the JDK these days.  Even worse it may hurt GC performance when running longer as we may have more objects ended up in the "old space" of the GC. 

Places that come into my mind for those short-lived object that are currently using the Recycler are:
- `ByteBuf`
- `AbstractChannelContext.WriteTask`
- `ChannelOutboundBuffer.Entry`

We should investigate if we may want to remove the `Recycler` usage for these or remove it completely.

@cconroy for example reported that he not saw any performance differences when disable the recycler via the system property.

@nmittler @Scottmitch @trustin @cconroy @buchgr @ejona86 @belliottsmith WDYT ?

**Comment by normanmaurer** [comment]
also @nitsanw @NiteshKant @mosesn

**Comment by nitsanw** [comment]
It is difficult to evaluate performance without workloads, which workloads do you test with? Since this is a GC optimization it is likely to only impact applications where the Netty garbage dominates, I don't know if these usecases are core to Netty.
As a prototype/deprecation approach perhaps start by putting it behind an option so that you can easily compare the impact.

**Comment by buchgr** [comment]
Two thoughts:

- The live times of instances of the beforementioned types is usually closely tied to the duration of requests. Usually it's a few hundred micros to millis from request to response, while usually young GCs are triggered every few hundred millis to seconds. So usually those objects should die between young GCs and thus be free to collect. I am saying usually, but obviously this is _completely_ application dependent.
However, if an application fits that description, then the question is what percentage of allocations (in bytes) per unit of time are those objects? Roughly, if you allocate `N%` more bytes per unit of time, then the time between young GCs will be `N%` shorter. The beforementioned objects might die, but lifetime of other objects might be affected and thus impact application performance negatively. Again, _completely_ depends on your application. It might make sense to measure this allocation rate in a few "typical" Netty applications and the smaller that `N` is, the higher your confidence that it will not negatively impact other Netty applications.
- It seems the sweet spot for the recycler are short-lived objects that make up a significant percentage of allocations per unit of time in applications that don't trigger full collections. If you changed the recycler to also allocate objects off heap, then those objects should not negatively affect full GCs.

FYI, we have tried to use the recycler for short-lived objects in gRPC and had worse results and made similar observations https://github.com/grpc/grpc-java/pull/2240.

**Comment by normanmaurer** [comment]
@buchgr @nitsanw I mean at smallest and safest change we could just disable the recycler by default and let users enable it when needed. Once we are sure there is no bad impact we could remove it completely.

**Comment by mosesn** [comment]
Disabling by default seems reasonable to me.  I'll see if we can see what our stuff looks like when it's disabled.

**Comment by belliottsmith** [comment]
I have to concede I was never quite sure of the value of the recycler in some places it is used.  For some of the larger objects (e.g. lists that may contain many elements), perhaps, but for very small objects...

But I recall complaints about the amount of garbage created by the recycler itself, which is a small fraction of the garbage it saved.  So I suspect there may be some unhappy campers.  I'm also not sure in what way GC characteristics have changed materially since the recycler was introduced - besides G1, GC has been fairly behaviourally consistent in Java for a long time now.

This may also be seen as a retrograde step in comparison to e.g. log4j, which has recently gone garbage free.  But IMO garbage freedom should probably be achieved by updating the API so callers supply any dynamic allocation whose lifetime they determine, and that is a whole other can of worms.

It does seem reasonable to me to disable it, and see if people complain.  The majority of users probably do not derive any benefit for the status quo.  Probably worth putting some big red flashing message in NEWS.txt, so there's nobody too taken by surprise.

**Comment by normanmaurer** [comment]
@belliottsmith yeah I think I would like to at least keep it for the `List` stuff in the codecs but thats it I think for now :)

**Comment by vkostyukov** [comment]
I've done some experiments in the past with recyclers. Disabling them completely (for all the use-cases) degraded GC times for us. I wonder if it actually makes some sense for one of its tree use cases. I'd put my money on `ChannelOutboundBuffer.Entry`.

Anyways, these experiments were done before we fixed out main GC problem so it might makes sense to do that again.

**Comment by normanmaurer** [comment]
@vkostyukov do you think you could wrote some canary with it disabled (via the system property) and report back ?

**Comment by vkostyukov** [comment]
@normanmaurer I'm happy to do that. Will run a couple of our Integ tests (an internal tool to test Finagle topologies) with recyclers disabled today or tomorrow.

**Comment by normanmaurer** [comment]
@vkostyukov thanks buddy!

**Comment by buchgr** [comment]
@normanmaurer

> @buchgr @nitsanw I mean at smallest and safest change we could just disable the recycler by default and let users enable it when needed. Once we are sure there is no bad impact we could remove it completely.

Yes, that seems like a good idea, and remove it eventually if there is no outcry from users. Is there overhead to having the recycler disabled?

**Comment by normanmaurer** [comment]
@buchgr no overhead compared with the recycler enabled. The only "overhead" you see is when you compare it with how it would be without an recycler implementation at all. Basically we could safe one field / object reference per object that supports the recycler.

**Comment by normanmaurer** [comment]
Let me close this for now as we saw the perf impact was really bad for Twitter :(
