### ISSUE TITLE
Http2Codec fails silently when the server tries to send too big headers

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5952]
When the server tries to send a response with too big headers according to the negotiated SETTINGS_MAX_HEADER_LIST_SIZE, it only half-closes and fails silently.  I think it should instead fireExceptionCaught.

**Comment by mosesn** [comment]
This is easy to reproduce.  Spin up an http/2 server, and have it respond to a request with a header of size 10K.

**Comment by mosesn** [comment]
I'm having an awful time testing this, but I think the solution is simple:

```
diff --git a/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java b/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
index 8b3ec62..24953c7 100644
--- a/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
+++ b/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
@@ -388,6 +388,7 @@ public final class Http2MultiplexCodec extends ChannelDuplexHandler {
                 promise.addListener(this);
             } else {
                 frame.streamId(streamId());
+                promise.addListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE);
             }
             writeFromStreamChannel(frame, promise, false);
         }
```

**Comment by mosesn** [comment]
@normanmaurer do you have tips for how I should test this?

**Comment by normanmaurer** [comment]
@mosesn writes usually not results in `exceptionCaught(...)` calls but should just fail the promise. Let me think a bit about this.

**Comment by mosesn** [comment]
@normanmaurer the problem I'm running into is that the promise isn't accessible.

**Comment by normanmaurer** [comment]
@mosesn yep which I think is the "core problem" and I think we need to make this happen ;)

**Comment by mosesn** [comment]
@normanmaurer should I post the diff I wrote in a comment before as a PR, or do you have another idea?

**Comment by normanmaurer** [comment]
@mosesn like I said I need to think a bit more about it. I think we need to refactor the whole child channel thing a bit to make it "better" and so allow to be notified

**Comment by mosesn** [comment]
oof, OK.  I'll just document the bug in our codebase for now.

**Comment by normanmaurer** [comment]
@buchgr @ejona86 btw if you have any "good" idea let me know

**Comment by buchgr** [comment]
If I understand correctly, this problem is solved by #5914. That is, the promise will be "accessible" on the child channel and fail with the correct error. We introduced `ChannelOutboundBuffer#steal` and https://github.com/netty/netty/pull/5914/files#diff-1467546ce755a7d28826823167febd0fR370 to fix this.

**Comment by ejona86** [comment]
This was a known deficiency caused by `ChannelOutboundBuffer`. The issue tracking it is #4941: "If we solve enough to make outbound flow control work, we should naturally end up fixing the premature child promise completion in the child's doWrite due to `ChannelOutboundBuffer`."

`steal()` or avoiding `ChannelOutboundBuffer` allows it to be resolved.

**Comment by mosesn** [comment]
OK, this makes sense to me.  @ejona86 @buchgr what do you think about cherry-picking that fix into netty so we don't have to wait on #5914?

**Comment by buchgr** [comment]
@mosesn I (as the author of that fix) am obviously fine with that :-). I believe @normanmaurer had some concerns about `ChannelOutboundBuffer#steal`.

**Comment by mosesn** [comment]
this seems to be fixed in 4.1.8, though I haven't looked into the exact mechanism.  anyway my test is no longer failing =).  I'm going to mark this as fixed, although y'all can reopen if you still have a problem with it.

**Comment by Scottmitch** [comment]
Just some bookkeeping ... The "low level API" now explicitly checks for HPACK encoder errors (mainly because SETTINGS_MAX_HEADER_LIST_SIZE is exceeded) and this is enabled by default. This is a combination of https://github.com/netty/netty/pull/6230 and https://github.com/netty/netty/pull/6284. I'm not sure what your tests look like but it is possible these changes impacted the behavior you observe.

**Comment by ejona86** [comment]
I think I've triggered this in 4.1.8 as well and didn't see problems. But I will note that since `SETTINGS_MAX_HEADER_LIST_SIZE` is advisory, I was actually surprised that netty enforced it locally. Bugs with HPACK error handling should be fixed, but if this _specific_ problem resurfaces it could be solved by removing the outbound check.
