### ISSUE TITLE
High-performance direct / heap buffer pool

### ISSUE THREAD

**Issue by trustin** [netty/netty#62]
We need a high performance direct / heap buffer pool that can be used by users.  So far, we were reluctant about exposing direct buffers to users, but with proper pooling with good documentation, it should be OK in many cases.  Heap buffer pool might also be useful when a user creates heap buffers too often because creating a byte array consumes memory bandwidth because JVM always memset the array with NUL.

However, we still need to allow people to use non-pooled heap buffers because it's often very convenient.  We can ditch non-pooled direct buffers which make all kind of troubles.

We also should give people the option to shrink or limit the pool size.  We will also have to provide some basic stats for diagnosis so that a user can determine the optimal pool size.

Since JVM does not deallocate a direct buffer timely, I'm going to allocate and deallocate it directly using `Unsafe`.  If `Unsafe` is unavailable (probably non-Sun JVM), we can always fall back to NIO's direct `ByteBuffer` and call `System.gc()` explicitly on `OutOfMemoryError`.

**Comment by ashutoshvsingh** [comment]
what is the best way to disable this malloc from happening inside of Netty. We are running IMAP server in netty and under high load we are seeing JVM getting killed because it is using too much memory. It seems that there is a leak in the way memory is either not collected properly or we are flooding ourselves reading from clients and not being able to flush. Either way we would like not to use this malloced heap. 
I did add  -Dio.netty.maxDirectMemory=0 -Dio.netty.allocator.type=unpooled this option to disable this but it is not working.

**Comment by normanmaurer** [comment]
@ashutoshvsingh you should check via a heap dump whats going on and enable leak-detection. You may not correctly release buffers back to the pool

**Comment by ashutoshvsingh** [comment]
I just want to disable the malloc. We are seeing this only when we are using this for certain load where the proxy we are writing to is slow. How do I disable this malloc. I can take GC.

**Comment by normanmaurer** [comment]
@ashutoshvsingh if this is only happening on slow writing you may write to fast ? Please open a new issue and explain what exactly you want to do and what the issue is. I think I may not fully understand the issue yet.

**Comment by ashutoshvsingh** [comment]
just opened the issue.
