### ISSUE TITLE
Unexpected behavior for MAX_HEADER_TABLE_SIZE

### ISSUE THREAD

**Issue by exell-christopher** [netty/netty#6210]
### Issue Description
I ran into some unexpected behavior when playing with MAX_HEADER_TABLE_SIZE, and the HTTP/2 Encoder/Decoder, and I figure it's worth noting.

The constant MAX_HEADER_TABLE_SIZE indicates that the largest value for the table size is the largest unsigned 32 bit int. Because of this the values that could be passed in are larger than Java int. However, when the encoder encodes the value it first casts the value to be sent to a Java int, resulting in overflow, then encodes it. This results in the receiver receiving a different value than what the sender expected to send.

On the decoder side, if you use something slightly less than Integer.MAX_VALUE, decodeULE128 fails to decode the value stating that it is too large.

While this isn't what I would consider "normal" behavior or sizes for the header table, I would expect that the MAX_HEADER_TABLE_SIZE constant should be less than the max value supported by decodeULE128 in the decoder.

### Netty version
4.1.6/4.1.7

**Comment by Scottmitch** [comment]
> This results in the receiver receiving a different value than what the sender expected to send.

Are you sure about this? I think the issue is more likely that the `decodeULE128` returns an `int`(inherited from Twitter's hpack [1]) and the integer encoding cannot completely be representing in an 31 bit unsigned value (max value documented as [2]).

I agree this is an issue though. There are some cases that can tolerate a 32 bit unsigned value and in general reporting a decompression error due to the limitations of java's signed types is misleading.

[1] https://github.com/netty/netty/commit/8accc52b0313ac4148a591881ff66a3c60ef4707#diff-265b66ff1f2ddb67210a8584c03c7e4aR543
[2] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/internal/hpack/Decoder.java#L434

**Comment by Scottmitch** [comment]
`MAX_HEADER_TABLE_SIZE` is meant to limit [SETTINGS_HEADER_TABLE_SIZE](https://tools.ietf.org/html/rfc7540#section-6.5.2) as defined by the HTTP/2 RFC and that is where the limit comes from. Just because java's int type can't represent the decoded representation doesn't mean we shouldn't support encoding it.
