### ISSUE TITLE
ResourceLeakDetector on HashWheeledTimer instance threshold too low?

### ISSUE THREAD

**Issue by jroper** [netty/netty#6225]
As I understand it, if you have 1 processor, the resource leak detector will complain if you create more than 4 instances of a HashedWheelTimer.

In the JVM world, it's becoming very easy to need more than 4 instances of this.  Consider an app that has a database driver that uses and manages its own Netty instance, a message broker client that uses and manages its own Netty instance, an HTTP client that uses and manages its own Netty instance, an HTTP server that uses and manages its own Netty instance, and metrics reporting implementation that uses and manages its own Netty instance.  These are all third party libraries, as the end user you're just the app that plumbs them together to implement your business logic, you don't have much control over how they use Netty (in particular you can't tell them to create a HashWheeledTimer with leak detection turned off), yet they each created their own HashWheeledTimer, totaling 5, and you deploy it to a single CPU server and you always get the leak detection warning.  You don't want to turn leak detection off though because that would hide legitimate leaks, but you do want to get rid of this warning.

So firstly, why is the limit of HashedWheelTimers dependent on the number of processors?  The javadocs for it say that there should only be one per app, it says nothing about needing one per processor, nothing about the number of processors would change whether there is a resource leak or not, and the practical consequence is that on developer machines, where you often have 8 or more hyperthreads in total, you'll never see the warning, but then deploy to a single CPU container in production, and you'll get it.  It would be better to have a consistent behaviour between dev and production.

Secondly, the number should be something that reflects an upper bound for the number of independent Netty instances that a single JVM classloader could conceivably have without having a misconfiguration or other problem.  I'd say this number should be at least 16, maybe 32.

**Comment by Scottmitch** [comment]
Thanks for reporting @jroper! The following is not clear to me:

- why in general is the creation of leak records is related to the lifetime of the objets being tracked [1]
- why tripping this threshold is logged as an error
- why the initial choice of `Runtime.getRuntime().availableProcessors() * 4L` was made [2]

At one point the sample rate was governed by a counter and some modulo arithmetic [3] (ignore the volatile increment bug). Now sampling is determine by a RNG distribution [4] and even if there was a nice relationship between leak record creation and object lifetime which we are tracking it is possible we could trip this threshold due to RNG "unluckiness".  I'm not convinced this type of "limiting" makes much sense in `ResourceLeakTracker` ... @trustin @normanmaurer can you help me understand?

I also noticed we retain the `String` of a leak report in a map to prevent duplicate reports [5], but we never purge this map. Granted leaks shouldn't occur in a "healthy" application, but it is surprising to me that the code responsible for detecting/reporting leaks can itself leak memory. Ideally we would purge this map at some time (with ample notification to users that duplicate reports may follow). Keep in mind that record size for a leak report is configurable and could be quite large.

[1] https://github.com/netty/netty/commit/337f5bbb8e12580e03274c15e90ccf702da6cc90#diff-e7f59893bb7f88824527d638b6cbba72R119
[2] https://github.com/netty/netty/commit/337f5bbb8e12580e03274c15e90ccf702da6cc90#diff-35b0b48bbbd268807be752bdd8b28a5dR88
[3] https://github.com/netty/netty/commit/337f5bbb8e12580e03274c15e90ccf702da6cc90#diff-e7f59893bb7f88824527d638b6cbba72R96
[4] https://github.com/netty/netty/commit/42fba015ce82ab4ab30e547c888db82fe74094e9#diff-e7f59893bb7f88824527d638b6cbba72R213
[5] https://github.com/netty/netty/commit/65b522a2a75c78c977a65e15663509509b5f12e0#diff-e7f59893bb7f88824527d638b6cbba72R209

**Comment by johnou** [comment]
@jroper thanks for opening this, we are running into the same problem with normal usage of our application (I think during shutdown) we see messages like this.. 

```text
2017-01-17 09:34:23,096 ERROR [main] (io.netty.util.ResourceLeakDetector) LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.
```

**Comment by normanmaurer** [comment]
> why in general is the creation of leak records related to the lifetime of the objets being tracked [1] ?

Honestly I have no idea why @trustin did it this way... @trustin can you comment ?

> why tripping this threshold is logged as an error ?

What else would you do ? Or do you think error level is too high ?

> why the initial choice of Runtime.getRuntime().availableProcessors() * 4L was made [2]

Again no idea... @trustin any comments ?

> At one point the sample rate was governed by a counter and some modulo arithmetic [3] (ignore the volatile increment bug). Now sampling is determine by a RNG distribution [4] and even if there was a nice relationship between leak record creation and object lifetime which we are tracking it is possible we could trip this threshold due to RNG "unluckiness". I'm not convinced this type of "limiting" makes much sense in ResourceLeakTracker ... @trustin @normanmaurer can you help me understand?

Honestly I think we could just remove this limit if we like, but still not break API ;)

> I also noticed we retain the String of a leak report in a map to prevent duplicate reports [5], but we never purge this map. Granted leaks shouldn't occur in a "healthy" application, but it is surprising to me that the code responsible for detecting/reporting leaks can itself leak memory. Ideally we would purge this map at some time (with ample notification to users that duplicate reports may follow). Keep in mind that record size for a leak report is configurable and could be quite large.

Yeah in practice this should be ok as it should not grow a lot. That said limit it somehow makes sense imho. Let me provide a PR for this...

**Comment by Scottmitch** [comment]
> What else would you do ? Or do you think error level is too high ?

I wanted to see what the rational for this was but my thought process is to just remove this entirely. From what I'm seeing there isn't a relationship between leak record creation and object lifetime being tracked by the leak record, and therefore I would like to remove the mechanism (`maxActive`) all together.

> Honestly I think we could just remove this limit if we like, but still not break API ;)

Unless there is some way to justify `maxActive` making sense I would vote for breaking the API here. Seems like a concept that doesn't make sense, and I would prefer to be overt about the change as opposed to silently deprecating and folks who may be assuming a certain functionally potentially missing the change.

**Comment by normanmaurer** [comment]
> Unless there is some way to justify maxActive making sense I would vote for breaking the API here. Seems like a concept that doesn't make sense, and I would prefer to be overt about the change as opposed to silently deprecating and folks who may be assuming a certain functionally potentially missing the change.

I disagree... We should not break the API, but just ignore it IMHO

**Comment by Scottmitch** [comment]
Agree to disagree on the API change. However I think we agree the `maxActive` concept and related code doesn't make sense and can be removed?

**Comment by normanmaurer** [comment]
@Scottmitch yes I think we do... but let give @trustin a bit of time to chime in as he wrote it.

**Comment by trustin** [comment]
I have no strong opinion on this. I felt it's not very natural for `ResourceLeakDetector` to handle two cases (leak detection and too many timer instances) together at the time of writing but I just left it as it is because they were sharing some common logic and I didn't have much interest improving it further at that moment (usual priority thing, you know.)

> why tripping this threshold is logged as an error ?

Because I thought it is very very likely that a user made a mistake of creating too many timers, which doesn't make sense and defeats the whole purpose of using Netty - why create such many timers when you have much smaller number of I/O threads? However, I agree that it can be a false alarm and we may need to increase the threshold.

> why the initial choice of Runtime.getRuntime().availableProcessors() * 4L was made

It's twice of the default number of I/O threads. As mentioned above, I thought it doesn't make much sense to crease such many number of hashed wheel timers, but I agree that this can be controversial.

Also, there were quite a few questions about Netty creating too many timers, although we don't see such questions very often these days. Logging at ERROR level and giving the user some hints in the log message might have helped people figure out what they have done wrong.

So, my suggestion is to raise the threshold rather than removing the check completely. +1 as well for refactoring this so that `ResourceLeakDetector` does one job it's good at.

**Comment by jroper** [comment]
I think it makes sense to have the check in there, in our support channels it is incredibly common to see people creating resources that create threads and not cleaning them up, often the issue isn't exposed until they deploy to production and their server runs out of memory.  The javadocs for HashedWheelTimer explains the situation exactly - saying it's a common mistake to instantiate one per request rather than sharing them.  If developers could be notified in development that they are creating too many threads, then that would save a lot of heartache for everyone involved, so I think this is a great feature of Netty, and I wish more libraries would do this.  I just think the default threshold is too low.  It could even be something as high as 256 - if you're creating one per request, it won't take long for you to exceed 256 timers, so that's low enough to detect a leak, meanwhile I can't imagine a legitimate reason to create 256 in one classloader, so it's definitely high enough to not get in the way of legitimate usage.

@Scottmitch with regards to leak records tracking the lifetime - do you mean to say that it should increment the tracking on instance creation, but not decrement when the object is closed?  There's a good reason to bind it to lifetime, and that's testing, often tests will start many short lived servers, we definitely do this a lot in Play, and so you want the instances to be decremented when the object is closed.

**Comment by Scottmitch** [comment]
> So, my suggestion is to raise the threshold rather than removing the check completely

If the intention is to limit the amount of `HashedWheelTimers` (presumably because each one creates its own thread) then I would prefer to explicitly do that in `HashedWheelTimers` instead of trying to build something into `ResourceLeakDetector` just because each `HashedWheelTimers` happens to use a single leak record. As previously stated this limit doesn't make sense in `ResourceLeakDetector`  because there is no relationship between leak record creation and the lifetime of objects which are already being traced with leak records.  The existing `maxActive` may provide some utility in the case of single leak records which generally are long lived, but in the general case the concept starts to break down.

For example I prefer to put a static counter in `HashedWheelTimers` which counts the number of instances and generates a warning at some threshold. We can use the `finalizer` method (gasp!) to decrement the count. Since it is generally not expected many of these instances will exist, and they generally live for a long time, using a `finalizer` *shouldn't* be an issue.
