### ISSUE TITLE
Support for MQTT v5

### ISSUE THREAD

**Issue by andsel** [netty/netty#6285]
Is there any planning to support MQTT v5 on netty-codec-mqtt? Do you need an hand.
Thanks.
 Andrea

**Comment by normanmaurer** [comment]
@andsel we love contributions. as far as I know no-one is working on it atm

**Comment by andsel** [comment]
Great @normanmaurer I'll start to implement, because I need into Moquette and I think it could be useful to others :-)

**Comment by mtaylor** [comment]
@andsel Did you make any progress with this?  Is there something I can do to help out?

**Comment by andsel** [comment]
@mtaylor I've read the specification, and I have an idea on how to implement the new features introduced in the protocol.

The v5 introduce a type of fields on each message, I was just thinking on how to implement this in existing implementation inside Netty. I find 2 possible ways:
- add these collection of attributes to every message, but this drives me to a series of "if" in the codec part
- use the same technique used in WebSocket, there is a ChannelHandler that determine the version of the protocol, and if it found v5 it reshape the pipeline with the codecs for MQTT v5 else use the existing

What do you think about this?

**Comment by Sammers21** [comment]
Is a work still in progress? I am interested in working on it and implement as soon as possible.

**Comment by Sammers21** [comment]
@normanmaurer, what do you think?

**Comment by Sammers21** [comment]
@normanmaurer ping?

**Comment by AlexBischof** [comment]
@normanmaurer Do you see a way to get PR above back to life? I would also offer to help.

**Comment by normanmaurer** [comment]
This was moved to an alternative project

**Comment by paul-lysak** [comment]
@normanmaurer - Are there any plans to get MQTT v5 support eventually? The spec is officially released more than a year ago and is being widely adopted (https://en.wikipedia.org/wiki/Comparison_of_MQTT_implementations#Protocol_support).
I can pick where @andsel  has left and do the changes to meet your standards. Should I create a new issue to track it or you can re-open this one?

One thing I was wondering about - is `codec-mqtt` actively maintained? Or is it abandoned? Because handling of the previous PR isn't what one would expect from the alive project - just hanging there over a year without any comments.

**Comment by chenzhiguo** [comment]
What happened about `codec-mqtt`? Why cant support mqttv5?
