### ISSUE TITLE
content-aware leak detection for unpooled composite bytebufs

### ISSUE THREAD

**Issue by dschobel** [netty/netty#6431]
I'm pondering a `CompositeByteBuf` implementation that makes leak detection depend not only on the `disableLeakDetector` param but also on whether the constituent buffers are leak-aware.

The problem I'm facing is that I want to ref-count + enable leak detection for direct bytebufs while still allowing unpooled heap bytebufs to leak. This works well enough with configuring the UnpooledByteBufAllocator since it never wraps heap buffers in leak detection, but I've run into [UnpooledByteBufAllocator#compositeHeapBuffer](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/UnpooledByteBufAllocator.java#L75) which is producing leak aware composite bytebufs at a point in the application where I can ensure that only unpooled heap byte bufs are being aggregated. The result is false positives in leak detection.

Before I dive in I wanted to check that I'm not missing an existing solution and also to see if there's interest in a PR since I understand the finagle use-case might be fairly fringe.

### Netty version
4.1.8

**Comment by normanmaurer** [comment]
@dschobel so you ask if we are interested in be able to create `CompositeByteBuf` which are not leak ware ?

**Comment by dschobel** [comment]
@normanmaurer kind of. The simplest thing to do would be to create a `CompositeByteBuf` that ignores the `disableLeakDetector` param and never wraps itself in the leak detection class. That works for us because we can reason about what kind of buffers we have in the application.

But what I'm proposing to upstream is a more general solution, a "smart" `CompositeByteBuf` that waits until it contains a `LeakAwareByteBuf` component to start leak tracking.

**Comment by dschobel** [comment]
in code (sorry about the scala):

```scala
ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.PARANOID)

val alloc = new UnpooledByteBufAllocator(
  /* preferDirect */ false,
  /* disableLeakDetector */ false
) 
val a = alloc.heapBuffer(10) // non-leak tracking buffer
val b = alloc.heapBuffer(10) // non-leak tracking buffer

val comp = alloc.compositeBuffer(2) // `comp` now tracks reference leaks and reports a leak if it is not released.
```

what I'm proposing is that `comp` in the example above looks at the components added via `addComponent` before deciding about leak tracking

**Comment by Scottmitch** [comment]
I'm not sure how generally useful this will be and I have concerns about the overhead associated with tacking this. Do you have a plan on how to implement this feature/change? Is this feature enabled at the allocator level ... so the allocator can be configured to return a "smart" `CompositeByteBuf` or the "existing" `CompositeByteBuf`?

**Comment by dschobel** [comment]
I don't think there's need to explicitly configure unless there are non-trivial performance implications in which case I'd say it's not worth doing. If there are major performance issues lurking, I don't see them. I think the implementation amounts to an instanceOf check in `addComponents` to test for leak aware components and a bit which holds the state for whether we're leak tracking or not.

In the case where the components are strictly *not* leak-tracking, then this implementation does less work by making the tracking operations no-ops.

I think this change would also make the semantics of the unpooled allocator more consistent by enforcing the view that a composite unpooled heap buffer w/ non-leaking components is semantically equivalent to a single unpooled heap buffer, with neither constituting a resource leak when unreleased.

**Comment by Scottmitch** [comment]
What is the expected behavior in the following situation:

```java
ByteBuf b1 = ...; // leak aware
ByteBuf b2 = ...; // not leak aware
compositeBuffer.add(b1); // composite is now leak aware
compositeBuffer.add(b2);
// Assume b1's bytes are consumed and it is removed from compositeBuffer
// so only b2 is contained ... is compositeBuffer still leak aware?
// if so what type of data structure will be used to track which buffers contribute to
// the leak detector?
```

> make the semantics of the unpooled allocator more consistent 

Currently a `CompositeBuffer` is treated as just a regular buffer and leak detected in the same manner as any other buffer (w.r.t to leaks). It *may* not have any "direct memory" inside, but in many situations `CompositeBuffer` is passed to interfaces that accept `ByteBuf`. and the implementations of the interface should generally not rely upon the buffer being safe to not release (because a different buffer may be passed in). So in this sense ... a leak is a leak. If you are sure that leaks are "OK" in your use case (heap buffers, or you are OK with relying on GC for direct memory) I wonder if just not wrapping `CompositeByteBuf` in a "leak aware buffer" is sufficient and more consistent ... wdyt? You can accomplish this with a custom `ByteBufAllocator` relatively easily.

**Comment by dschobel** [comment]
> Assume b1's bytes are consumed and it is removed from compositeBuffer so only b2 is contained ... is compositeBuffer still leak aware?

I think it would have to be until someone calls .removeComponent on b1. By analogy consider that a composite buffer wrapping a direct buffer doesn't automatically release the direct component after reading all of its data (which is a bad idea since reader indices are mutable anyway).

> "So in this sense ... a leak is a leak."

 That's valid but I'd argue that's not the behavior of the unpooled byte buffer allocator today precisely because on heap buffers refuse to be leak tracked.

My reading of the semantics is: "irrespective of refcounts, netty's not going to trigger leak alerts for resources which we can't release deterministically and the gc can handle in any event".

As for datastructures, I think a counter of leakaware components is sufficient. When that count is zero, all leak tracing is a noop.

**Comment by Scottmitch** [comment]
Reference count ownership is transferred to the `CompositeByteBuf` as soon as `add` is called [1]. [discardReadComponents](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1569), [discardReadBytes](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1605), and [discardSomeReadBytes](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1922) provide the opportunity to release components which have been consumed. These methods are commonly called in handlers which use `CompositeByteBuf` for aggregation purposes.

In terms of semantics the behavior you described is implemented as a "best effort" and mostly done for efficiency reasons IIUC ( @normanmaurer - wdyt ). Because buffer types and allocators can change globally relatively easily I'm not sure its a good idea to ignore refcounts in general (unless your allocator is careful to only allocate heap based buffers ... which Unpooled doesn't).

> As for datastructures, I think a counter of leakaware components is sufficient. When that count is zero, all leak tracing is a noop.

What about adding a composite to a composite?

```java
CompositeByteBuf outer = ...;
CompositeByteBuf inner = ...;
inner.addComponent(/*direct buffer*/);
// inner leak count = 1 -> now leak detected
inner.addComponent(/*heap buffer*/);
outer.addComponent(/*heap buffer*/);
outer.addComponent(inner);
// ? outer leak count = 1 -> now leak detected ?

inner.skipBytes(inner.capacity());
inner.discardReadComponents();
// inner is now empty, inner leak count = 0 -> now not leak detected
// ? how do you update outer's leak count ?
```

Also keep in mind that leak detection is thread safe so swapping between leak and non-leak will need to be carefully coordinated.

I'm still not convinced there is enough value to implement this in the core and make it the default behavior. Can you explain why using a custom allocator that never allocates any buffers with leak detection is not a viable solution in your case?

[1] https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L132

**Comment by dschobel** [comment]
I think the bookkeeping needed to support the the discard* methods and nested `CompositeByteBufs` would largely looks like what exists for making ref-counts coherent in both cases.

> Can you explain why using a custom allocator that never allocates any buffers with leak detection is not a viable solution in your case?

Yep, we certainly could solve this with custom allocators but I wanted to see whether you were interested in the composite buf change.

Stepping back, I think the fundamental issue is the difference between the position that "a reference leak is always a bug and our leak detector yells at you in all cases (ignoring unpooled onheap)" vs "the leak detector yells at you for leaks that matter in practice".

**Comment by normanmaurer** [comment]
@dschobel generally speaking I think in a normal Netty app fail to release a buffer correctly should always reported as this makes it possible to basically switch from allocating heap to direct buffers and still be sure nothing leaks. So to make it short I am kind of thinking what you want to do may be fine for Finagle (as you know what you are doing etc) but not sure if this is really something that i useful for most people and may even be dangerous.

**Comment by dschobel** [comment]
it's only dangerous if the implementation is buggy :)  in any event I'll fix it locally. thanks for discussion guys.
