### ISSUE TITLE
WeightedFairQueueByteDistributor may not write all pending bytes when testing HTTP/2 with Chrome.

### ISSUE THREAD

**Issue by durigon** [netty/netty#6621]
### Expected behavior
WeightedFairQueueByteDistributor write all pending bytes when testing HTTP/2 with Chrome.

### Actual behavior
WeightedFairQueueByteDistributor does not respond to all images when testing with Chrome, finally Chrome can not display for some images.
On the contrary, All images were displayed when testing Firefox.

### Steps to reproduce
1. Run the HTTP / 2 Tiles example(io.netty.example.http2.tiles).
2. Connect to https://localhost:8443 using the Chrome browser.
3. Press Ctrl+F5

### Netty version
netty-4.1.9.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
#uname -a
Linux 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#cat /etc/redhat-release 
CentOS release 6.8 (Final)

**Comment by durigon** [comment]
If you change WeightedFairQueueByteDistributor to UniformStreamByteDistributor, UniformStreamByteDistributor writes all pending bytes when testing HTTP/2 with Chrome.

**Comment by normanmaurer** [comment]
@nmittler @ejona86 can you check ?

**Comment by ejona86** [comment]
@normanmaurer, I reproduced the hang on master. And it does appear `UniformStreamByteDistributor` doesn't have the same failure. I can't reproduce the problem on v4.1.8, but I can on v4.1.9, which is interesting because nothing really changed in either the weighted distributor or the remote flow controller.

**Comment by ejona86** [comment]
I'm mistaken. Commit 3482651 happened between the two and have verified it introduced the bug. That should help in figuring out what's broken.

**Comment by normanmaurer** [comment]
@ejona86 so you will take a look ?

**Comment by normanmaurer** [comment]
Also @Scottmitch ....

**Comment by ejona86** [comment]
@normanmaurer, yeah, I'll still investigate more. I don't get much work done on Tuesdays, so tomorrow is when I'll probably be able to get back to it.

**Comment by ejona86** [comment]
I tracked the problem down to an interaction with `maxStateOnlySize`. A high value (~195) does not trigger the bug. A medium value seems to trigger it less. And 1 triggers it very quickly. 0 doesn't have any issue.

I also know that the streamableBytes on many streams is incorrectly 0. I think this was caused by child/pseudoTimeQueue tree corruption, because it seems there were large trees that weren't descendant from the connection.

It seems the problem is due to a bug in updateDependencyTree, where if it doesn't find the parent it creates new State for it, but it doesn't give that State a parent. This seems to fix it (more testing needed):
```java
@@ -229,6 +229,10 @@ public final class WeightedFairQueueByteDistributor implements StreamByteDistrib
         State newParent = state(parentStreamId);
         if (newParent == null) {
             // If there is no State object that means there is no Http2Stream object and we would have to keep the
             // State object in the stateOnlyMap and stateOnlyRemovalQueue. However if maxStateOnlySize is 0 this means
             // stateOnlyMap and stateOnlyRemovalQueue are empty collections and cannot be modified so we drop the State.
             if (maxStateOnlySize == 0) {
                 return;
             }
             newParent = new State(parentStreamId);
             stateOnlyRemovalQueue.add(newParent);
             stateOnlyMap.put(parentStreamId, newParent);
+            // Only the stream which was just added will change parents. So we only need an array of size 1.
+            List<ParentChangedEvent> events = new ArrayList<ParentChangedEvent>(1);
+            connectionState.takeChild(newParent, false, events);
+            notifyParentChanged(events);
         }
```

Although I'm becoming more familiar with the code, I am not fully up-to-speed. I'll see if I can turn this into a PR.

**Comment by Scottmitch** [comment]
thanks for looking into this @ejona86 ... this does seem like a bug but maybe in other areas too ... I can take a stab at a PR

**Comment by Scottmitch** [comment]
good find ... after looking a bit more it seems to be the only place where this bug occurs. We should be able to share code with [1] too. Also I need to review when we prematurely exit if the parent's state object cannot be found ... I'm concerned we may not write to the child stream if it is in the active state ... I need to investigate more.

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/WeightedFairQueueByteDistributor.java#L125

**Comment by Scottmitch** [comment]
> Also I need to review when we prematurely exit if the parent's state object cannot be found ... I'm concerned we may not write to the child stream if it is in the active state ... I need to investigate more.

Just to close the loop ... we are OK here. The state only map is just used when there is no stream object. If there is a stream object we keep track of the priority in the stream and so it is OK to bail out early if no state exists for the parent stream and we don't track any "priority only state" ... because it will not impact the priority. I will add a unit test to demonstrate the behavior is correct.
