### ISSUE TITLE
Support DGRAM unix domain socket

### ISSUE THREAD

**Issue by kghost** [netty/netty#6737]
Currently only STREAM unix domian socket is supported, it would better to support DGRAM unix domain socket.

**Comment by normanmaurer** [comment]
@kghost we love contribution.s

**Comment by kghost** [comment]
Looking into it

**Comment by Scottmitch** [comment]
> better to support DGRAM unix domain socket.

Can you provide some justification for this statement? Why is it "better"?

**Comment by shakuzen** [comment]
To add a concrete use case for this, in Micrometer we support publishing metrics to dogstatsd (Datadog-flavor of StatsD daemon) over UDP using reactor-netty currently. We have had requests to support publishing metrics to dogstatsd via unix domain sockets in micrometer-metrics/micrometer#792, and I was excited to see that reactor-netty has support for unix domain sockets built on top of the support in netty for it. However, the netty support is limited to stream domain sockets and dogstatsd is listening on a datagram domain socket. Since we are already using reactor-netty for publishing statsd metric lines, it would be advantageous to use a built-in netty feature to also support publishing on (datagram) unix domain sockets.

**Comment by normanmaurer** [comment]
@shakuzen I am currently super busy but I would be happy to review a PR and provide feedback. So if you want to give it a go I am happy to help

**Comment by violetagg** [comment]
@shakuzen @normanmaurer I'm gonna look at this and will try to provide a PR for a discussion.

**Comment by violetagg** [comment]
I opened a PR #11423 for a discussion. I'll appreciate your feedback.
