### ISSUE TITLE
ByteBuf's retainedSlice affects refCnt based on the ByteBufAllocator used

### ISSUE THREAD

**Issue by AshwinJay** [netty/netty#6776]
### Expected behavior
`ByteBufAllocator.retainedSlice()` affects `refCnt()` inconsistently between `UnpooledByteBufAllocator` and `PooledByteBufAllocator`. This causes tests to break where reference counts of the bytebufs are being verified for leaks and tested against various allocators.

### Actual behavior
Here, `bb2 = bb1.retainedSlice()`. See attached JUnit test to reproduce the issue.
```
unpooled-direct(io.netty.buffer.UnpooledByteBufAllocator false)

BB1 new:                         1
BB1 after retained slice of BB2: 2
BB2 new:                         2
BB1 after release:               1
BB2 after BB1's release:         1
BB1 after everything released:   0
BB2 after everything released:   0

unpooled-heap(io.netty.buffer.UnpooledByteBufAllocator false)

BB1 new:                         1
BB1 after retained slice of BB2: 2
BB2 new:                         2
BB1 after release:               1
BB2 after BB1's release:         1
BB1 after everything released:   0
BB2 after everything released:   0

pooled-direct(io.netty.buffer.PooledByteBufAllocator true)

BB1 new:                         1
BB1 after retained slice of BB2: 2
BB2 new:                         1
BB1 after release:               1
BB2 after BB1's release:         1
BB1 after everything released:   0
BB2 after everything released:   0

pooled-heap(io.netty.buffer.PooledByteBufAllocator true)

BB1 new:                         1
BB1 after retained slice of BB2: 2
BB2 new:                         1
BB1 after release:               1
BB2 after BB1's release:         1
BB1 after everything released:   0
BB2 after everything released:   0
```

### Steps to reproduce
See attached unit test - [RetainedSliceTest.java.txt](https://github.com/netty/netty/files/1024514/RetainedSliceTest.java.txt).

### Netty version
`netty-buffer-4.1.5.Final.jar`

### JVM version
`jdk1.8.0_121`

### OS version
MacOS Sierra 10.12.4

**Comment by NiteshKant** [comment]
Looks like the cause of this behavior is that `PooledByteBuf.retainedSlice()` always has the ref count as 1. Potentially due to [this line](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/AbstractPooledDerivedByteBuf.java#L66).

It looks like a bug to me. @Scottmitch may have a better idea whether it is as expected or not.

**Comment by Scottmitch** [comment]
The fact that reference count behavior is different between allocators for `retained*` operations is not a bug, and is intentional behavior. The API contract of `ByteBuf` does not say anything about reference counts of derived buffers being shared with there parent. We take advantage of this in the case of `PooledByteBufAllocator` to maintain a pool of derived buffers. If you want to validate reference counts in your unit tests this validation should check that reference counts go to zero all derived/parent buffers are released, and not focus on the intermediate reference counts of derived objects.
