### ISSUE TITLE
Support Brotli

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6899]
We currently don't support Brotli decompression/compression but this would be a useful feature and we should add support for it.

**Comment by Scottmitch** [comment]
@NSProgrammer - You opened in issue in the past which mentioned Brotli [1]. Do you have support for it and would you be interested in submitting this to Netty?

[1] https://github.com/netty/netty/issues/6784

**Comment by slandelle** [comment]
@Scottmitch I was under the impression that Brotli was slow on compressing and fast on decompressing, so the typical use case was to compress offline and serve already compressed content, not compress on the fly. I guess that's what @NSProgrammer was trying to achieve.

I'm not sure it's worth trying to support on the server/compression side. On the contrary, it could be interesting to support on the client/side decompression. In the Java world, there's currently 2 decompressors:
* [Official Java decoder](https://github.com/google/brotli/tree/master/java/org/brotli/dec) implementation
* [JBrotli](https://github.com/MeteoGroup/jbrotli) JNI wrapper

Last time I checked, the former was nowhere as fast as the latter. I guess it's intended for Android. Then, the former is JNI based, so here be dragons...

Note the latest cool kid in the compression game is FB's [Zstandard](https://github.com/facebook/zstd).

**Comment by Scottmitch** [comment]
I clarified the title. The intention was to investigate supporting Brotli decompression/compression and not just compression.

However these things generally depend upon the content being compressed and the configuration of the compressor. Certain configuration levels of Brotli can actually provide a favorable throughput/compression ratio compared to gzip [1]. As always the advise would be "benchmark for your data", but before benchmarking can be done we must first support Brotli.

[1] https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html

**Comment by NSProgrammer** [comment]
I'm going to defer to Ben Leib for Netty integration convos (I can't find his github account to @ mention him).

I will say that we've measured a bunch and do think that with the 12 levels of compression for brotli that some of those levels are efficient enough to run on-demand in servers with native code (Java implementations just can't hack it).   There are definitely diminishing returns on smaller payloads and it is prudent to test at which point Brotli should kick in over gzip.  gzip/deflate are fast, clearly, but for large enough payloads, the latency of encoding is surpassed by the reduction in payload translating fewer TCP window round-trips needing to be sent.

**Comment by bgleib** [comment]
(Ben Leib here)

We have implemented both Brotli and Zstandard compression of on-demand REST API responses, but we ended up doing it at a higher level in the stack. This was faster for me largely just due to my being less familiarity with Netty code, but also because as @NSProgrammer mentions the Java implementation was too slow and pulling the JNI implementation into Netty looked iffy.

FWIW we have found that for larger payloads (over about 10kB), the payload size reduction from using Brotli or Zstandard instead of gzip outweighed the longer compression time in terms of improving client-perceived latency, especially over slower networks.

Our benchmarking also made Brotli look slightly more performant than Zstandard without a dictionary for an equivalent compression ratio, but YMMV.

**Comment by Scottmitch** [comment]
thanks @bfritz ... is there any interest in doing this at the Netty level and making a PR contribution?

**Comment by normanmaurer** [comment]
@bfritz ping...

**Comment by bfritz-zed** [comment]
@normanmaurer Did you mean @bgleib ?

**Comment by bfritz** [comment]
@normanmaurer did you mean @bgleib ?

**Comment by raulk** [comment]
Would this be a good first issue for new Netty contributor? If yes, @normanmaurer could you give a little bit of guidance of what you'd expect?

**Comment by idelpivnitskiy** [comment]
Hi @raulk,
It definitely could be, because I started my contributions to netty from compression codecs.
You should choose a java library which does compression/decompression (one of mentioned above or another) and use it for implementation of `ByteToMessageDecoder` and `MessageToByteEncoder`.
You could use this PRs as examples:
https://github.com/netty/netty/pull/2654
https://github.com/netty/netty/pull/2739
https://github.com/netty/netty/pull/2755
https://github.com/netty/netty/pull/2610
https://github.com/netty/netty/pull/2576

Or any other compression codec. All of them are located in `netty-codec` module, `io.netty.handler.codec.compression` package.

**Comment by hyperxpro** [comment]
I'd like to add support for Brotli. Is it fine to use third-party dependency?

**Comment by normanmaurer** [comment]
@hyperxpro as long as its optional yes.

**Comment by idelpivnitskiy** [comment]
@hyperxpro and as long as its license allows it (compatible with Apache 2.0)
