### ISSUE TITLE
StackOverflowerror while using Netty v4.1.5+ with Spring

### ISSUE THREAD

**Issue by abhijith-prabhakar** [netty/netty#6931]
Please follow this thread to get more info
http://activemq.2283324.n4.nabble.com/Artemis-v2-1-Spring-MessageListener-Netty-StackOverflow-td4728139.html

### Minimal yet complete reproducer code (or URL to code)
Since this is happening only on Solaris can't give a test code.

### Netty version
4.1.5+

### JVM version (e.g. `java -version`)
JDK8u121

### OS version (e.g. `uname -a`)
SunOS myhost 5.10 Generic_Virtual i86pc i386 i86pc [Solaris VM]

**Comment by mbukosky** [comment]
+1

**Comment by Scottmitch** [comment]
If I'm following the SO thread correctly the diagnosis seems to imply that the issue lies with the usage of `PlatformDependent.newConcurrentHashMap` [1]? Can you produce a unit test involving this collection (or any other minimal reproducer) which fails unexpectedly on your platform? I don't even see any Netty methods in the stack traces you provided.

Note that [PlatformDependent.newConcurrentHashMap](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L315) just returns `java.util.concurrent.ConcurrentHashMap`.

[1] http://activemq.2283324.n4.nabble.com/Artemis-v2-1-Spring-MessageListener-Netty-StackOverflow-tp4728139p4728147.html

**Comment by slandelle** [comment]
@abhijith-prabhakar Your stacktrace doesn't look like an infinite loop. Isn't it just that stack size is too small? Have you tried increasing Xss?

**Comment by abhijith-prabhakar** [comment]
Is there any preferred way to give a test case?  I am thinking of just giving a vagrant file and write a simple spring boot app to replicate.  

@slandelle The memory is 2G which I thought should be sufficient.  I do see infitine loop trying to load same class.  May be I am missing something.

@Scottmitch  It is starting from `io.netty.util.AttributeKey.valueOf()` [1]  method.

[1] https://github.com/apache/activemq-artemis/blob/master/artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java#L137

**Comment by slandelle** [comment]
> The memory is 2G which I thought should be sufficient.

This is your total heap size. It has nothing to do with your stack size, which is controlled by the Xss JVM option.

> I do see infitine loop trying to load same class.

Where do you see that? It looks to me your Thread was able to reach `ZipCoder` but then hit your configured Xss.

Try increasing your Xss.

**Comment by Scottmitch** [comment]
> Is there any preferred way to give a test case?

If it is self contained you can paste it in this issue. If not just create a minimal java project, put it on GitHub, and provide a link in this issue. However before you do this please try increasing [Xss](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html) as recommended by @slandelle ... looks like most of the stack trace is in the class loader.

**Comment by abhijith-prabhakar** [comment]
It worked when we increases Xss to 1024 from 256.  Thanks for the quick help.  Will close this issue if you guys are fine with it.

**Comment by normanmaurer** [comment]
Thanks closing :)
