### ISSUE TITLE
direct memory leak

### ISSUE THREAD

**Issue by MedicOP** [netty/netty#7123]
### Netty version
4.1.13-Final

### JVM version (e.g. `java -version`)
1.8.0_144"

### OS version (e.g. `uname -a`)
CentOS 6.8

### Screenshot of YourKit profiler:
![screenshot_1](https://user-images.githubusercontent.com/18251099/29432504-3d944fbc-839c-11e7-8a41-595739643e7c.png)

Memory snapshot shows 27 million instances of ChannelOutboundBuffer$Entry. GC path points it to being a Netty issue?

Heap size was only 6.1GB while this was taken, but actual memory usage according to ```top``` was over 21GB

The program I'm using is https://github.com/SpigotMC/BungeeCord

**Comment by Scottmitch** [comment]
This typically means you aren't applying back pressure and are writing faster than your peer is reading.

**Comment by Janmm14** [comment]
@Scottmitch What is back pressure? flush()?

**Comment by maseev** [comment]
@MedicOP, @Janmm14 Back pressure means that you have to stop sending data (and, probably, stop reading but it again depends on your application protocol) if your peer can't keep up with your message rate.

Basically, it means that your server sending data faster than a client can read and process. Because of that you fill your TCP SO_SNDBUF pretty quickly and start queuing messages.

Instead of that, you have to apply some back pressure technique. You can check whether or not you can send the message "right away" without putting it into a queue by using the following [method](http://netty.io/4.0/api/io/netty/channel/Channel.html#isWritable--). If it returns false you, in most situations, have to stop reading by turning the autoRead option to false:

```java
ctx.channel().config().setAutoRead(false)
```

You should also override this [method](http://netty.io/4.0/api/io/netty/channel/ChannelInboundHandler.html#channelWritabilityChanged-io.netty.channel.ChannelHandlerContext-) to check whether or not the channel's writability status has changed. If it's changed (meaning channel.isWritable() returns true) you have to turn autoRead option to true.

Hope this helps

**Comment by Janmm14** [comment]
An attempt was made by the owner of the project to fix this issue.
I guess this can be closed.
If anyone is interested into what needs to be changed, here is the commit: https://github.com/SpigotMC/BungeeCord/commit/bd5a7e5b26b698c57e6f99933452bfc0659269f9
