### ISSUE TITLE
Mark transport-rxtx as `@deprecated`

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#7199]
https://github.com/netty/netty/pull/7198 just reminded me that I wanted to bring up the topic of mark transport-rxtx as `@deprecated` for some time. 

This is mainly driven because I think there is really no-one that maintain this one and there is no easy way for us to even test it. I think we should better concentrate and spend our time on the "real" core transports that are part of netty.

@Scottmitch @ejona86 @trustin @carl-mastrangelo WDYT ?

**Comment by carl-mastrangelo** [comment]
I don't believe Google is using it.  No concerns here.

**Comment by ejona86** [comment]
Sounds fine to me. Searching around it seems like there may be some small projects using it on the Raspberry Pi or to talk to a wireless modem. They probably wouldn't be served fine using RXTX directly (says the person who hasn't looked at RXTX at all).

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7200

**Comment by chrisdutz** [comment]
Hi,

I'm part of the Apache PLC4X (incubating) (http://plc4x.apache.org) project and we're currently implementing more and more industrial protocols (mainly ip based, but not exclusively). The Modbus protocol is now the first protocol we are implementing where the TCP version is just another layer on top of the old serial protocol. My first idea was to simply use Netty RxTxChannel and now read that's deprecated. Which path should I follow in order to implement the serial version of the driver?

Chris

**Comment by normanmaurer** [comment]
@chrisdutz I guess the answer would be to implement your own `Channel` or fork what we have and maintain it. We just have not the expertise and time to maintain it anymore.
