### ISSUE TITLE
How To Upgrade Netty into a VPS

### ISSUE THREAD

**Issue by KiritoKun90** [netty/netty#7273]
How can I upgrade the latest version of netty into my vps so I can try to fix an old "issue"?
Didn't find any tutorial on internet

**Comment by johnou** [comment]
Probably because Netty isn't something you install or upgrade on a VPS, it is an event-driven asynchronous network application framework used in other applications, based on your issue history I am going to go out on a limb and guess you are referring to BungeeCord.. If your VPS provider installed BungeeCord for you, you will need to contact them for support wrt updating BungeeCord or the BungeeCord forums etc.

**Comment by KiritoKun90** [comment]
I installed BungeeCord into the VPS by myself. So what can I do to upgrade it?

**Comment by KiritoKun90** [comment]
Sorry first time for me and I dunno what should I do.. I didn't found any information about it around the web

**Comment by johnou** [comment]
It entirely depends on how Netty was bundled with the application, if it's shaded, you'd probably need to fork the project and build it yourself from source after bumping the Netty version, if it's in a "libs" or other folder which is on the application classpath you might be able to monkey patch it by dropping in replacement jars.

Before going to the trouble of trying to update Netty you should first verify what version of Netty the application has and also check if there is a newer release of the software you want to run (some tutorials might have links to old version).

**Comment by normanmaurer** [comment]
@KiritoKun90 if its part of `BungeeCord` you should ask them how to upgrade it (and if its even possible).

**Comment by KiritoKun90** [comment]
Ok I'll do it for sure and if I see that I still have a problem I'll let you know.

Cheers

**Comment by KiritoKun90** [comment]
@normanmaurer Already done and they told me it's a netty issue and to write here lel :)
Np I'll find it out by myself. Thx
