### ISSUE TITLE
Suddenly Kicked From The Server And Can't Join Back {netty issue?}

### ISSUE THREAD

**Issue by KiritoKun90** [netty/netty#7274]
Players suddenly were kicked from the server and they can't join back.
This is the error I see when I try to log in:

**io.netty.channel.abstracts channel$annotated connectexception**

What is that mean? Cause I didn't find any ERROR into the console, except this message in game.

**Comment by johnou** [comment]
Check your server logs and provide the full stacktrace to the BungeeCord forum / maintainer, if they spot it's an issue with Netty I am sure they will follow up on this issue tracker with specifics eg. reproducer, thread dumps, heap dump etc. Please stop reporting BungeeCord specific issues without first verifying it is an issue with Netty.

**Comment by KiritoKun90** [comment]
Probably you didn't read well... I already said 0 error message in the log.
Also please stop acting like a professional when people out there are not. 
Forum exists for this, at least I suppose.... I wrote here cause the only message I see is:

**io.netty.channel.abstracts channel$annotated connectexception**

I googled it and all the older posts that I've found talke about netty, also the messages says it. How did I know is about Bungee?! I need constructive answer, not random ones. And ofc I've tried many things before posting here cause I don't like to lose time.
I'm sorry if I'm newbie, but just to let you know: I post here and you say to contact Bungee... I contact Bungee and they say to post here.... just tell me what should I do, cause the only reference that I have is the name "netty" into this error.

Cheers

**Comment by johnou** [comment]
I'm acting like a professional because that's my job. The Netty issue tracker is dedicated for issues, you might try stackoverflow or netty@googlegroups.com for questions. When creating an issue here do your best to fill out the template https://github.com/netty/netty/blob/4.1/.github/ISSUE_TEMPLATE.md instead of deleting it and giving vague desciptions, also keep in mind that someone replying here might not even know what Bungee is.

While Netty does not  provide BungeeCord support I can give a few tips.

The broken reference you provided roughly matches https://github.com/netty/netty/blob/aa8bdb5d6b7f89d56712c2d177c27857a17d79cd/transport/src/main/java/io/netty/channel/AbstractChannel.java#L1023 you should look into what logging framework the software you are running uses and that it is configured correctly, once you have done that try and reproduce the error and get a full stacktrace, on the other hand if there are no errors you should look into changing the log level of Netty and the application to debug level and see if there are any other clues as to what might be wrong with your deployment eg. missing dependencies, configuration issue etc.

**Comment by normanmaurer** [comment]
As @johnou mentioned this should be reported to the BungeeCord team. The exception you are seeing is because we could not connect to the server which may be because of network problems or bad configuration. Nothing Netty can do here as Netty itself is just a framework that is used by others, like BungeeCord.

**Comment by KiritoKun90** [comment]
They told me that it isn't their issue and that I was supposed to contact you and that's what I did. Btw np, I'll find it out by myself. Thx

**Comment by johnou** [comment]
Another tip, try running the JVM with ```-Djava.net.preferIPv4Stack=true``` network setup on the VPS / application might not be configured correctly and this property sometimes works around that.
