### ISSUE TITLE
HTTP/2 Use of ByteBuf for frames with small content

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7629]
Currently `Http2PingFrame` and `Http2GoAwayFrame` are backed by a `ByteBuf`. This was done for consistency reasons but increases the complexity for sharing/reusing these objects. Since is it assumed the payload size for these frames is typically small (<100 bytes) should we instead just use a `byte[]` for these frames to simplify the APIs?

**Comment by bryce-anderson** [comment]
For the PING frame it's arguable that you could even use a `long` since the size is exactly 8 bytes and the values are often going to be id's or timestamps, but a `byte[]` is definitely better than a `ByteBuf`. As @ejona86 noted, GOAWAY is less clear as the content doesn't have a size limit other than MAX_FRAME_SIZE, yet they are likely to be small, and allocating a new GOAWAY frame per HTTP/2 session seems like a drop in the ocean.

**Comment by ejona86** [comment]
PING can use `long` as well. Since it is generally an ID and it is fixed-length, `long` isn't really strange to work with.

Taken from https://github.com/netty/netty/issues/7607#issuecomment-360606631: 
> reader/writer indexes. we should be able to use duplicate()/slice().

`duplicate()` works. That's [what we do today](https://github.com/netty/netty/blob/911b2ac/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L326). However, we need to do it once for each child channel.

Ignoring object overhead (which will bloat this more) and assuming `duplicate()` uses `DuplicatedByteBuf`, each `Http2GoAwayFrame.duplicate()` has `(8+4+4)+(8+4+4+4+4+4) = 44 bytes` worth of fields.

So we end up going through effort to use `ByteBuf`, but it's not clear it actually wins us much.

**Comment by ejona86** [comment]
To be clear: in this discussion I am trying to optimize the _experience_, not performance. Any talk about performance from me is mainly to point out that `ByteBuf` really doesn't provide us much in these cases.

**Comment by Scottmitch** [comment]
> PING can use long

+1 if its just 64 bits. Not sure why we also don't do this in the "lower level" API....

> we end up going through effort to use ByteBuf, but it's not clear it actually wins us much.

I'm in agreement here. Any one have objections to this change?

**Comment by carl-mastrangelo** [comment]
SGTM

**Comment by normanmaurer** [comment]
I am not sure ... but I kind of feel its good to be consistent even if it may be a bit more effort . At the moment its easy to just check if `ByteBufHolder` is implemented and if so be sure the frame holds some kind of content. This is not true anymore if we change it. Also while the memory overhead used by the ByteBuf may be "huge" compared to the actual data we could argue that this is not a problem as we would typically have a pool of these anyway.

**Comment by trustin** [comment]
> PING can use long

+1 - way better than byte[8]

> GO_AWAY

I think it's better keeping `ByteBuf` in this case given that it can be arbitrarily large, especially in case where it contains some debugging info such as stack trace when using HTTP/2 internally.

**Comment by Scottmitch** [comment]
> in this case given that it can be arbitrarily large

+1. Since the data is not bounded, and it is consistent with how Netty represents data almost everywhere else this is a compelling argument for me. Even though it maybe more "effort" to consume/use `ByteBuf`, and the memory overhead for small payloads may be higher, I would prefer to keep it as is.

**Comment by normanmaurer** [comment]
@Scottmitch should I work on a PR ?

**Comment by Scottmitch** [comment]
@normanmaurer - sure for the ping content as `long`. thanks!

**Comment by ejona86** [comment]
> given that it can be arbitrarily large

> Since the data is not bounded

It's guaranteed to be less than 16k, or rather, less than the maximum frame size. But yes, that is a noticeable size.

> it is consistent with how Netty represents data almost everywhere else

Sounds fine. Let's keep goaway as-is.

----

Aside: it's a little bit of a shame that it isn't defined to be string data, since it generally _is_ character data and code is commonly assuming it is ascii/text and "hoping for the best." If it was clearly a string we could store it as AsciiString/String. But alas.

**Comment by Scottmitch** [comment]
> It's guaranteed to be less ... than the maximum frame size. But yes, that is a noticeable size.

Agreed. ~16MB with current definition of `SETTINGS_MAX_FRAME_SIZE`.

**Comment by normanmaurer** [comment]
@Scottmitch @ejona86 @carl-mastrangelo @bryce-anderson @trustin just to clarify, we want to change it to long (ping) all the way through the API ? So also for `FrameListener`, `Http2FrameWriter` etc... Correct ?

**Comment by bryce-anderson** [comment]
@normanmaurer, that would be my preference.

**Comment by ejona86** [comment]
I don't have an opinion for the old API.

**Comment by trustin** [comment]
+1 for changing all.

**Comment by Scottmitch** [comment]
+1 for changing it all lets take advantage of `UnstableApi` while we still can :)

**Comment by normanmaurer** [comment]
ok will do.

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/7690.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7690
