### ISSUE TITLE
Http2ConnectionHandler shutsdown channel too early when using SSL

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#7639]
### Expected behavior
Connection read related failures should be noticed before buffered writes.

 
### Actual behavior
Channel is closed by failing buffered writes too earl

### Steps to reproduce.
https://github.com/grpc/grpc-java/issues/3991

In this issue, gRPC is adding an SSL handler followed by an Http2ConnectionHandler.   When added, the Http2ConnectionHandler writes the preface which is buffered by the SslHandler.   In the issue linked, the certificate sent by the server was incorrect and the client tries to handle the error.  The exact call sequence is 

1.  `SslHandler.decodeJdkCompatible`
2.  `SslHandler.handleUnwrapThrowable`
3.  `SslHandler.wrapAndFlush`
4.  `SslHandler.wrap`
5.  `promise.tryFailure(SSLENGINE_CLOSED);`

This goes through several promises and eventually fails the Write promise for the HTTP/2 preface sent.   Unfortunately, the write looks like:

```
ctx.write(connectionPrefaceBuf()).addListener(ChannelFutureListener.CLOSE_ON_FAILURE);
```

(We are still in the the scope of the `read`, remember).    This promise is failed, which closes the channel, which then ends all further processing by gRPC because we ignore errors after the channel has closed.    I believe this is wrong, because the `SslHandshakeCompletionEvent` get trigger _after_ the channel has been closed down, which is not the correct order.

As a work around, gRPC now adds the HTTP/2 handler after Ssl is established in order for the correct Ssl Exception to be returned.

As for a fix, I'm open to ideas.    My first guess was to make the `Http2ConnectionHandler` not use `CLOSE_ON_FAILURE`, but instead add an executable to the event loop to close the channel.  This would allow the read() to fail properly, followed by closing the connection.  @ejona86 points out that this may not work, because other write failure listeners may close the connection down early too.   I still think this is likely the best course of action.  

### Netty version
4.1.17

**Comment by ejona86** [comment]
> My first guess was to make the Http2ConnectionHandler not use CLOSE_ON_FAILURE, but instead add an executable to the event loop to close the channel.

I brought up that other things related to this handling _may_ also be putting things on the event loop (or putting them there dependent of the reentrancy counter), such that the channel.close() still happens before they are processed. I didn't look into it at all.

**Comment by Scottmitch** [comment]
netty's pipeline model, decoupling of components, and async notification/callbacks tend to lead to these ordering/sequence issues. The "best effort" way to resolve this is as you stated "execute on event loop and run code later". This doesn't guarantee the issue will be resolved, because as you stated other areas maybe using the same strategy in a loosely coupled manner. When ever this strategy comes up I always encourage folks to find an alternative if possible.

Is it just the `SslHandshakeCompletionEvent` which is out of sequence? I would need to investigate more but perhaps we should do the handshake failure processing before attempting to notify the write promise.

**Comment by ejona86** [comment]
Based on grpc/grpc-java#4016, this _may_ be a regression introduced in netty 4.1.17. It is possible the regression is in gRPC instead of Netty, because I've not checked that just changing Netty introduces the problem, but given the Netty churn around that time and our research already it seems likely it was a Netty regression.

**Comment by Scottmitch** [comment]
see https://github.com/netty/netty/pull/7667

**Comment by normanmaurer** [comment]
I think @Scottmitch s patch makes perfect sense.
