### ISSUE TITLE
io.netty.handler.codec.http.HttpContentCompressor need compress threshold

### ISSUE THREAD

**Issue by teaey** [netty/netty#7660]
### Expected behavior
the response body is compressed, when the response body exceeds the threshold
### Actual behavior
no threshold can be set
### Steps to reproduce
-
### Minimal yet complete reproducer code (or URL to code)
-
### Netty version
4.1.16.Final
### JVM version (e.g. `java -version`)
java 1.8
### OS version (e.g. `uname -a`)
-

**Comment by normanmaurer** [comment]
@teaey we will need some more details etc to be able to fix this. Can you give some more or share some code ?

**Comment by teaey** [comment]
@normanmaurer  Please see : https://github.com/teaey/netty/commit/1cf24675c9e90d29d799e6184a9da13a2984a0f9

**Comment by normanmaurer** [comment]
@teaey looks useful... yeah please open a PR and I will comment there. Thanks!

**Comment by teaey** [comment]
@normanmaurer  Done

**Comment by hepin1989** [comment]
@normanmaurer ，I suggested he to make a PR, he is sitting beside me now.

**Comment by normanmaurer** [comment]
@hepin1989 awesome :) Thanks @teaey

**Comment by pli2014** [comment]
@teaey  I enjoy this enhancement, good job.

**Comment by pli2014** [comment]
This one is a little less obvious and there are two components. For starters, if you’re compressing files that are smaller than the MTU size of a TCP packet, you’re wasting your time. 1500 bytes is the MTU size for the internet since that is the largest size allowed at the network layer. If you take a file that is 1300 bytes and compress it to 800 bytes, it’s still transmitted in that same 1500 byte packet regardless, so you’ve gained nothing. That being the case, you should restrict the gzip compression to files with a size greater than a single packet, 1400 bytes (1.4KB) is a safe value.

just set this threshold with 1500 as default value. avoid to CPU cost.

**Comment by normanmaurer** [comment]
@pli2014 I think we should keep 0 as default value to not change behaviour.

**Comment by pli2014** [comment]
@normanmaurer  using this default value in constructor method or comment this explanation with variable.  I propose this for other users.

**Comment by hepin1989** [comment]
Maybe we could introduce a static constant field as a suggested value?

**Comment by normanmaurer** [comment]
@hepin1989 @pli2014 I think we should not suggest anything as what makes sense highly depends... for example even if you use smaller buffers as the mtu size it may make sense if you do a gathering write.

**Comment by teaey** [comment]
Let the user decide how to use it.

**Comment by normanmaurer** [comment]
Merged...
