### ISSUE TITLE
No way to get a Http2StreamChannel for a client h2c upgrade stream via Http2MultiplexCodec

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#7947]
### Expected behavior
When using the `Http2MultiplexCodec` on a client after a h2c upgrade is performed, I expect to be able to get a handle on the `Http2StreamChannel` associated with the upgrade request when using the `Http2MultiplexCodec`.

### Actual behavior
There is no public API for surfacing a `Http2StreamChannel` that resulted from the client request.

### Netty version
Branch 4.1 (as of SHA 0bce0450c05697d)

**Comment by normanmaurer** [comment]
@bryce-anderson basically you are asking to get access to stream 1 (upgrade stream) ?

**Comment by bryce-anderson** [comment]
@normanmaurer, yes, specifically as a client since I wasn't clear on that.

**Comment by bryce-anderson** [comment]
@normanmaurer, I think the implementation of `Http2StreamChannel` in the private class `DefaultHttp2StreamChannel` inside the `Http2MultiplexCodec` and I don't see a way to surface it (outside of reflection magic).

I'm more than happy to work on a PR presuming @ejona86 or someone else more versed doesn't point me to an API I missed. I'll start on it tomorrow unless someone intervenes.

**Comment by bryce-anderson** [comment]
@ejona86, I'm not sure what you mean. I don't want to use the `Http2FrameStream`, I want to use the child channels in the `Http2MultiplexCodec`, and I think they are all implementations of the `Http2StreamChannel`, which is what you get from the `Http2StreamChannelBootstrap`. Unfortunately you can't get the `Http2StreamChannel` for the upgrade stream since it was created for you by the upgrade mechanism.

**Comment by ejona86** [comment]
You can't get _any_ of the channels created for you. That's true for any inbound request. Instead, you can specify the handler that will be installed in the pipeline for that channel. If you need to interact with that channel, then you coordinate with your handler. That's standard Netty for incoming connections.

What am I missing?

**Comment by bryce-anderson** [comment]
I'm talking about a client side usage of `Http2MultiplexCodec` when doing a h2c upgrade. How should I be using it for the request that resulted in the upgrade? In a way, I did create that channel via my HTTP/1.x upgrade request, but it is not like streams 3+ where it begins as a h2 stream from birth.

**Comment by ejona86** [comment]
Ah, I see. _Client-side._ And you did say client in the issue title.

I only did server-side for this before. Client side looks more complicated API-wise, because we don't know whether we'll be speaking HTTP/1 or HTTP/2. The current upgrade API is call-back based, where you provide a Handler that will be used when appropriate.

It's a bit hard for me to see how this all works, because the current example relies on using HTTP/2 API and then using HttpToHttp2ConnectionHandler or Http2ConnectionHandler depending on the upgrade result. Although, maybe that's what we need here, use a HTTP/2 handler with HTTP/1 conversion logic and if the upgrade is successful the handler would be "migrated" to a child channel (although add/removal from the pipeline may be confusing).

Alternatively, maybe the handler could be a HTTP/1 handler that continues receiving HTTP/1 frames (converted from HTTP/2) until the end of the response, and it just ignores any HTTP/2 frames flowing past. In that solution, there _wouldn't_ be a childchan for the upgraded stream. (Note: the handler could actually speak HTTP/2, but there would need to be another HTTP/1 to HTTP/2 conversion; yes, that means we would convert HTTP/2 to HTTP/1 to HTTP/2 for the upgraded stream.)

Yeah. This would take some time to figure out.

**Comment by bryce-anderson** [comment]
Sorry for the confusion about using this client side.

An awkward part of the 'flow-past' solution is that you can't manage response backpressure for the upgraded stream in the normal Netty manner since if you turn off auto-read or you stall the whole h2 session.

My first inclination is to mange this via a richer event model where if the Http2MultiplexCodec gets installed due to a h2c upgrade, the tail of the pipeline gets an event that provides a handle for the child stream and it's the tail of the pipelines job to make the transition. The transition will be pretty complex, but h2c upgrades are anything but simple.
For Finagles current usage, since we're not doing the dispatch work in the pipeline, it's relatively easy for us to switch the underlying `Channel`, but this isn't exactly a normal pattern when using Netty directly.

I'm happy to start putting together something along those lines if it sounds like a reasonable direction to try out.

**Comment by ejona86** [comment]
Ah... flow control. Of course. So axe the HTTP/1 conversion idea.

> the tail of the pipeline gets an event that provides a handle for the child stream and it's the tail of the pipelines job to make the transition

This is sort of fine, but it is timing sensitive ("racy"). If any handler in the pipeline delayed that event, then frames could begin appearing in the childchan before the transition has started.

I think simply passing in a "stream-1 HTTP/2 handler" to use if upgrade succeeds would be more straight-forward, and more in line with the rest of the upgrade logic. Complexity-wise it seems similar or maybe easier to use (although there may be a cost to preparing that handler even when unused).

**Comment by bryce-anderson** [comment]
@ejona86, you're right, the racy nature of pushing messages down that new child stream channel could be tricky and it's not really the same pattern used elsewhere. I like the idea of providing an upgrade initializer/handler.

I'd like to get this sorted out sooner than later so we can start using the `Http2MultiplexCodec` in our client, so I'm happy to take a run at this unless someone else feels like they really want to tackle it.

**Comment by ejona86** [comment]
@bryce-anderson, go for it. I couldn't work on it soon and the upgrade handler seems good enough to me.

**Comment by normanmaurer** [comment]
👍 sounds good to me
