### ISSUE TITLE
HTTP/2 - Race Condition with RST_STREAM

### ISSUE THREAD

**Issue by shorea** [netty/netty#8025]
### Expected behavior
When a RST_STREAM is sent to the remote, any future incoming DATA frames should be ignored.

### Actual behavior
Sometimes an error is thrown instead. (See https://github.com/grpc/grpc-java/issues/3548)

### Steps to reproduce
Send a RST_STREAM frame to a remote endpoint.

### Netty version
4.1.23.Final

### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Any (observed on Mac and Linux).

For a bit more context. Sending a RST_STREAM will eventually trigger this code in Http2ConnectionHandler, https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L589 . This removes the stream from the active streams metadata and any subsequent DATA frames that come in will be considered as an unknown stream. I was thinking we could just check if the stream may have existed and if so just ignore the DATA frame altogether. So instead of [this](https://github.com/netty/netty/blob/501662a77f8166382eefd18a8620983d27f59d4a/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L535) do something like this

```java
verifyStreamMayHaveExisted(streamId);
return true;
```

**Comment by normanmaurer** [comment]
@carl-mastrangelo @bryce-anderson @mosesn @ejona86 @Scottmitch thoughts ?

**Comment by ejona86** [comment]
Ignoring the frames may be most appropriate. I think this broke several years ago when old streams became no longer retained.

**Comment by bryce-anderson** [comment]
I've seen the log entries described in https://github.com/grpc/grpc-java/issues/3548 as well. The race condition is intrinsic to the protocol: there is no way for a peer to send a RST and ensure that there are not DATA (or other frames) already in flight. The docs at the origin of the exception [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L532) even describe the situation. 

I think the behavior we have now is about as good as we can hope for other than we shouldn't pollute logs with it, at least at info or higher levels. Sending a RST in response to these frames is probably smart to combat bad behavior of peers, though the spec does say the frames should be ignored.

There is one way we could do a little better, but it's slightly complex. We can hubristically tell if the frame is the start of a new stream by the fact that DATA frames will never initiate a stream and trailer HEADERS frames won't contain any pseudo headers. If we do that, we can presume any HEADERS that are not trailers are an out-of-order new stream and we can elevate the exception to a connection level PROTOCOL_ERROR as described in the [spec](https://http2.github.io/http2-spec/#rfc.section.5.1.1/). Trailer headers and DATA frames can then be presumed to belong to a stream that was RST, and ignored. The drawback is that this doesn't protect against peers that are sending orphan DATA of trailer HEADERS frames, but ignoring them is probably not much worse than sending a RST since this is kind of worst-case peer behavior.

**Comment by mosesn** [comment]
@bryce-anderson this isn't necessarily a bad remote peer–they might not have received the RST before sending the DATA frame, so I think we should just ignore them.  telling the difference between a bad-actor remote peer and an honest-mistake remote peer seems too hard.

**Comment by bryce-anderson** [comment]
@mosesn, it's not even necessarily an 'honest mistake', there is no way to prevent the race.

Ignoring the messages is fine outside of the case where the peer tries to initiate an out-of-order stream. In that case ignoring the frame may cause the peer to hang unless they decide to reset the illegal stream themselves. From the perspective of _this_ session, it's probably still fine to ignore this case since the alternative is to tear down the session as described in section (§5.1.1):

> The identifier of a newly established stream MUST be numerically greater than all streams that the initiating endpoint has opened or reserved. This governs streams that are opened using a HEADERS frame and streams that are reserved using PUSH_PROMISE. An endpoint that receives an unexpected stream identifier MUST respond with a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

That said, it's not terribly difficult to see if the headers are stream initiating headers vs trailers potentially from a reset stream: just check for pseudo headers.

**Comment by shorea** [comment]
Thanks for the input guys! I'm working on a testing a potential fix and will open a PR soon.

**Comment by shorea** [comment]
@normanmaurer, assuming I get a PR accepted for this issue would it be possible to do a release of Netty early next week to get it incorporated? We are trying to get this issue fixed for a new product launch.

**Comment by normanmaurer** [comment]
@shorea yep... sounds good. We wanted to do a Netty release anyway :)

**Comment by abhishekagarwal87** [comment]
was this ever fixed? Linked PR is closed and doesn't have any commits.
