### ISSUE TITLE
HTTP 1.1 Pipelining Support

### ISSUE THREAD

**Issue by xttam** [netty/netty#8027]
I need to send multiple async requests to a rest server through the same connection and get them executed in FIFO order, I think HTTP 1.1 pipelining is just perfect for this.

Do Netty or any HTTP wrapper client around Netty support this? There are some related comments on this on other issues but I couldn't find any example or test case.

**Comment by normanmaurer** [comment]
Sure netty let you do this... Its just matter of sending multiple requests and not wait for the response before send the next one.

**Comment by xttam** [comment]
I know it's a matter of sending multiple requests and then reading each response as they come, but what about the channel implementation? I'm trying to avoid implementing everything myself and I'm not very familiar with Netty, but it seems it doesn't come with a fully fledged http client, does it?

I've tried doing this on some wrappers like [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client) but it would just send one request at a time in sync mode if I set max-connections-per-host to 1.

I'd appreciate it if you can link an example. The client described on the User Guide is very basic and doesn't even implement the http protocol.

**Comment by mosesn** [comment]
@xttam the core API is something like

```
Channel channel = ...
channel.write(req)
```

If you want to talk to a remote peer that supports pipelining, you then send a new request immediately after.

```
Channel channel = ...
channel.write(req1);
channel.write(req2);
```

The difficulty with pipelining then becomes matching sent requests with received responses.

As you've mentioned, netty doesn't come with a fully fledged http client.  Netty is intended to be a layer that more batteries-included libraries can build on top of.  Since you seem to like AsyncHttpClient, I would encourage you to contribute pipelining to that library.
