### ISSUE TITLE
Snapshot publication for native library

### ISSUE THREAD

**Issue by cchantep** [netty/netty#8100]
### Expected behavior

Snapshot version of kqueue available at Sonatype snapshot.

### Actual behavior

For 4.1.26.Final-SNAPSHOT, the kqueue artifact with classifier `osx-x86_64` is not published (the one with the `META-INF/native`), whereas it seems ok for epoll.

### Steps to reproduce

`sbt update`

### Minimal yet complete reproducer code (or URL to code)

https://github.com/cchantep/netty-native-shading

### Netty version

4.1.26.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

1.{8,9}

### OS version (e.g. `uname -a`)

OS X (high sierra)

**Comment by normanmaurer** [comment]
these days we publish

**Comment by simonbasle** [comment]
@normanmaurer I don't think the issue is fully resolved: the snapshots repository does contain a jar with `osx-x86_64` classifier for `4.1.43.Final-SNAPSHOT`, but only one.
Newer versions with a newer timestamp don't include the native library nor classifier 😢

Compare just the filenames of [kqueue](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-kqueue/4.1.43.Final-SNAPSHOT/) vs [epoll](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-epoll/4.1.43.Final-SNAPSHOT/) and notice epoll consistently has the `linux-x86_64` classifier, while kqueue doesn't.
