### ISSUE TITLE
why use lazySet instead set in WeakOrderQueue#add?

### ISSUE THREAD

**Issue by zhaojigang** [netty/netty#8215]
It's a not an issue. Instead, I'm asking for help. I cant understand why use lazySet instead set in WeakOrderQueue#add? and I also cant understand why "we lazy set to ensure that setting stack to null appears before we unnull it in the owning thread"?

**Comment by normanmaurer** [comment]
I think @belliottsmith can explain it better as he wrote the original version. But I think `lazySet` gives us enough "guarantees" and is cheaper is the answer.

**Comment by belliottsmith** [comment]
Right.  It only guarantees write-ordering wrt previous writes, and the immediately preceding write is the nulling of the handle's `stack` property.  So we are guaranteeing (cheaply) that the null `stack` value will be seen by other threads prior to anyone witnessing that `tail == writeIndex + 1`

It's a long time since I looked at the code, but it looks like this is simply to ensure that when the owning thread's pool reclaims the handle, and sets the `stack` property to itself, it is guaranteed that these two writes are not re-ordered (which could leave the value `null` when it should be its owning stack).

As a by-product, it also guarantees that any state that may have been modified in the recycled object is also visible prior to its reference on the receiving thread.  Which is a necessary 'least surprise' property.

This class was written to (extraordinarily) minimise coordination between CPUs.  More so than any other similar structure I have seen, and it pays for it by reducing the promptness of recycling between threads, since recycling was expected primarily to be same-thread or between a small cohort of threads (there have been some issues iirc, with people abusing it for random thread recycling amongst huge cohorts of threads)

Unlike many other concurrent data structures you may have seen, there may be zero volatile property accesses between two operations on different threads, so things like `lazySet` are necessary to guarantee against subtle correctness issues like this.

**Comment by zhaojigang** [comment]
ok, thanks!!! @belliottsmith @normanmaurer
