### ISSUE TITLE
[Netty5] ChannelPipeline mutating methods signature

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8511]
All the methods that mutate the `ChannelPipeline` are currently “synchronous”. This means all manipulation of the pipeline must complete before modifier methods return, and the`ChannelPipeline` implementation must therefore account for concurrency. All of the interaction with the `ChannelPipeline` is inside the `EventLoop` and we can therefore delay modification until we are in the `EventLoop`. This will reduce complexity of the `ChannelPipeline` implementation, and also remove the current “best effort” concurrency code in `AbstractChannelHandlerContext`. 

There are currently 2 different ideas here: 
1) Have all methods just return `ChannelFuture` which completes when the pipeline is modified (e.g. on the `EventLoop`). If we do this we also most likely should allow to pass in a `ChannelPromise` that is used for notifications. 
2) Only allow pipeline modifications on the `EventLoop`. 

I am currently in favour of 1) as this is also what we did in [SwiftNIO](https://swiftnio.io) with great success and still will allow people to just use `ChannelPipeline` from “any thread”.

**Comment by ejona86** [comment]
I think this interacts with #8156.

**Comment by njhill** [comment]
@normanmaurer is this obsolete in light of #8778?

Related to this and #8156, I had another idea w.r.t. the pipeline manipulation API design, i.e. how best to reference handlers after they are added. Why not have all the `addX`/`replace` methods return the new handler context, and move all of the `addBefore`, `addAfter`, `replace`, `remove` methods from the pipeline to the context?

I think this would address most/all of the frustrations raised in #8156, including most of the cartesian product explosion. You could do things such as:
```java
channel.pipeline().addFirst(handler1).addAfter(handler2, "myname").addAfter(handler3);

channel.pipeline().context("myname").replace(handler4);

MyHandler removed = channel.pipeline().context(MyHandler.class).remove();
```
etc.

If we still want to avoid the synchronization here, all these methods could instead return `Future<ChannelHandlerContext>` along the lines of your suggestion 1 above.

cc @ejona86

**Comment by RoganDawes** [comment]
I quite like this approach to the problem of the Cartesian product of methods on ChannelPipeline.

One existing method that this approach does not seem to support is ```ch.pipeline().addLast(handler1, handler2, handler3);```
Which context would you return from such a method?

I think it would be reasonable, though, to require migration to ```ch.pipeline().addLast(handler1).addAfter(handler2).addAfter(handler3);```

Or better, to only have methods on the context for adding new handlers, and remove those entirely from ChannelPipeline, leaving only methods for accessing the various contexts.

e..g
```pipeline.firstContext().addAfter(handler);```
```pipeline.lastContext().addAfter(handler);```
```pipeline.context(name)...```
```pipeline.context(ChannelHandler.class)...```
etc

I'm not sure how this would look if the ChannelHandlerContext add* and replace methods returned a Future<ChannelHandlerContext> instead.

```pipeline.lastContext().addAfter(handler1).sync().get().addAfter(handler2);``` ?

Ick.

**Comment by normanmaurer** [comment]
@nicktrav I like your idea. That said we may still want to return a `Future` (not sure about this yet).

@RoganDawes I think we should just not support the "varargs" anymore to fix the problem. About how this would look like when we return futures, I think we would allow to chain calls via some lambdas.

**Comment by njhill** [comment]
> One existing method that this approach does not seem to support is `ch.pipeline().addLast(handler1, handler2, handler3);`

I hadn't considered that variation but that could either return the final context or if that might not be very intuitive then maybe just the pipeline as it does now.

> Or better, to only have methods on the context for adding new handlers, and remove those entirely from ChannelPipeline

This may need more thought since the implicit head and tail contexts are currently private/inaccessible I think.

> I'm not sure how this would look if the ChannelHandlerContext add* and replace methods returned a Future instead.

I think your distaste here is related to returning a future rather than this latest proposal, i.e. something similar would be needed even with the current structure or others that were considered.

@normanmaurer I think you tagged the wrong Nick :)

**Comment by normanmaurer** [comment]
ups @njhill yep... wrong nick 👍

**Comment by ejona86** [comment]
Note that @njhill's suggestion is pretty similar to using `ctx` instead of `name` in the relative ChannelPipeline APIs.

So instead of:
```
ChannelPipeline addBefore(String baseName, String name, ChannelHandler handler);
```

It would be
```
ChannelPipeline addBefore(ChannelHandlerContext ctx, String name, ChannelHandler handler);
```

And cases like remove()/replace() could remove most of their various overloads and just rely on `ctx`. (And yes, we could also change the return value to be a `ctx`.)

I point this out because it keeps the APIs on ChannelPipeline for mostly the same benefit, without having trouble with Head/Tail. The bare minimum of mutation operations necessary on the ChannelPipeline (throwing away things like removeFirst()/removeLast()):

```
addBefore(ctx, newHandler)
addAfter(ctx, newHandler)
addFirst(newHandler)
addLast(newHandler)
remove(ctx)
replace(ctx, newHandler)
```

We could move all of that API to ChannelHandlerContext except for addFirst()/addLast(). Those would need to stay on ChannelPipeline (but would be rarely needed, since the Pipeline is initialized to have a Handler and mostly modified from an existing handler). If we expose head/tail, then we could remove addFirst()/addLast().

Note that when I considered this earlier, I did realize it was weird to return ChannelHandlerContext because _you shouldn't call it_. All the methods on it are intended only for the added Handler. It could be confusing figuring out why the ctx is returned. Also, the signature will be unclear, as ChannelHandlerContext returns `this` very frequently; it'll may be subtle to notice the times it returns `newCtx` instead.

**Comment by njhill** [comment]
> Note that @njhill's suggestion is pretty similar to using ctx instead of name in the relative ChannelPipeline APIs.

That's true, I guess the main advantage is that it allows more elegant constructs such as:
```java
channel.pipeline().context(MyHandler.class).replace(newHandler);
```
rather than
```java
channel.pipeline().replace(channel.pipeline().context(MyHandler.class), newHandler);
```
but I agree there may be a tradeoff of being slightly less intuitive w.r.t. where to "find" these functions.

> Note that when I considered this earlier, I did realize it was weird to return ChannelHandlerContext because you shouldn't call it.

This was also in my mind, but something I'm not actually sure of - you probably know better than me and maybe @normanmaurer could also weigh in... but is it really true that "All the methods on it are intended only for the added Handler"? I'd kind of prefer that to be the case but something which threw me off recently in this regard is the [comments in `ChannelHandler` doc](https://github.com/netty/netty/blob/02850da4808bd64bf131a083ddedb8856189dd20/transport/src/main/java/io/netty/channel/ChannelHandlerContext.java#L47) about external use. Maybe any external use should still be exposed from the handler instance itself? And then also why do the `ChannelPipeline.context(...)` methods exist?

One idea to address the concerns raised in your last paragraph - we could introduce a simpler `PipelineStep` superinterface of `ChannelHandlerContext` that acts as a more opaque handle returned from the appropriate `ChannelPipeline` methods (including maybe replacing `context(...)` with `step(...)`), and would expose only those methods pertaining to "external" manipulation of the pipeline. It could even have a `context()` method which returns itself (if there were some reason for it). wdyt?

**Comment by normanmaurer** [comment]
This was mostly done.

**Comment by RoganDawes** [comment]
> This might also lead to a change in the method signature for ChannelInitializer, though, so that it receives ChannelHandlerContext instead of Channel directly. I personally use ChannelInitializer in several places in my pipelines, and do not assume that the ChannelPipeline is empty when I do. As a result, I prefer to use addBefore/addAfter to addFirst/addLast methods. It is not the end of the world, of course, as I can always do ctx = ch.pipeline().context(this); It does seem cleaner to call ctx.channel() if you need the channel, though, which does not require any iteration.

Necro'ing this issue, because I just ran into `OptionalSslHandler`, that has `ChannelHandler newSslChannelHandler(ChannelHandlerContext ctx, SslContext sslContext)` signature. But this is essentially asking for a `ChannelInitializer`, because in most cases you want to add more than just one ChannelHandler to the pipeline. And at that point, there are likely to be other ChannelHandlers in the pipeline, so using relative adds is likely to be a good pattern to avoid messing up the order of the handlers.

Would it be reasonable to add an alternative method signature to ChannelInitializer, like `initChannel(ChannelHandlerContext ctx)` that by default delegates to `initChannel(ctx.channel())` to allow for a time for users to migrate, but mark the latter method as deprecated?

Also, @normanmaurer said:
> This was mostly done.

with regards to the rest of the discussion above. But I can't see the actual changes that he is referring to, if I look at the methods on `ChannelHandlerContext` or `ChannelPipeline`, or `git log -p -- transport/src/main/java/io/netty5/channel/ChannelHandlerContext.java transport/src/main/java/io/netty5/channel/ChannelPipeline.java transport/src/main/java/io/netty/channel/ChannelHandlerContext.java transport/src/main/java/io/netty/channel/ChannelPipeline.java`, I don't actually see any changes to the signatures of methods in these classes, especially not around Aug 25th 2021, the date of Norman's message above.
