### ISSUE TITLE
[Netty 5] Use Java11 as minimum Java version

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8540]
Netty 5 will move to Java 11 as minimum. 

This is driven by the fact that we assume that the development of Netty 5 will take some time and for people that can not switch to Java11 there will still be support for netty 4.1.

**Comment by smaldini** [comment]
Bold but interesting choice ! Java 11 is far from mainstream but it is all relative to 5.0 timeline as well so I am not too worried. We can still evaluate by then if we really needed any Java 9-11 API to achieve what we want. It seems that Finalizer/Cleaner/RefCounted might be one.

I believe the non Java 8 API tho will be pretty limited but if that happens, I wonder if we should have a 4.2 both introducing new features/changes, along with deprecations and requiring Java 8 only.

**Comment by normanmaurer** [comment]
@smaldini sounds fair enough... That said I can at least think of two things that are interesting for us which are both not in Java8.

* Compact string to maybe replace `AsciiString` : 
https://github.com/netty/netty/issues/8548
* Cleaner to replace `finalize()` as these are for example not supported on substrate VM : 
https://github.com/netty/netty/issues/8542

**Comment by smaldini** [comment]
Yeah so we need to look at AsciiString vs String but that seems like a small price to pay to keep compat if it was the only thing. That's up for debate tho.
About `finalize()` I would hope we could get away without using them. Implicit behavior depending on non deterministic GC behavior seems dangerous enough that maybe the best way would be to require explicit releasing. However doable it seems to be with 4 use cases (HashedWheelTimer, OpenSslContext, OpenSslEngine and PoolArena) there would be 1 case that might be tricky because leaky : Recycler. We already educate user to pay attention to `refcountable#release` calls and management of event loop / pool resources so it shouldn't be too far a gap to maybe transition to explicit behavior here too.

**Comment by ejona86** [comment]
Java 11 may be a bit too aggressive for gRPC to use it soon, as we may need to support "the last two LTS releases." That would mean it'd be 3 years from now before gRPC could use Netty 5. Our support timelines are still a bit up-in-the-air, though.

@smaldini, #8052 will likely resolve the `Recycler` issue. But I don't think we could remove all usages, for example, leak detector. Although maybe we can make such things optional and then use Cleaner or ObjectCleanerThread. Or may also be possible to fake an API like Cleaner using a custom class with `finalizer()`. Or just periodically poll a ReferenceQueue when registering new objects to be watched. I do agree this is a reasonable risk to using Java 8.

Concerning Compact strings/`AsciiString`, I think it would be fair to say, "if you want Netty to be more efficient, use Java 11." As in, we can still design for preference of Java 11+ without dropping Java 8, and it's not even difficult to do so in this case.

**Comment by SharpMan** [comment]
I would have understood choosing JDK10 for Http/2 feature,s but you guys went straight from the goal of **Java 8 to 11** ?
Did the community had any word on this ?
Although , Java11 does support tls1.3, I think the project will go through the longest ever unstable version.

**Comment by normanmaurer** [comment]
@SharpMan none of the things here is written in stone and just suggestions. We would love to hear suggestions from the community

**Comment by winterbe** [comment]
@SharpMan HTTP Client has changed from JDK 10 to 11. In Java 10 it was only available from `jdk.incubator` package. You shouldn’t build a library on top of that API.

**Comment by johnou** [comment]
@SharpMan I think you'll also find Netty 4.x is Java 6 :)

**Comment by SharpMan** [comment]
> l find Netty 4.x is Java 6. Java 11 is also the next LTS.
So everyone has to deal with commercial licenses 👏


> @SharpMan none of the things here is written in stone and just suggestions. We would love to hear suggestions from the community

[JDK 9 Issues ](https://github.com/netty/netty/issues?utf8=%E2%9C%93&q=is%3Aissue+java+9)
[JDK 10 Issues](https://github.com/netty/netty/issues?utf8=%E2%9C%93&q=is%3Aissue+java+10)

Netty has to complete solving issues related to previous JDK versions in order to aim for the new java version. All the feature are mentioned on the Netty 5 report will take 2-3 years to be tested and released.  So if we add the estimate to fix JDK11 issues, it would take forever. 
It is for the best of Netty to remain running on JDK8 minimal version, otherwise this project will just become a mess.

**Comment by Mr00Anderson** [comment]
My only concern but I have not checked into it much yet, the effects of peformance due to unsafe removale and off heap/direct buffers. I rely likely as many do on those peformance points.

**Comment by normanmaurer** [comment]
So far we did not find any requirement for Java 11 but can life with Java 8 as minimum requirement. Let me close this one and update the title to reflect that we use Java8 as a minimum

**Comment by fabienrenaud** [comment]
@normanmaurer https://github.com/netty/netty/issues/8838 is slated for Netty 5 and requires Java 11

**Comment by johnou** [comment]
@fabienrenaud doesn't require Java 11, it can be optional.

**Comment by kasobol-msft** [comment]
@normanmaurer It looks like Netty 5's baseline is now JDK 11 https://github.com/netty/netty/pull/10650 . This issue and referenced PR mention that 4.x line is going to be supported for a time being. Could you please shed some light on the plans for the 4.x? For how long is it going to be supported?

**Comment by normanmaurer** [comment]
@kasobol-msft there is not real defined date yet but I am sure it will be quite some time
