### ISSUE TITLE
CompositeByteBuf.Component freeIfNecessary always frees

### ISSUE THREAD

**Issue by jameskleeh** [netty/netty#8641]
### Expected behavior
The `freeIfNecessary` method should only release if the ref count > 0

### Actual behavior
The `freeIfNecessary` method always releases

I would like to be able to free any given component of a composite byte buffer myself, with release being called on the whole buffer only releasing the components that were not previously released. The method name indicates to me that is what should happen

### Netty version
4.1.30

**Comment by njhill** [comment]
@jameskleeh the `Component` class is private/internal to `CompositeByteBuf` and I think this method behaves as intended. I acknowledge the name is misleading and I think we should change it to just `free()`, but this is only to make the internal logic clearer, not because it's an API method. I suggest `free()` rather than `release()` to avoid any confusion with the public `release()` methods.

`CompositeByteBuf` takes ownership of any buffers added to it. If you subsequently only access them via the composite buffer, you don't need to worry about releasing them individually. You can remove components via the `removeComponent(...)` methods which will automatically release the corresponding buffers, and when `release` is ultimately called on the composite buffer it will release only the contained buffers it still owns, not any which it previously released due to explicit or indirect removal.

**Comment by jameskleeh** [comment]
@njhill Thanks for the explanation! I think it would be good to enforce the ownership of those components in code by returning a bytebuf that prevents the user from releasing it directly
