### ISSUE TITLE
Netty 5 wish list

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#8704]
Maybe we can use this issue to discuss all the changes we want to see in Netty 5 :)

This is a copy from an old issue from me:

"I did some tests with the example HttpStaticFileServer.
I downloaded a file and canceled the connection before completion.
In order to better handle such an abort, I have 2 ideas:

Adding a new method to ChannelProgressiveFutureListener

operationCanceled(ChannelProgressiveFuture future, long progress, long total) which will be called instead of the operationComplete in such a case.

or

Changing the existing method operationComplete to something like this:
operationComplete(ChannelProgressiveFuture future, long progress, long total)"

In Netty 5 I would like to see an easier way how to bind multiple IPs for a ServerBootstrap. Maybe you can come up with something :)

I also think that it might irritate some new Netty users when they see code like this:

.childHandler(new HexDumpProxyInitializer(REMOTE_HOST, REMOTE_PORT))

The class HexDumpProxyInitializer is a ChannelInitializer which can add one or more ChannelHandlers. Maybe something like .childInitializer() can be added. 
But I am not sure if this is really a good idea.

**Comment by Mr00Anderson** [comment]
What's wrong specifically with those two features that they need to be changed? The issue list is 383 at the time of writing this. 

What is the current way to bind multiple IPS with netty? Would be useful information to share if some netty users done use multiple ips. Though I have a feeling how I would if, but that's simply a thin layer of code to write onto of netty. 

Netty alone is pretty balanced. I think it's intended to write your own code for case specifics and works out of the box for standard protocols and functions.

**Comment by chrisvest** [comment]
At this point, a couple of things:

1. We removed the "progressive" futures from Netty 5. It's less complexity on our side, and less magic, to let integrators manage future-per-IO and make their own progress accounting. This also makes it more obvious what gets cancelled, and what managed to complete.

2. To the original issue, I think it'd be a bad idea to add more methods to the listeners, because then you can't make lambdas for them. The cancellation information is also already available from the future, which has to be inspected anyway in order to figure out if it succeeded or not.

3. Once you have a Channel from calling bind on a Bootstrap, you can call bind on the channel again. The returned future will then either succeed or fail depending on whether binding the socket to multiple addresses is supported or not.

**Comment by normanmaurer** [comment]
Let'S close this one... I think @chrisvest explained everything :)
