### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by zyb2013** [netty/netty#8765]
![image](https://user-images.githubusercontent.com/5093114/51579503-26058a80-1efc-11e9-9f52-f6856f3f5a22.png)
![image](https://user-images.githubusercontent.com/5093114/51579511-3158b600-1efc-11e9-8415-2cde0818680a.png)
In first picture,the code have no surround with try..catch.If here occurs RuntimeException,does it mean msg will not be released?

**Comment by normanmaurer** [comment]
@zyb2013 you are right we are not consistent here... I wonder which implementation is more correct tho.

@ejona86 @carl-mastrangelo @trustin WDYT ?

**Comment by normanmaurer** [comment]
And @Scottmitch

**Comment by Scottmitch** [comment]
Since `isNotValidPromise` may throw, and doesn't take ownership of (or even know about) the `msg` we should be catching and releasing in `writeAndFlush`.

We could also consider moving the cleanup code into the `write(Object, boolean, ChannelPromise)` method which is called by both of these methods.
