### ISSUE TITLE
Optimize ByteBuf-String conversion when charset is UTF-8 or ASCII

### ISSUE THREAD

**Issue by trustin** [netty/netty#909]
When a user specified a very well known encoding such as UTF-8 and ASCII, Netty could refrain from using CharsetEncoder/Decoder and use more optimized implementation.

**Comment by lukehutch** [comment]
It would be nice to add the methods: ByteBuf.writeUtf8Bytes(CharSequence) and Unpooled.wrapUtf8(CharSequence) that call out to ByteBufUtil.writeUtf8CharSequence() [partly to promote the fact that this new ultra-fast method for UTF8 conversion actually exists, so that people start using it...]

Does ByteBuf.copiedBuffer(CharSequence string, Charset charset) call ByteBufUtil.writeUtf8CharSequence() when 'charset' is UTF8, or is it using the java.lang String-to-UTF8 conversion method? Are there other places in Netty that still use java.lang UTF8 conversion?

**Comment by Scottmitch** [comment]
@normanmaurer - Can this be closed with the introduction of the ByteBufUtil methods?

**Comment by normanmaurer** [comment]
Yeah let us close this.
