### ISSUE TITLE
stop responding halfway

### ISSUE THREAD

**Issue by lifeinwild** [netty/netty#9210]
I'm a beginner at Netty, so I don't know if this is my mistake or Netty problem.

### Expected behavior
don't stop responding halfway.

### Actual behavior
Netty stop responding by Thread.sleep() in channelReadComplete().
Of course, it will be the same as processing that takes time other than Thread.sleep ().

### Steps to reproduce
copy the reproducer to your IDE, auto import fix, and run it.

### Minimal yet complete reproducer code (or URL to code)
```
/**
 * Depending on performance and timing, only partial data will be responsed and an assertion will occur.
 * you will see like "exceptionCaughtjava.lang.AssertionError: expected:<50000000> but was:<23199567>".
 *
 * OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
 * windows 10 Pro x64
 * Netty 4.1.36
 */
public class BigResponseTest {
	public static final int serverPort = 23841;
	public static byte[] big = new byte[1000 * 1000 * 50];//by computer performance. set enough big
	static {
		new Random().nextBytes(big);
	}
	public static final EventLoopGroup sg = new NioEventLoopGroup();
	public static final EventLoopGroup cg = new NioEventLoopGroup();

	public static class ResponseServer {
		public void run() throws Exception {
			ChannelInboundHandlerAdapter bigRes = new ChannelInboundHandlerAdapter() {
				@Override
				public void channelReadComplete(ChannelHandlerContext ctx)
						throws Exception {
					System.out.println("[Server]channelReadComplete");
					ctx.writeAndFlush(Unpooled.wrappedBuffer(big));
					//ctx.writeAndFlush(new ChunkedStream(new ByteArrayInputStream(big)));	//Not received why?
					Thread.sleep(1000 * 5);//Stop responding halfway. Why does it affect sending data?
				}

				@Override
				public void exceptionCaught(ChannelHandlerContext ctx,
						Throwable cause) throws Exception {
					System.out.println("[Server]exceptionCaught");
				}
			};
			ServerBootstrap b = new ServerBootstrap();
			b.group(sg).channel(NioServerSocketChannel.class)
					.localAddress(new InetSocketAddress(serverPort))
					.childHandler(new ChannelInitializer<SocketChannel>() {
						@Override
						public void initChannel(SocketChannel ch)
								throws Exception {
							System.out.println("[Server]init");
							ch.pipeline().addLast(bigRes);
						}
					});
			ChannelFuture future = b.bind(BigResponseTest.serverPort).sync();
		}
	}

	@Test
	public void test() throws Exception {
		ResponseServer s = new ResponseServer();
		s.run();
		ChannelInboundHandlerAdapter cHandler = new ChannelInboundHandlerAdapter() {
			private byte[] buf = new byte[big.length];
			private int count = 0;

			@Override
			public void exceptionCaught(ChannelHandlerContext ctx,
					Throwable cause) throws Exception {
				System.out
						.println("[Client]exceptionCaught" + cause.toString());
			}

			@Override
			public void channelRead(ChannelHandlerContext ctx, Object message) {
				System.out.println("[Client]received");
				if (message instanceof ByteBuf) {
					ByteBuf chunk = ((ByteBuf) message);
					int chunkSize = chunk.readableBytes();
					chunk.getBytes(chunk.readerIndex(), buf, count, chunkSize);
					count += chunkSize;
				} else {
					System.out.println("exception");
				}
			}

			@Override
			public void channelReadComplete(ChannelHandlerContext ctx)
					throws Exception {
				System.out.println("[Client]channelReadComplete");
				assertEquals(big.length, count);
				assertEquals(true, Arrays.equals(big, buf));
				System.out.println("[Client]channelReadComplete success");
			}

			@Override
			public void channelActive(ChannelHandlerContext ctx)
					throws Exception {
				System.out.println("[Client]channelActive "
						+ ctx.channel().remoteAddress());
				ctx.writeAndFlush(Unpooled.wrappedBuffer(new byte[333]));//just for triggering response code
			}
		};
		Bootstrap client = new Bootstrap();
		client.group(cg).channel(NioSocketChannel.class)
				.remoteAddress(new InetSocketAddress("localhost", serverPort))
				.handler(new ChannelInitializer<SocketChannel>() {
					@Override
					protected void initChannel(SocketChannel ch)
							throws Exception {
						System.out.println("[Client]init");
						ch.pipeline().addLast(ChannelInboundHandlerAdapter.class
								.getSimpleName(), cHandler);
					}

				});
		client.connect();

		Thread.sleep(1000 * 3);//wait for sending and responding and receiving.

		sg.shutdownGracefully().sync();
		cg.shutdownGracefully().sync();
	}
}
```

### Netty version
4.1.36

### JVM version (e.g. `java -version`)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)

### OS version (e.g. `uname -a`)
windows 10 Pro x64

**Comment by lifeinwild** [comment]
There are two problems.
If you make "byte[] big" smaller or remove the line of Thread.sleep (1000 * 5), you can send all the data.
Even in this case, channelReadComplete () may be called on the client side even though reception has not been completed. But eventually the client receives all the data.
If you increase "byte[] big" or put the line of Thread.sleep (1000 * 5), the client side will not receive all data.

That is, there is a problem that channelReadComplete () is called on halfway, and a problem that responding is stopped halfway.

**Comment by qeesung** [comment]
You shouldn't do any blocking in the IO thread, otherwise it will block the IO operation.

Why can the client receive all the data when writing a small amount of data, but only part of the data when writing a lot of data?

This is because TCP has a local buffer queue and sliding window. If a small amount of data is written, the data can be put into the buffer queue of the kernel at one time (the subsequent kernel will send the data to the client), but if too much data is written at one time, it may cause too much data to be accumulated in the buffer queue of the kernel, thus causing the socket to be unwritable.

Now back to Netty, when you call `writeAndFlush`, netty puts the data into a buffer queue, and then, when the socket is writable, writes the data into the socket as much as possible. If a large amount of data is written at one time, netty can only write part of the data into the socket. Until the next time the socket is writable, it writes the rest of the data.

So if you call `Thread.sleep` to block the IO thread, then after netty writes part of the data, it will be blocked until `Thread. sleep` returns to write the remaining data.

**Comment by qeesung** [comment]
You shouldn't do any blocking in the IO thread, otherwise it will block the IO operation.

Why can the client receive all the data when writing a small amount of data, but only part of the data when writing a lot of data?

This is because TCP has a local buffer queue and sliding window. If a small amount of data is written, the data can be put into the buffer queue of the kernel at one time (the subsequent kernel will send the data to the client), but if too much data is written at one time, it may cause too much data to be accumulated in the buffer queue of the kernel, thus causing the socket to be unwritable.

Now back to Netty, when you call `writeAndFlush`, netty puts the data into a buffer queue, and then, when the socket is writable, writes the data into the socket as much as possible. If a large amount of data is written at one time, netty can only write part of the data into the socket. Until the next time the socket is writable, it writes the rest of the data.

So if you call `Thread.sleep` to block the IO thread, then after netty writes part of the data, it will be blocked until `Thread. sleep` returns to write the remaining data.

**Comment by lifeinwild** [comment]
Thank you for your reply. Very easy to understand.

The line in the code that a ChunkedStream is not received is simply my mistake. I think this is because there is no ChunkedWriteHandler in the pipeline.

The problem was solved.
