### ISSUE TITLE
NotSslRecordException with Java 11 JDK SSLProvider

### ISSUE THREAD

**Issue by mp911de** [netty/netty#9216]
### Expected behavior

SSL handshake succeeds.

### Actual behavior

When using Java 11+ with TLS 1.3, SSL negotiation fails with:

```
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 8ec407d00e000000
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
		at io.r2dbc.mssql.client.ssl.TdsSslHandler.channelRead(TdsSslHandler.java:363)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
		... 18 more
	Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: db34cbdf0e000000
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1206)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
		... 21 more
```

The reported byte sequence is always different, but always the last 8 byte of the first received SSL handshake packet.

Full traffic (`LoggingHandler`): https://gist.github.com/mp911de/33e9d19332ac77b5b73e7d7d3f56c5f8

Full traffic (Wireshark): [r2dbc-mssql-tls.pcapng.zip](https://github.com/netty/netty/files/3246204/r2dbc-mssql-tls.pcapng.zip)

### Steps to reproduce

Connect to Azure SQL server via R2DBC MSSQL using Java 11:

SQL Server driver: https://github.com/r2dbc/r2dbc-mssql

```
MssqlConnectionConfiguration config = MssqlConnectionConfiguration.builder()
    .host("abcbookstore.database.windows.net")
    .database("foo")
    .username("foo")
    .password("foo")
    .build();
MssqlConnectionFactory cf = new MssqlConnectionFactory(config);

cf.create().block();
```

### Minimal yet complete reproducer code (or URL to code)

https://gist.github.com/mp911de/3421fa37f71f2032239b3fa60507ebeb

### Netty version

4.1.36.Final

### JVM version (e.g. `java -version`)

Oracle JDK 11.0.1

### OS version (e.g. `uname -a`)

18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Related issue: r2dbc/r2dbc-mssql#77

**Comment by normanmaurer** [comment]
@mp911de I am correct that this is only with JDK SSL implementation and NOT with netty-tcnative ? Also could you test with java8 as well ?

**Comment by mp911de** [comment]
I tested the setup with the JDK implementation only so far. Here are test results with tcnative and Java 8/Java 11:

* BoringSSL Java 8 (default config): works
* JDK SSL Java 8 (default config): works
* BoringSSL Java 11 (default config): works
* BoringSSL Java 11 TLSv1.3: remote peer closed (server failure)
* JDK SSL Java 11 (default config): NotSslRecordException
* JDK SSL Java 11 TLSv1.3: remote peer closed (server failure)

Because Java 8 works and Java 11 does not with the JDK SSL impl I assumed it's related to TLS 1.3. Seems the remote side does not work with TLS 1.3, so relabelling this ticket to NotSslRecordException with Java 11.

**Comment by normanmaurer** [comment]
@mp911de what happens if you "force" non TLS1.3 ciphers and so also TLS1.2 ?

**Comment by mp911de** [comment]
JDK 11 SSL
* SSLv2Hello: Works
* SSLv3: Works
* TLSv1: NotSslRecordException
* TLSv1.1: NotSslRecordException
* TLSv1.2: NotSslRecordException
* DTLSv1.0: Works
* DTLSv1.2: Works

**Comment by normanmaurer** [comment]
@mp911de is there any way to reproduce this locally without azure ?

**Comment by mp911de** [comment]
No, I haven't found a reproducer without Azure yet. I can provide you with an instance if that works for you.

**Comment by arunim29** [comment]
Hi, I am facing the issue even when using JDK 8. I raised a ticket with microsoft regarding this. So, they asked for the network traces. I sent them two network traces. 
![image](https://user-images.githubusercontent.com/53040069/61444829-cdbebb00-a969-11e9-8022-ec8e759f85ed.png)
This trace was captured when using JDBC for connecting to azure SQL db. 

The analysis is -:
This three messages are showing that the connection was well done:
1. Client Hello -> The client machine sends a message to the SQL Server
2. Handshake -> 10 frames later, the Client machine trade cipher suites using TLS 1.2
3. Change Cipher Spec -> Server replies with ChangeCipherSpec confirming that the TCP connection succeeded.

![image](https://user-images.githubusercontent.com/53040069/61444911-f2b32e00-a969-11e9-8688-23bc0c9fcdbf.png)

This trace was captured when using R2DBC for connecting to azure SQL db.
Now looking for the highlighted frames:
1. Client Hello -> Ok. This can be found
2. Handshake -> This is missing. The client machine is not sending its handshake TLS specifications.
3. Change Cipher Spec -> This is still missing, because the handshake was not sent by the client

So, the server is responding in the same way in both JDBC and R2DBC, but the R2DBC library is not able to understand the server.

If you need anything more, let me know.

**Comment by normanmaurer** [comment]
@mp911de yes please ... I have no way how to reproduce :/

**Comment by mp911de** [comment]
I forwarded you a reproducer including the server coordinates via mail.

**Comment by mp911de** [comment]
The problem happens entirely in the library, not an netty issue. The actual cause is packet fragmentation and improper packet aggregation.

For some reason, it kept working in most Java 8 scenarios, therefore, I was blinded by a relation to the used Java runtime version.

**Comment by mp911de** [comment]
Thanks @normanmaurer for your help and your time.

**Comment by Abilash02** [comment]
Hi @mp911de  , Could you please explain in detail  about the  cause (improper packet fragmentation and packet aggregation) 
Experiencing the same issue

**Comment by Surya-V-28** [comment]
Aby Updates on this issues
