### ISSUE TITLE
HttpProxyHandler does not work with http url !!! https works fine

### ISSUE THREAD

**Issue by hongdaliu** [netty/netty#9302]

**Comment by normanmaurer** [comment]
@hongdaliu please provide some re-producer code

**Comment by slandelle** [comment]
I personally never expected clear HttpProxyHandler to support clear HTTP. The current implementation is intended for HTTP tunneling, hence with a preflight CONNECT request.
Clear HTTP proxy is simply a matter of connecting to the proxy instead of the target host and using a full url for the request instead of a relative one. Not sure it’s worth having a handler for this.

**Comment by normanmaurer** [comment]
Ah now I understand... so yes this is expected as @slandelle already noted above.
