### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by PanTang123** [netty/netty#9330]
### JVM version jdk 1.8

![image](https://user-images.githubusercontent.com/32662068/60697348-6726af80-9f1c-11e9-8b5d-ac8060296911.png)

![image](https://user-images.githubusercontent.com/32662068/60697364-802f6080-9f1c-11e9-9080-b9522a556301.png)

**Comment by normanmaurer** [comment]
This is expected as you call `readBytes` which will allocate a new `ByteBuf` and copies the bytes into it. Because of this you are responsible to call `bodyBytes.release()`.

That said I think what you want to use here is `readSlice(...)` which will just slice out some parts of the `ByteBuf` without a memory copy. In this case you also don't need to call release() as it shares the same underlying storage as the original buffer.
