### ISSUE TITLE
HpackEncoder writing headers does constantTime lookup

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#9671]
Looking at a profile of a client that sends a lot of http2 requests, I did notice that HpackEncoder spends some unnecessary time in encoding headers.

This is because in this place:
https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackEncoder.java#L173
it does a lookup for an already existing header.

I do understand the idea of not leaking timing information in sensitive code, but I struggle to see that this place could be one where it could apply (especially as the follow up code will make it sidechannel observable which code path was followed)

**Comment by normanmaurer** [comment]
@carl-mastrangelo PTAL

**Comment by normanmaurer** [comment]
Also @bryce-anderson

**Comment by bryce-anderson** [comment]
I'd strongly suggest getting someone with a security background to weigh in, but here are my 2 cents.

It looks like there are comparison early-aborts for differences in length and key hashcode, so if you're benchmarking and using identical headers I doubt we'll get better performance. However, I suspect the line

```java
if (e.hash == h && (equalsConstantTime(name, e.name) & equalsConstantTime(value, e.value)) != 0) {
  return e;
}
```
would be roughly as safe and potentially faster if changed to
```java
if (e.hash == h && equalsConstantTime(value, e.value) && equalsConstantTime(name, e.name)) {
  return e;
}
```
for headers with the same key but varying values.

**Comment by normanmaurer** [comment]
Maybe @Lukasa ....

**Comment by Lukasa** [comment]
Huh, I'm somewhat surprised to see a constant-time comparison for HPACK header fields in this case.

The reason to want to perform constant-time comparisons when querying the HPACK table is to prevent a side-channel leaking the value of sensitive headers, such as cookies or authorisation headers. The side-channel in question can only exist when running HTTP/2 in a coalescing configuration where there are multiple peers sharing the same HPACK table (otherwise HPACK tables are per-connection, which in a client-server mode is not a shared resource).

The first note here is that I think there is zero security value in performing a constant-time comparison of the field name. Header field names are not per-client and highly unlikely to contain sensitive content, so the odds of anyone launching this side channel attack on a header field name are approximately zero. So we can throw that bit away entirely and just use a regular string comparison. (I'd say this applies more generally to the rest of this code, I can see no value in ever performing constant-time string comparison on HPACK field names.) This is basically an evolution of @bryce-anderson's proposal: in addition to removing the bitwise comparison, we can remove the `equalsConstantTime` on the name, and go back to comparing the name first (we don't have a side channel if we never even look at the value, so comparing the names first is fine).

Doing the constant-time comparison on the value is more interesting. A general solution is not really available: we can rely on sensitive header detection which should eliminate issues regarding Cookie or Authorization, but people love putting sensitive information in all kinds of random headers and we can't _a priori_ know which ones they'll use. If we wanted to be maximally defensive we can keep the constant time comparison on all values. A more pragmatic approach might be to do it only on sensitive headers. This reflects the fact that another side channel exists: compressed HPACK block size. Sensitive headers that we'd want to defend with constant time string comparison should never enter a HPACK compression table in the first place, so arguably that's the only case in which we'd need to do it here.

**Comment by Lukasa** [comment]
The relevant counter argument comes from @jpinner's original comment [here](https://github.com/netty/netty/issues/5436#issuecomment-227928988):

> The compare does predate the inclusion of the "never index" flag. That being said I can certainly think of "sensitive" headers that you might want to index for performance in the table (e.g. domain cookies sent on every request).
> 
> I personally would be cautious here.

**Comment by Lukasa** [comment]
I disagree with Jeff's argument: while the caution is understandable I think the timing side channel is no more vital to defend against than the sizing side channel, and the only defence against that side channel is never indexed headers. That's the correct solution to here. The performance gain of putting "sensitive" headers in the table is likely to be utterly dwarfed by the performance cost of doing constant-time comparisons for every table lookup.

**Comment by Lukasa** [comment]
As some relevant context, neither of the two implementations I wrote perform constant-time comparisons here. Neither does [nghttp2](https://github.com/nghttp2/nghttp2/blob/d08c43951f5bf599dace882ed0e67ded2ff8519e/lib/nghttp2_hd.c#L501-L509) or [h2o](https://github.com/h2o/h2o/blob/1defc77a2243804d06401a9331ecf81735606f9c/include/h2o/memory.h#L476-L486) as two other prominent implementations.

**Comment by normanmaurer** [comment]
@Lukasa thanks again for all the thoughtful comments :) I knew why I pinged you here. 🍻 on me.

@bryce-anderson @CodingFabian WDYT ? Any takers ?

**Comment by carl-mastrangelo** [comment]
Jumping ahead without reading the thread.  I had  PR that mostly removes the overhead.  @CodingFabian   Would https://github.com/netty/netty/pull/9259  fix this for you?  Is there anyway you can patch in that PR and see if it helps?

**Comment by CodingFabian** [comment]
@carl-mastrangelo The PR will pretty likely fix it for me. I will patch my current version and come back.

**Comment by normanmaurer** [comment]
@CodingFabian thanks... please keep us posted.

**Comment by CodingFabian** [comment]
I had a look at the PR #9259 by @carl-mastrangelo and compiled 4.1.42 with it, to replace the same version I ran the original experiments / profiling with.

As expected all the calls disappeared (well the code no longer calls them, duh :))

The only really scientific statement I can do is that while previously header encoding showed up in the top list, it now does not anymore. 

so in a sense #9259 fixes this issue.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/9259
