### ISSUE TITLE
[Discussion] Support readv() on Linux

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#9723]
I would like to get some feedback on some work I plan on doing for Netty that enable using the `readv` syscall.   Today, there is a `RecvByteBufAllocator` which is attached to the channel that is used to support reading in data.  It allocates a single buffer, keeping track of how much data to allocate.   I am considering making the following changes:

1.  Make a custom ByteBuf type akin to CompositeByteBuf, which cannot grow in side (i.e. there are a fixed number of nio buffers).  
2. If the RecvByteBufAllocator returns such a type, the readv() syscall can be used.  For Nio sockets this means being able to use ScatteringByteChannel, and using a `readv()` JNI wrapper for Epoll.   I don't know enough about Kqueue to support this, but in the future it could be added.
3.  Modify RecvByteBufAllocator to not use `guess()` somehow.    The guess() function is use to strongly limit how much data can be read at a time, but this is harder to express in a vector read.  Guess makes sense when coming from a world of single buffer reads, as it's easy to slice the destination down to size.   But a vectored read is not so clear.   I don't know exactly how this can work (hence this issue), but I am thinking some how returning a negative number for guess() mean disabling it.

@normanmaurer @njhill     thoughts?

**Comment by njhill** [comment]
@carl-mastrangelo that's a interesting idea. Could you elaborate on why it would be beneficial? A "guess" still needs to be made for the cumulative capacity of the receiving buffer(s) for each read, and so why not just use a single contiguous buffer in that case (as is currently done)?

Is it to make over-guessing less costly, i.e. we can immediately release any unused buffers at the end of the vector once the read has completed? and/or to more tightly integrate with the underlying allocator so that we can more effectively soak up fragmented unused space in the arenas/caches and thus make more efficient use of mem overall?

Both of those sound reasonable, but there's additional pros/cons to passing a non-contiguous buffer up the pipeline especially if "granular" decoding is to be done because of the additional indirection and offset arithmetic required on every access.

That said I have some changes to `ByteToMessageDecoder` in the works which should be complimentary and help mitigate that last part (hopefully ready soon!)

**Comment by carl-mastrangelo** [comment]
> Is it to make over-guessing less costly, i.e. we can immediately release any unused buffers at the end of the vector once the read has completed?

It's similar, but the opposite direction.  I want to try out a buffer allocator with vector of exponentially larger chunks.  For example, the buffer would contain a slice of: [64, 128, 256, 512, 1024, 2048, 4096, ...., 32768].  The behavior I have seen with the existing allocator is that it tries to guess how big the buffer should be, but gets into a degenerate state if the message size is slightly larger than the recv buffer size.   

For example, if frequently receiving a message of size 70K, it typically gets broken up into a read of size 64k, followed by another syscall of size 6k.    This leads to a bimodal message size distribution, which the recv allocate has a hard time learning.  It leads to extra syscalls, basically.   The idea I want to explore is using a vector of growing slices, which should always be big enough for bimodal read() sizes.   The reason for being exponential is that it's very easy to calculate where the index should be using some bit magic.  

I don't know if this idea will end up being faster or slower, but the current allocator doesn't allow using a slice of buffers easily, so I can't really test it out.  I have a hacked allocator to show the direction I am going:

https://github.com/carl-mastrangelo/netty/commit/6b0cf9edbba301101b8b77d0b532a9fa5b3c6a2b#diff-fbadef790f6a5d35b727f409b04db054R51

> That said I have some changes to ByteToMessageDecoder in the works which should be complimentary and help mitigate that last part (hopefully ready soon!)

SGTM

**Comment by normanmaurer** [comment]
@carl-mastrangelo couldn't you do something like https://github.com/netty/netty/pull/9509 ?

**Comment by njhill** [comment]
#9509 was beneficial because we were otherwise constrained to a single packet per read, but in the TCP case there's just a single contiguous recv buffer. Wouldn't the the combined size of your array of buffers just be equivalent to the existing max read size (== "guess"), and so still need to be determined somehow? The larger ones towards the end will still need to be allocated (if I understand correctly) and so it's not like less mem will be needed, just that it might be free-able a bit sooner.

Did you consider enhancing the adaptive algorithm/heuristics to better accommodate the case described? I don't recall the details of it, but thought that the "message size" reported back should be able to span multiple reads and thus the `RecvByteBufAllocator` should be able to know when it's in a situation where the predicted message size is larger than the configured max input buffer length (which I think defaults to 64k) and take that into account. i.e. after the 64k buffer has been allocated but no "message read" report comes back, it would know that the next size only needs to be ~6k.

Of course I guess the best way to reduce syscalls in the case you mentioned would be to just increase the max recv buffer size to something > 70k (in both netty and OS)?

Apologies if there's still something I've missed or misunderstood, which I realize is likely!

**Comment by ninja-** [comment]
This is an interesting idea.
![1299612647186](https://user-images.githubusercontent.com/5637961/67888829-16336a80-fb4e-11e9-98ce-c551394752c1.jpg)

**Comment by normanmaurer** [comment]
@carl-mastrangelo are you still interested in this or should we just close it ?

**Comment by carl-mastrangelo** [comment]
@normanmaurer it can be closed.
