### ISSUE TITLE
Netty Http2 client in example not connecting to all h2 servers which browsers can connect to(SSL problem)

### ISSUE THREAD

**Issue by bishwenduk029** [netty/netty#9815]
### Expected behavior
Creating a client with InsecureTrustManagerFactory should allow connection to any h2(Http2 over TLS) web server like webtide.com or deckofcardsapi.com.

### Actual behavior
Encountering an exception "Received fatal alert: handshake_failure".

### Steps to reproduce
The Netty example project for http2 client can be re-used for reproducing the by just changing the host to deckofcardsapi.com and port to 443 and url to "/api/deck/new/shuffle/?deck_count=1"

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java

### Netty version
Netty-All 4.1.41.Final

### JVM version (e.g. `java -version`)
Java-8
### OS version (e.g. `uname -a`)
MacOS

**Comment by hyperxpro** [comment]
TLS Handshake is failing because to SNI is not specified in TLS Client Hello request. Just change this code: https://github.com/netty/netty/blob/41c47b41bf0caa2f0faffec901a374516fbd19f7/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L101

pipeline.addLast(sslCtx.newHandler(ch.alloc())); -> pipeline.addLast(sslCtx.newHandler(ch.alloc(), Http2Client.HOST, Http2Client.PORT));

**Comment by hyperxpro** [comment]
TLS Handshake is failing because to SNI Extension is not specified in TLS Client Hello request. Just change this code: https://github.com/netty/netty/blob/41c47b41bf0caa2f0faffec901a374516fbd19f7/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L101

pipeline.addLast(sslCtx.newHandler(ch.alloc())); --> pipeline.addLast(sslCtx.newHandler(ch.alloc(), Http2Client.HOST, Http2Client.PORT));

This will add SNI Extension in TLS Client Hello request.

**Comment by normanmaurer** [comment]
@hyperxpro can you do a PR ?

**Comment by hyperxpro** [comment]
> @hyperxpro can you do a PR ?

Sure
