### ISSUE TITLE
Can we use thread variables instead of global variables, such as UnpaddedInternalThreadLocalMap.nextIndex?

### ISSUE THREAD

**Issue by JulyJunWu** [netty/netty#9945]

**Comment by JulyJunWu** [comment]
When we use FastThreadLocal, we know that this is to get the variable from the current thread according to the index, but if the index becomes large, such as 10000, then when different threads use the new FastThreadLocal, the capacity needs to be expanded, causing unnecessary waste of space.

**Comment by Cybermaxke** [comment]
Yeah, when constructing a lot of a `FastThreadLocal`s (and gc cleaning old ones up) eventually you'll get a very large backing array because of the constantly increasing index. To prevent this, the index should be "recycled" in some way.

Alternatively, after a certain threshold, fallback to an `IntObjectMap` instead of an array.

**Comment by normanmaurer** [comment]
@Cybermaxke @Cybermaxke I am happy to review a PR.

**Comment by normanmaurer** [comment]
@JulyJunWu @Cybermaxke I wonder why you would create a lot of these ?
